kubernetes-sigs/node-feature-discovery

main.go
sources.go

The fake source adds three fake features. I tested it manually. 
```sh
>docker run quay.io/kubernetes_incubator/node-feature-discovery:31ec894-dirty --source=fake --no-publish
2016-10-25 22:04:09.446666 I | node.alpha.intel.com/node-feature-discovery.version = 31ec894-dirty
2016-10-25 22:04:09.446939 I | node.alpha.intel.com/31ec894-dirty-fake-fakefeature1 = true
2016-10-25 22:04:09.447595 I | node.alpha.intel.com/31ec894-dirty-fake-fakefeature2 = true
2016-10-25 22:04:09.447659 I | node.alpha.intel.com/31ec894-dirty-fake-fakefeature3 = true
```

Added fake feature source for testing purposes.

---

README.md
main.go

Usage was amended in #20. Replaced ascii-cast w/ plain text to make this easier to keep up to date.

Updated CLI usage info in README.

---

README.md
main.go
main_test.go
mockapihelpers.go

Took a stab at #25. Appreciate any feedback.
Modifies AddLabels() to first remove any non-discovered nfd labels from
the node labels before adding newly discovered labels.
Adds tests to main_test.go to test the behavior of AddLabels.
edit:
This deletes non-discovered labels including those that may not be "discovered" because of the whitelist option. Wanted to make sure I called that out.

Fixes #25: Deletes non-discovered nfd labels

---

main.go

Previously the output for labels/nfd version was output to stderr along with errors. This PR adds stderr/stdout loggers and outputs labels/nfd version to stdout. This doesn't change the output on the terminal but it does allow another tool to deal with stdout and errors separately. 
Before:
```
-% docker run quay.io/kubernetes_incubator/node-feature-discovery:419702fc3dc8 2> error
-% cat error                                                                                                                                                                                                                                                                                    
2016-10-28 21:26:44.023070 I | node.alpha.intel.com/node-feature-discovery.version = 769caf8-dirty
2016-10-28 21:26:44.023294 …
```

Fixes #21: Splits label/version output to stdout

---

main.go
main_test.go
sources.go
test_sources.go

Fixes #37.
- Handles errors from discovery of source.
- Handles panics from discovery of source using recover().
- Added tests.
Before: 
```sh
>docker run quay.io/kubernetes_incubator/node-feature-discovery:e7f35ed --sources=cpuid,pstate,fake --no-publish
2016/11/15 22:39:55 node.alpha.intel.com/node-feature-discovery.version = e7f35ed-dirty
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-NX = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-MMX = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-SSE = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-SSE4.2 = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-RDTSCP = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-RDSEED = true
2016/11/15 22:39:55 node.alpha.intel.com/nfd-cpuid-MMXEXT = true
2016/11/15 …
```

Enabled graceful failure if discovery for a source fails.

---

README.md
main.go

Fixes #27.
- Changed prefix from `node.alpha.intel.com/nfd` to
`node.alpha.kubernetes-incubator.io/nfd`

Update published label prefix.

---

Dockerfile
Makefile

Fixes https://github.com/kubernetes-incubator/node-feature-discovery/issues/54. Tested manually.
- Removed demo directory from .dockerignore.

Fix to report the correct version inside container.

---

rdt-discovery/l2-allocation-discovery.c
rdt-discovery/l3-allocation-discovery.c
rdt-discovery/monitoring-discovery.c
sources.go

Fixes #42 
- Updated RDT helper programs.
Manually tested. See below.
```sh
>docker run quay.io/kubernetes_incubator/node-feature-discovery:b44b054-dirty --no-publish
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/node-feature-discovery.version = b44b054-dirty
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-SSE = true
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-SSSE3 = true
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-AESNI = true
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-CLMUL = true
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-RDSEED = true
2016/12/09 22:53:32 node.alpha.kubernetes-incubator.io/nfd-cpuid-CMOV = true
2016/12/09 22:53:32 …
```

Upated RDT Discovery() to use exit status

---

Dockerfile

currently, nfd framework can't be work on Arm64 platform.
Fix points:
1, removed rdt on Arm64 platform
2, optimized the code related to multi-arch
Change-Id: If605041f6d2243ae2afb3248edbf102083c6dcb4
Signed-off-by: Bin Lu <bin.lu@arm.com>
Jira: ENTOS-432

enable nfd framework on Arm64 platform

---

label-nodes.sh
main.go
node-feature-discovery-job.json.template

spec.nodeName allows to get node name directly, without
using pod and podnamespace as intermediate steps.
This PR resolves #41

Get node name from spec.nodeName instead of indirectly from pod.

---

README.md
main.go
main_test.go
source/storage/storage.go

Add label if any non-rotational block device is present in the node.
The label will be: nfd-storage-nonrotational=true
This change also adds feature source "storage".
Fixes #85 
Note that during label creation it is not known how devices are actually
used by pods, so the approach is simplistic, and more sophisticated
logic will be needed at some level to make precise decisions.
But labeling "if any SSD present" should cover simple cases reasonably.

Added nonrotational storage detection

---

README.md
main.go
main_test.go
source/memory/memory.go

If multiple nodes are marked online in
/sys/devices/system/node/online, it's a sign of NUMA
architecture. Mark it using nfd-memory-numa label.
Fixes #84 
Here is one way of detecting NUMA architecture based on number of online nodes.
Please comment if you see some problems with such detection.
I have verified it on single-node and 2- and 4-node NUMA systems.

Add memory source and NUMA detection.

---

README.md
main.go
main_test.go
node-feature-discovery-job.json.template
source/selinux/selinux.go

This commit:
- enables node-feature-dicovery to advertise selinux status
on the node by adding a label.
- update the template to mount /sys into the container, this is
needed to know about the selinux status on the host
- adds selinux source for unit tests

Add label to advertise selinux status

---

Dockerfile
rdt-discovery/Makefile

This makes the build more deterministic. Previously, nfd just blindly
took the tip revision from intel-cmt-cat master branch which could brake
the build without any changes in nfd itself.

Use a specific released version of intel-cmt-cat

---

README.md
rdt-discovery/Makefile
rdt-discovery/mem-bandwidth-allocation-discovery.c
rdt-discovery/monitoring-cmt-discovery.c
rdt-discovery/monitoring-mbm-discovery.c
source/rdt/rdt.go

Added more Intel RDT capability discovery: CMT,MBM,MBA
Added Memory Bandwith Allocation (MBA) capability discovery.
Refined RDT monitoring capability detection;
Cache Monitoring Technology (CMT) and
Memory Bandwidth Monitoring (MBM)
capabilities can be detected separately.

Added more Intel RDT capability discovery: CMT,MBM,MBA

---

Dockerfile
rdt-discovery/l2-allocation-discovery.c
rdt-discovery/l3-allocation-discovery.c
rdt-discovery/monitoring-cmt-discovery.c
rdt-discovery/monitoring-discovery.c
rdt-discovery/monitoring-mbm-discovery.c

I discovered outdated links while I was preparing #120:
Source links in rdt-discovery point to 01org area repo which has changed, 
also cap.c source file name has changed.
In Dockerfile also it makes sense to use same repo name (although GH redirects the old name so it works qith both names).
This PR makes no functional changes.

rdt-discovery: update links to intel-cmt-cat source

---

README.md
label-nodes.sh

A "newbie style" deployment attempt was made on a recent
cluster, and some added notes in README and in label-nodes.sh
could help someone who just started with node-feature-discovery.
Correcting also description of label-nodes.sh which does not
deal with unlabeled nodes as was promised in README.

Add, correct some notes in documentation

---

label-nodes.sh

Counting nodes in Ready state was too fragile, matching
entries like:
Ready,SchedulingDisabled
NotReady
By requiring whitespace on both side, we accept only clean Ready.

label-nodes.sh: match Ready without side-strings (#151)

---

Makefile
README.md

Make it possible to specify an image build tool other than docker - a
limitation is that the build tool must be compatible with docker files,
of course. This makes it possible to build an NFD image without the
Docker daemon, for example.
The image build command is specified in a makefile variable and can be
overridden from command line, for example:
$ make IMAGE_BUILD_CMD="buildah bud"

Configurable image build tool

---

README.md

Add a note about required volume mounts when running NFD directly with
docker run.

Mention volume mounts in README

---

.travis.yml
Dockerfile
rdt-discovery/Makefile

This reduces the image basically to size of the debian stretch minimal base image. I.e. size drops from ~1.2GB to ~75MB. Targeted against #129

Utilize multi-stage build to reduce docker image size

---

README.md
main.go
main_test.go
node-feature-discovery.conf.example
source/pci/pci.go

This feature source detects the presence of PCI devices (#167).
This PR also adds support for configurability via a config file and/or the `--options` command line flag.
The PCI feature source has two configuration options:
- device classes to detect
- PCI Id fields to present in the node label name

Implement PCI feature source

---

README.md
demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
demo/helper-scripts/demo-pod-with-discovery.yaml.parsec.template
main.go
main_test.go
mockapihelpers.go

This PR incorporates multiple changes to how NFD manages and advertises node features:
* label namespace is changed to `feature.node.kubernetes.io`
* `nfd` prefix is dropped from the feature label names
* NFD version label (`node.alpha.kubernetes-incubator.io/node-feature-discovery.version`) is dropped and replaced with an annotation
* NFD-specific annotations are added (namespace `nfd.node.kubernetes.io`):
* `nfd.node.kubernetes.io/version` for advertising NFD version
* `nfd.node.kubernetes.io/feature-labels` for advertising for keeping track of feature labels managed by NFD
After this change the naming scheme for all feature labels is:
```
feature.node.kubernetes.io/<source name>-<feature name>
```

Change feature label namespace

---

README.md
main.go
main_test.go
source/local/local.go

Implement a new feature source named 'local' whose only purpose is to
run feature source hooks found under
/etc/kubernetes/node-feature-discovery/source.d/ It tries to execute all
files found under the directory in alphabetical order.
This provides a mechanism for users to implement custom feature sources
in a pluggable way, without modifying nfd source code or Docker images.
The hooks are supposed to print all discovered features in stdout, one feature per line. Normally, the name of the feature label is composed of the hook and feature names, separated by a dash. However, if the feature name (that the hook prints) starts with a slash (`/`) it is used as is in the label name.
The value of the label is either `true` (for binary labels) or `<value>`        
(for non-binary labels). …

Support feature detector hooks

---

Makefile

Docker v17.07 and later supports configuring proxy servers via the
docker client configuration (https://docs.docker.com/network/proxy/).
This is better than using --build-args for passing the proxy settings to
the build environment. Previously, we could end up with empty variables
values which could cause the build to fail. E.g. if you had
http_proxy=<myproxy> defined but HTTP_PROXY unset in the host
environment, you ended up with http_proxy=<myproxy> and HTTP_PROXY=""
(i.e. empty value) inside the build which caused problems in some cases.
In addition, this makes builds via make and directly with docker more
similar.

Makefile: drop docker build-args for https(s) proxy

---

README.md
demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
demo/helper-scripts/demo-pod-with-discovery.yaml.parsec.template

Remove 'nfd' label prefix from README and demos.
Remove references to nfd version label from README

Fixes to label naming change

---

README.md
RELEASE.md

Change links in README.md and RELEASE.md to point to the new repo
location under kubernetes-sigs. Also, remove some outdated references to
kubernetes incubator project.

Refer to kubernetes-sigs in the documentation

---

README.md
main.go
main_test.go
node-feature-discovery-daemonset.yaml.template
node-feature-discovery-job.yaml.template
source/system/system.go

Implement new 'system' feature source. It now detects OS release                
information from the os-release file, assumed to be available at                
/host-etc/os-release. It currently creates two labels (assuming that the        
corresponding fields are found in the os-release file), with example            
values:                                                                         
feature.node.kubernetes.io/system-os_release.ID=opensuse                      
feature.node.kubernetes.io/system-os_release.VERSION_ID=42.3                  
Also, update the template spec to mount /etc/os-release file from the           
host inside the container.

OS version detection

---

README.md
main.go
main_test.go
source/cpu/cpu.go

Currently, it only discovers one feature label, i.e. 'logical-cpus',
which basically tells if hyper-threading has been enabled. However, the
label is not named 'hyper-threading' because the setting is not detected
directly, and, the heuristics can be mislead. NFD determines the thread
siblings of each (logical, online) cpu in the system. If any cpu has
thread siblings the feature is set to true. Thus, hyper-threading could
be effectively disabled by putting all sibling cpus offline (even if HT
would be enabled in hardware).

Implement cpu feature source

---

README.md
main.go
main_test.go
source/kernel/kernel.go
source/kernel/selinux.go

Remove the 'selinux' feature source and move the functionality under the
'kernel' feature source. The selinux feature label is changed to
feature.node.kubernetes.io/selinux.enabled
The selinux feature source was rather narrow in scope, and, the sole
feature it advertised naturally falls under the kernel feature source.

Move selinux detection to kernel feature source

---

README.md
source/system/system.go

Add two new attributes 'VERSION_ID.major' and 'VERSION_ID.minor' to the
os_release feature. These represent the first two components of
the OS version (version components are assumed to be separated by a
dot). E.g. if VERSION_ID would be 1.2.rc3 major and minor versions would
be 1 and 2, respectively:
feature.node.kubernetes.io/system-os_release.VERSION_ID=1.2.rc3
feature.node.kubernetes.io/system-os_release.VERSION_ID.major=1
feature.node.kubernetes.io/system-os_release.VERSION_ID.minor=2
The version components must be purely numerical in order for them to be
advertised. This way they can be fully (and reliably) utilized in
nodeAffinity, including relative (Gt and Lt) operators.

source/system: advertise major and minor OS version

---

main.go

Prevents NFD errors e.g. in the case custom hooks happen to output
invalid label values.

Add validation for feature label values

---

README.md
source/memory/memory.go

Add a new (binary) label indicating the presence of non-volatile DIMM devices:
```
feature.node.kubernetes.io/memory-nv.present
```
Implements #178

source/memory: detect presence of NVDIMM devices

---

README.md
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

As the `local` source is enabled by default, we should mount the directories in the given YAML files
Signed-off-by: Jordan Jacobelli <jjacobelli@nvidia.com>

Mount source.d and features.d in template YAMLs

---

README.md

Move the documentation of the feature detection hooks (i.e. 'local'
feature source) after all other feature sources. It is a more logical
place to document custom user-specific functionality after the built-in
features. Also, adjust the title a bit.

README: move description of hooks to the end of the feature source list

---

Makefile
README.md

Change the structure and naming of the make variables that control the
container image name/tag that gets created. Default values and behavior
stay the same, but, this change tries to make it easier to customize the
build from command line.
Also, document all the relevant make variables in readme.

Makefile: reorganise container image variables

---

.travis.yml

Default language is ruby and we don't need that. The minimal environment
is enough. Also, no su privileges are needed to run the build.

travis: run in minimal environment and drop sudo

---

source/kernel/kernel.go
source/local/local.go
source/network/network.go
source/pci/pci.go

Simplify logging of feature sources. Drop glog which was used in some feature
sources as it was too complicated for the simple logging needs of
NFD.

Simplify logging

---

README.md
label-nodes.sh
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

Point to the latest release in the README, and, point out that a
user-built custom image is required to run the latest development
version. Update the deployment instructions to reflect the need to
specify the container image when using the deployment spec template(s).
Also, update the Job deployment script to set a user-defined container
image.
Use a placeholder for the container image in the template specs as they were not compatible with the image they were pointing to (v0.3.0).

Better document the difference between latest release and master branch

---

README.md
nfd-worker.conf.example
pkg/nfd-worker/nfd-worker.go
source/cpu/cpu.go
source/cpu/cpuid_arm64.go

Add 'cpuid/attributeBlacklist' and 'cpuid/attributeWhitelist' config
options for the cpu feature source. These can be used to filter the set
of cpuid capabilities that get published. The intention is to reduce
clutter in the NFD label space, getting rid of "obvious" or misleading
cpuid labels. Whitelisting has higher priority, i.e.  only whitelist
takes effect if both attributeWhitelist and attributeBlacklist are
specified.

source/cpu: make cpuid configurable

---

README.md
cmd/nfd-master/main.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker.go
source/local/local.go

The aim here is to allow to override the default namespace of NFD. The allowed namespaces are whitelisted.
Close https://github.com/kubernetes-sigs/node-feature-discovery/issues/227
Signed-off-by: Jordan Jacobelli <jjacobelli@nvidia.com>

Allow to change labels namespace

---

README.md
label-nodes.sh

The former usage of slash as a delimiter did not play well together
with container image tags that usually contain slashes themselves.

Change the sed delimiter in deployment instructions

---

README.md
label-nodes.sh
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

Also, slightly adjust the deployment instructions in README to point out
that the templates should now be usable as is to run the latest released
version of NFD.

Use v0.4.0 release in README and deployment templates and script

---

OWNERS

Remove ConnorDoyle and flyingcougar from the OWNERS file. They haven't
been active in over a year and are not members of the Kubernetes-SIGs
org. We can easily add them back, later, if needed.

Remove inactive approvers from OWNERS

---

source/kernel/kernel.go

Discover other than bool or tristate kconfig options, too. For bool and tristate the node label is still binary (i.e. set to "true" if the kconfig option has been enabled). For other kconfig types (e.g. string or int) the value of the label directly corresponds to the value of the kconfig flag, e.g. "32", "elf64-x86-64" etc.

Support non-binary kconfig options in kernel feature source

---

source/kernel/kernel.go

Fix a build failure that slipped through when adding support for
non-binary kconfig options in #197,

kernel: fix undefined symbol error

---

README.md
source/memory/memory.go

Extend NVDIMM (non-volatile DIMM) discovery by adding detection of DAX
mode, i.e. detection of regions in DAX/AppDirect mode.
The new label is:
feature.node.kubernetes.io/memory-nv.dax: true

source/memory: detect NVDIMM DAX mode

---

.travis.yml
Makefile
README.md

Configure .travis.yml to automatically push builds on the master branch
to the container image registry (quay.io by default). This will automatically
make the latest "experimental" version of NFD, built from the tip of the
master branch, available in the upstream container image repository.
IMAGE_REPO_USER and IMAGE_REPO_PASSWORD environment variables must be defined in
the travis repositorys settings in order for the deployment step to be
triggered.

travis: add deploy step to automatically push docker image

---

label-nodes.sh
nfd-worker-job.yaml.template

Use pod anti-affinity to explicitly indicate that pods should be
scheduled on separate nodes. And, remove the obscure and non-obvious
ports definition whose only purpose was to reach the same effect.

Use pod anti-affinity in the worker Job template spec

---

pkg/nfd-worker/nfd-worker.go

Instead of erroring out right away, try to connect to nfd-master for 60
seconds until giving up.

nfd-worker: try connecting to nfd-master for 60s

---

README.md
source/cpu/cpu.go
source/cpu/pstate.go

Some workloads may benefit from Intel Turbo Boost technology being
disabled. This patch sets the
'feature.node.kubernetes.io/cpu-pstate.turbo' label to 'false' if we can
detect that it has been disabled. If detection fails no label is
published.

source/cpu: support 'false' status of cpu-pstate.turbo

---

Gopkg.lock
Gopkg.toml

Due to the constraint, pretty old version is being used. Update
the cpuid package to the latest master to get, e.g., AVX512_VNNI
and VMX detection.

vendor: update klauspost/cpuid

---

nfd-daemonset-combined.yaml.template

Without this the nfd namespace is not created and the deployment may
fail.

Add nfd namespace to the daemonset-combined deployment template

---

.travis.yml

Integrate end-to-end tests (#181) to Travis.
First, it reworks Makefile, adding targets for pushing images to remote registry and running e2e tests in a (remote) test cluster. Then it adds travis integration (in .travis.yml) for running e2e tests in AWS EKS.
Basically, the following environment variables need to be configured in travis in order to make it work:
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `AWS_REGION`
* `KUBECONFIG_AWS`
* `IMAGE_REPO`
* `IMAGE_REPO_PASSWORD`
* `IMAGE_REPO_USER`

e2e test integration in Travis CI

---

.travis.yml
Dockerfile
go.mod

Update go version in Docker build image to v1.13.5

Update go version in Dockerfile

---

README.md
source/pci/pci.go

SR-IOV is a PCI attribute and also non-NIC PCI devices can have it. Therefore,
it is useful to label all PCI devices with that capability.
After this commit the following labels for Intel NICs are overlapping:
```
feature.node.kubernetes.io/pci-0200_8086.sriov.capable=true
feature.node.kubernetes.io/network-sriov.capable=true
```
Fixes: #286

pci: add sriov.capable attribute

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go
pkg/version/version.go

Just print a warning instead of exiting with an error if no version has
been specified at build-time. This was pointless and just annoying at
development time when doing builds with go directly.

version: allow undefined version

---

source/system/system.go

Do not publish non-existing version components as empty labels.
Reading the description of #297 I realised that it would probably be better to not publish the missing version components as labels with empty values.

source/system: do not publish empty version labels

---

source/kernel/kernel.go

Some Kernel versions include symbols such as "+". Yocto L4T kernel is
an example of this behaviour. To fix this error the symbols are replaced
by an underscore.
Signed-off-by: Pablo Rodriguez <paroque28@gmail.com>
This is associated with issue:
https://github.com/kubernetes-sigs/node-feature-discovery/issues/308

Proposal kernel.go: Replace forbidden symbols and check format

---

README.md
cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
nfd-worker.conf.example
pkg/nfd-worker/nfd-worker.go
source/custom/custom.go
source/custom/rules/usb_id_rule.go
source/internal/pci_utils.go
source/internal/usb_utils.go
source/usb/usb.go

This builds on the PCI support to enable the discovery of USB devices. While we allow for class-based discovery, many USB devices shift this to the interface level instead and have meaningless class values. The vendor and device IDs, therefore, are the main items of interest. This is primarily useful for the discovery of Edge-based heterogeneous accelerators that are connected via USB, such as the Coral USB Accelerator and the Intel NCS2 - our main motivation for this work.

Add support for USB device discovery

---

Dockerfile
Makefile
source/config.go
source/cpu/cpu.go
source/cpu/power_amd64.go
source/cpu/pstate.go
source/internal/pci_utils.go
source/iommu/iommu.go
source/kernel/kernel.go
source/kernel/selinux.go
source/memory/memory.go
source/network/network.go
source/storage/storage.go
source/system/system.go

Specify and handle system paths we use for discovery in a unified way.
Consistently do all sysfs based feature discovery under the same sysfs directory.

source: parametrise host directory paths

---

README.md
cmd/nfd-master/main.go
cmd/nfd-worker/main.go
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go

After commenting #306 I looked into the code and was not happy what I found (with my own work).
Unify handling of --label-whitelist in nfd-worker and nfd-master. That is,
in nfd-worker, apply the regexp filter on non-namespaced part of the
label name.
Brief history:
1. Originally the whitelist regexp was applied on the full namespaced
label name (that would be e.g.
'feature.node.kubernetes.io/cpu-cpuid.AVX' in the current nfd version)
2. Commit 81752b2d changed the behavior so that the regexp was applied
on the non-namespaced part (that would be `cpu-cpuid.AVX`)
3. Commit 40918827 added support for custom label namespaces. With this
change, the label whitelist handling diverged between nfd-worker and
nfd-master. In nfd-master the whitelist regexp is always applied on
the non-namespaced …

nfd-worker: fix --label-whitelist

---

nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
source/network/network.go

The default deployment mounts /sys from the host under /host-sys so
let's use that. No need to use hostNetwork after that so drop it from
the worker deployment templates.

source/network: run discovery under /host-sys

---

README.md
source/cpu/cpuid_arm.go

This provides support for 32-bit ARM cpuid capabilities based on
the HWCAP flags, and enables the build of NFD on the 32-bit ARM
userland - notably, this also applies to ARM64 systems that are
running userspace in Aarch32 mode, which is where this problem
was first encountered.

cpu: Add support for ARM/Aarch32 cpuid

---

.travis.yml
Dockerfile

Go versions after 1.13.7 contain fix for CVE-2020-7919

Update builder image to Go 1.13.12

---

.travis.yml
Dockerfile
go.mod

Go 1.14.2 is stable enough for us to move from 1.13 at this point
after this PR we could start thinking updating deps for K1.19

Update go to 1.14.2

---

.travis.yml
Makefile
scripts/test-infra/test-e2e.sh

Add a new script for running end-to-end tests. Implement a Makefile rule
for polling the container image. We need this for prow as there is no
other way for syncing the jobs (e2e postsubmit job must wait until the
image-pushing job has built and published the image). This is
implemented in the Makefile as all the image-related variables are also
defined/available there.
Also, adapt the TravisCI config to use the new script.

scripts/test-infra: add script for end-to-end testing

---

go.mod
go.sum

Update go dep golang.org/x/text
CVE-2020-14040
golang.org/x/text: possibility to trigger an infinite loop in
encoding/unicode could lead to crash
Reported on Bug 1853652

Update go dep golang.org/x/text

---

Makefile
README.md
cloudbuild.yaml
scripts/test-infra/push-image.sh
scripts/test-infra/test-e2e.sh

Use make for building our container image (through a new push-image.sh
script) instead of building directly with docker. This way we avoid the
container image tag naming hassle where we build and push the image on
"image-pushing" prow job and need to be able to reliably re-create the
same tag on the "testing" side for end-to-end tests. This also has the
advantage that the same mechanism (make) is used everywhere, i.e. in
image-pushing, testing and locally.

cloudbuild.yaml: build using make

---

scripts/test-infra/push-image.sh

We don't have a full git repo in the gcb builds so our version/tag magic
inside the makefile does not work. Thus, get version information from
the build information - fortunately we can do that by simply stripping
the date prefix from the _GIT_TAG variable.

scripts: hand-construct a reproducible version

---

cloudbuild.yaml

cloudbuild.yaml: set _GIT_TAG in env

---

scripts/test-infra/push-image.sh

As we're trying to push the images directly from the phase job and not
use 'images:' targets in cloudbuild.yaml.

scripts: configure docker authentication in push-image.sh

---

cloudbuild.yaml

Use the staging image repository for tagging/pushing images. We aren't
able to (and wouldn't want to) push directly to the production
repository that is the default in the Makefile.

cloudbuild.yaml: set correct container image registry

---

README.md
cmd/nfd-master/main.go
pkg/apihelper/apihelpers.go
pkg/apihelper/k8shelpers.go
pkg/apihelper/mock_APIHelpers.go
pkg/nfd-master/nfd-master.go

A new sub-command like flag for cleaning up a cluster. When `--prune` is
specified nfd-master removes all NFD related labels, annotations and
extended resources from all nodes of the cluster and exits.
Also, add new `--kubeconfig` flag. Useful with `--prune` and for development purposes.

nfd-master: implement --prune flag

---

Makefile
README.md

make image and make push fails when trying to set a diff value to
IMAGE_BUILD_CMD, runing the default value

Fix Makefile to take vaules from ENV VAR values

---

Makefile
README.md

An attempt to organize the Makefile variables a bit further. The idea is
to only document variables that are really intended for build
customization and initialize all these variables in the Makefile with
'=?' so that they can be specified in the environment (and not just with
variable overrides). Thus, this patch drops some variables from the
README and change the initialization of some variables in the Makefile
so that the two files would be in sync.

Fix up Makefile variable initialization and documentation

---

scripts/test-infra/push-image.sh

gcloud auth call in push_image.sh test script is no longer needed

Drop gcloud auth for image pushing

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/support.md

This commit adds templates for bug report, feature request and support
related issues.
did this on the operator side, thought is also a good idea for the Operand

Enable issue templates

---

Makefile

Change the default namespace used in deployment yamls from 'kube-system'
to 'node-feature-discovery'. Sync with what the templates have. Also,
this should be a safer and more desirable default for people just trying
out node-feature-discovery.

Makefile: set default deployment ns to node-feature-discovery

---

docs/_config.yml
docs/_includes/class/addons-wrap.liquid
scripts/github/update-gh-pages.sh

Make the list of available versions dynamic. The items displayed is now
generated with javascript. The parent directory of the site is supposed
to contain versions.js providing getVersionListItems() that returns the
available versions.
The update-gh-pages.sh script is modified to update/create versions.js
on every invocation. It simply lists all directories in the root
directory and adds them to the version list.

docs: make the list of available versions dynamic

---

Makefile
docs/_includes/class/addons-wrap.liquid
scripts/github/update-gh-pages.sh
scripts/test-infra/build-gh-pages.sh

Only show the dynamic version menu in production environment where it's
available. Local (development) builds only show a stub version menu with
one item.
Also, fix the theme customization. Append version list items to the
correct element in html so that they are displayed correctly. Drop
unnecessary <div/>.

docs: polish the version menu

---

Makefile
docs/advanced/index.md
docs/contributing/index.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/index.md
docs/get-started/quick-start.md
scripts/github/update-gh-pages.sh

- fix broken refs in docs/
- make Github refs point to `release-0.6` branch:
Point to the tip of the release branch instead of master (or `v0.6.0` tag).
- fixup site baseurl setting (cherry-pick from master):
Change build configuration related to site baseurl and Jekyll output directory a bit. Making it more coherent e.g. by removing the need to override baseurl for 'site-serve' makefile target.

release-0.6: fix broken refs in documentation

---

docs/_config.yml
docs/advanced/developer-guide.md
docs/contributing/index.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/index.md
docs/get-started/quick-start.md
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

Support versioned links to gihub blobs in the documentation. Make the links point to the blob from the release corresponding the documentation.
Change deployment templates to point to staging image. Latest changes on the templates make them unusable with v0.6.0 release. Going forward, we should keep it this way - templates in the master branch should use staging image corresponding the template.

Link to correct Github blobs, use staging images in deployment templates

---

scripts/github/update-gh-pages.sh

Update update-gh-pages.sh to manage the index.html in the root of the
main gh-pages site. Make the index page to redirect to the documentation
of the latest stable version.

scripts/update-gh-pages: redirect to "stable" documentation

---

test/e2e/e2e-test-config.exapmle.yaml
test/e2e/node_feature_discovery.go

Interpret node names in the e2e test config as regexps instead of plain
strings. This makes it a lot easier to maintain a config file where
multiple nodes share configuration.

test/e2e: interpret node names in config as regexps

---

nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

NFD-Worker does not need write access.

Make all mounts in deployment templates read-only

---

Dockerfile

Container base image updates:
- update builder to golang 1.15.5 (was 1.15.4)
- Be more explicit about using the -buster variant for build image
- Update runtime image from -stretch to -buster to pick up security fixes

Container base image version bump

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
docs/advanced/developer-guide.md
docs/advanced/worker-commandline-reference.md
pkg/nfd-worker/nfd-worker.go

A new special value 'all' is a shortcut for enabling all feature
sources. It should be the only name specified -- if any other names are
specified 'all' does not take effect, but, we only enable the listed
feature sources. E.g.
--sources=all enables all sources, but
--sources=all,cpu only enables the cpu source

nfd-worker: add special handling for --sources=all

---

Makefile
docs/get-started/deployment-and-usage.md
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
scripts/test-infra/verify.sh

Add a virtually empty ConfigMap that is mounted inside the workers.
Makes it easier to start customizing the worker deployment e.g. with just:
`$ kubectl -n ${NFD_NS} edit configmap nfd-worker-conf`
Create a new 'templates' make target for inserting the content of
nfd-worker.conf.example into the configmap spec of the templates. Thus,
'make templates' should be run whenever the example config is update.
Update the verify.sh prow script to check that the templates are up to
date.
This patch also streamlines the documentation about configuration
management, reflecting the changes.

Add nfd-worker-conf ConfigMap to deployment templates

---

source/kernel/kernel.go

Trim illegal characters from the beginning and end of the kernel version
string. Label values must start and end with an alphanumeric and we want
to have some 'version.full' label, even if a sanitized one.
Fixes #390

kernel: more agressively sanitize full kernel version

---

test/e2e/node_feature_discovery.go

Pick the correct rule when multiple node rules are present.

test/e2e: fix e2e-config node matching

---

cmd/nfd-master/main.go
go.mod
go.sum
pkg/apihelper/apihelpers.go
pkg/apihelper/jsonpatch.go
pkg/apihelper/k8shelpers.go
pkg/apihelper/mock_APIHelpers.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/node_feature_discovery.go

When updating node labels and annotations use JSON patches instead of
doing a read-modify-write on the whole node object. Patching is already
being used in managing extended resources so some of the existing code
was re-usable. This should mitigate the problem of node update failures caused by
race conditions (a change in the node object between our read and write)
resulting e.g. in errors/restarts in nfd worker pods.
This patchset also slightly improves the unit tests.
Addresses #122

nfd-master: patch node object instead of rewriting it

---

Makefile

throw an error message before running `e2e-test` if `KUBECONFIG` is not defined 

be a bit more verbose on a required KUBECONFIG env var

---

.github/workflows/gh-pages.yml
scripts/github/update-gh-pages.sh

Only update documentation if the version has been released (i.e. a git
tag corresponding the version we're updating exists) or it is for the
master branch. Prevents us from pointing users to documentation of an
unreleased version.
Also updates github workflow to fetch full commit history (including
tags) so that git describe works correctly.

scripts/update-gh-pages: only update docs if version has been released

---

nfd-prune.yaml.template

Change the template so that our sed magic updates the container image
name correctly.

Fix auto-generation of nfd-prune.yaml

---

docs/get-started/deployment-and-usage.md
nfd-prune.yaml.template

Makes it possible to run prune on its own. Reflect this change in the
documentation.

Add namespace and RBAC rules to nfd-prune.yaml.template

---

docs/get-started/features.md
go.mod
go.sum
source/internal/cpuidutils/cpuid_amd64.go

The latest changes in klauspost/cpuid add detection for Sapphire Rapids
new instructions.

go.mod: update klauspost/cpuid

---

Makefile
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template

Rely on markers instead which makes the update work also in the middle
of a template file. Previously it relied on the configuration data to be
at the very end of the file to be updated.

Change the worker conf update mechanism of templates

---

pkg/apihelper/jsonpatch.go
pkg/nfd-master/nfd-master.go

In JSON and kubernetes API object names we want to use slashes instead
of the OS dependent file path separator.

Replace improper usage of filepath.Join with path.Join

---

go.mod
pkg/nfd-worker/nfd-worker.go

Add support for detecting configuration file changes via file system
notifications (fsnotify). Watches are added for the whole directory
chain (up to root directory) so that all changes (even directory
renames) affecting the given configuration file path are captured.
Previously dynamic (re-)configuration of nfd-worker was implemented by
(re-)reading the configuration file on every labeling pass. This was
simple and effective, even if a bit wasteful. However, it didn't provide
asynchronous configuration updates that will be required for e.g.
controlling the "sleep-interval" parameter dynamically which will be
implemented by later patches.

nfd-worker: use fsnotify for watching for config file changes

---

cmd/nfd-master/main.go
docs/advanced/master-commandline-reference.md
docs/get-started/introduction.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/node_feature_discovery.go

This can be used to help running multiple parallel NFD deployments in
the same cluster. The flag changes the node annotation namespace to
<instance>.nfd.node.kubernetes.io allowing different nfd-master intances
to store metadata in separate annotations.
Related to #427

nfd-master: implement --instance flag

---

Makefile
deployment/node-feature-discovery/.helmignore
deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/templates/_helpers.tpl
deployment/node-feature-discovery/templates/clusterrole.yaml
deployment/node-feature-discovery/templates/clusterrolebinding.yaml
deployment/node-feature-discovery/templates/master.yaml
deployment/node-feature-discovery/templates/nfd-worker-conf.yaml
deployment/node-feature-discovery/templates/service.yaml
deployment/node-feature-discovery/templates/serviceaccount.yaml
deployment/node-feature-discovery/templates/worker.yaml
deployment/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
scripts/prepare-release.sh

This commit adds Helm chart for node-feature-discovery
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>

Add helm chart for NFD

---

deployment/node-feature-discovery/templates/master.yaml
deployment/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

--instance flag was introduce in the e52ec3480fc586211bbdea3c99caa47bf810c72d commit.
This patch adds ability to configure it in the Helm chard during deployment.

Add NFD master '--instance' flag support to Helm chart

---

nfd-worker-daemonset.yaml.template

Remove incorrect tolerations that accidentally crept in with the helm
charts and break the deployment.

Fix daemonset deployment template

---

deployment/node-feature-discovery/templates/master.yaml

Commit 88bd80d415eec5adc6af29bca9aa6509a2300307 introduces error
in template due to the bad formatting. This commit fixes it.

Fix NFD master chart template

---

deployment/node-feature-discovery/values.yaml
docs/get-started/features.md
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
nfd-worker.conf.example
source/custom/custom.go
source/custom/directory_features.go
source/custom/rules/nodename_rule.go
test/e2e/node_feature_discovery.go

With this PR we add a new `nodename` rule for the `custom` source for the NFD worker, which will apply features based on  nodes' hostnames.
For making more dynamic configuration by potentially multiple parties easier, `custom` source rules can also be read from the `/etc/kubernetes/node-feature-discovery/custom.d` directory now (probabaly mostly populated by mounted ConfigMaps).
Also an optional `value` field was added, which allows overruling the default `true` value for matching features if set.
Consider this config:
```
- name: "feature.by.nodename"
matchOn:
- nodename:
- worker-0
- worker-1
- name: "another.features.by.nodename.regex"
value: customValue
matchOn:
- nodename:
- wor.*-0
```
The config will apply the `feature.by.nodename=true` feature to the `worker-0` and `worker-1` …

Added nodename rule to custom source

---

docs/advanced/developer-guide.md
docs/advanced/master-commandline-reference.md
docs/advanced/worker-commandline-reference.md
docs/get-started/deployment-and-usage.md
docs/get-started/features.md

After moving to the flags package for command line argument parsing NFD
accepts command line arguments (flags) starting with a single dash (e.g.
-no-publish in addition to --no-publish). Even if double-dash can be
used the single-dash version is printed e.g. in the usage string (from
-h, -help) so align documentation with that.

docs: align docs with the single-dash command line flags

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
deployment/node-feature-discovery/values.yaml
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
nfd-worker.conf.example
pkg/nfd-worker/nfd-worker.go
pkg/utils/flags.go
source/cpu/cpu.go
source/custom/custom.go
source/custom/directory_features.go
source/custom/rules/nodename_rule.go
source/internal/kernelutils/kernel_kconfig.go
source/internal/pci_utils.go
source/internal/usb_utils.go
source/kernel/kernel.go
source/local/local.go
source/memory/memory.go
source/network/network.go
source/pci/pci.go
source/system/system.go
source/usb/usb.go

Greatly expands logging capabilities and flexibility with verbosity options, among other things.
Also, implement dynamic configuration of klog. I.e. make it possible to dynamically (at run-time) alter most of the logging configuration from the config file.

nfd-worker: switch to klog

---

Makefile
docs/advanced/developer-guide.md
test/e2e/node_feature_discovery.go

Only enabled if OPENSHIFT is specified in the environment when running
make e2e-test, for example:
```
$ OPENSHIFT=y make e2e-test
```

test/e2e: make openshift bits optional

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go
pkg/nfd-worker/nfd-worker.go
source/internal/kernelutils/kernel_kconfig.go
source/internal/pci_utils.go
source/iommu/iommu.go
source/kernel/kernel.go
source/kernel/selinux.go
source/local/local.go
source/network/network.go
source/pci/pci.go
source/usb/usb.go

Standardize logs to be lower cased 
Bonus: Fixed a func comment to start with the func name 

logs should all be lower case when possible

---

Makefile

Formerly used 5 minutes caused timeout in Prow.

Makefile: increase golangci-lint timeout to 7min

---

Dockerfile
Makefile
docs/get-started/deployment-and-usage.md
docs/get-started/features.md
scripts/test-infra/test-e2e.sh

Build a "minimal" variant of the nfd image based on
gcr.io/distroless/base. The motivations behind the minimal image are
image hardening (security) and reducing the image footprint (from ca.
108MB down to about 40MB).
The practical effect of deploying the minimal image is that no runtimes
for running worker hooks are present, not even a shell. This means that
only statically linked linked hook binaries are supported. Also, because
of the image hardening live debugging of the minimal image by attaching
to the container is not possible, and, the "full" image needs to be used
for that purpose.
This doesn't change the default usage/deployment of NFD in any way. Just adds a new image variant that can be alternatively deployed. The minimal variant might become the default in the future, though

Dockerfile: add minimal image

---

pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/fswatcher.go
pkg/utils/tls.go

Leveraging some of the work done on worker config file watcher lately, implement filesystem watcher of TLS certificate files for nfd-master and nfd-worker.

Support TLS certificate updates

---

pkg/utils/grpc_log.go

Unwind two call frames so that the source (file:line) of the log message
is correctly displayed.

pkg/utils: show correct source file in gRPC logs

---

docs/get-started/features.md
source/cpu/cpu.go
source/cpu/cstate.go
source/cpu/pstate.go

This adds additional cpu features:
- pstate enable from status of intel_pstate driver
- pstate performance and powersave settings from scaling_governor
- cstate enable from max_cstates in intel_idle driver
Closes: #439

Support for additional cpu features

---

docs/advanced/customization-guide.md
docs/advanced/developer-guide.md
docs/advanced/e2e-configuration-reference.md
docs/advanced/master-commandline-reference.md
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/introduction.md
docs/get-started/quick-start.md
scripts/test-infra/mdlint.sh

(cherry picked from commit 7fc6cd632c6e65916e577e33b47f4eef40ae1f4b)
Unlike in 7fc6cd632c6e65916e577e33b47f4eef40ae1f4b the wording of all headings is kept intact in order to not break possible external links to the anchors

release-0.7: docs: unify capitalization of headings

---

.gitignore
Makefile
docs/get-started/deployment-and-usage.md
nfd-cert-manager.yaml.template
nfd-master.yaml.template
nfd-worker-daemonset.yaml.template

A POC to use cert-manager to manage nfd-master and nfd-worker certs
TODO:
Closes: #277

use cert-manager for TLS

---

pkg/nfd-worker/nfd-worker.go
pkg/utils/dump.go

Reduce default log verbosity. Only print out labels if log verbosity is 1 or higher (e.g. '-v 1' command line). Also, dump the labels in a reproducible (sorted) format.
Produces logs like this with `-v 1`:
```
I0311 07:15:34.257115   23856 nfd-worker.go:523] labels discovered by feature sources:
I0311 07:15:34.257333   23856 nfd-worker.go:523]   cpu-cpuid.ADX: "true"
I0311 07:15:34.257346   23856 nfd-worker.go:523]   cpu-cpuid.AESNI: "true"
I0311 07:15:34.257367   23856 nfd-worker.go:523]   cpu-cpuid.AVX: "true"
I0311 07:15:34.257373   23856 nfd-worker.go:523]   cpu-cpuid.AVX2: "true"
I0311 07:15:34.257379   23856 nfd-worker.go:523]   cpu-cpuid.FMA3: "true"
I0311 07:15:34.257384   23856 nfd-worker.go:523]   cpu-cpuid.HYPERVISOR: "true"
I0311 07:15:34.257390   23856 nfd-worker.go:523] …
```

nfd-worker: don't log labels returned by sources by default

---

docs/get-started/features.md

Some reference point to the wrong section after headings have changed.

docs: fix some internal references

---

docs/advanced/worker-configuration-reference.md

Add rudimentary documentation of all options related to feature sources.
Now all options are covered in the config reference.

docs: document all config file options

---

nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template

We don't want that as it makes dynamic configuration of the
sleep-interval via the config file impossible. It was set to the
internal default value, anyway.

Remove --sleep-interval flag from worker deployment templates

---

source/custom/custom.go

You get log entries like this (with `-v 1`):
```
I0310 21:59:19.778694   12976 custom.go:84] custom features configuration:
I0310 21:59:19.778963   12976 custom.go:84]   - matchOn:
I0310 21:59:19.778981   12976 custom.go:84]     - pciId:
I0310 21:59:19.778985   12976 custom.go:84]         vendor:
I0310 21:59:19.778988   12976 custom.go:84]         - 15b3
I0310 21:59:19.778991   12976 custom.go:84]     name: rdma.capable
I0310 21:59:19.778994   12976 custom.go:84]   - matchOn:
I0310 21:59:19.778997   12976 custom.go:84]     - loadedKMod:
I0310 21:59:19.779000   12976 custom.go:84]       - ib_uverbs
I0310 21:59:19.779004   12976 custom.go:84]       - rdma_ucm
I0310 21:59:19.779009   12976 custom.go:84]     name: rdma.available
I0310 21:59:19.779015   12976 custom.go:84]   - matchOn:
I0310 …
```

source/custom: dump config in more human-readable form

---

scripts/github/update-gh-pages.sh

Whitespace in release metadata json was not correctly handled.
Not surprisingly, we failed magnificently in production 🤦 
https://github.com/kubernetes-sigs/node-feature-discovery/runs/2137744191?check_suite_focus=true

scripts/update-gh-pages: fix helm repo update

---

scripts/github/update-gh-pages.sh

Whitespace in release metadata json was not correctly handled.
(cherry picked from commit 6541e3bb55638ebbc959609f53662c474ba268f5)

release-0.8: fix helm repo update

---

.github/ISSUE_TEMPLATE/new-release.md
.github/workflows/gh-pages.yml

This will make the Helm repo to be updated at release time.

github: update gh-pages on published releases

---

deployment/node-feature-discovery/values.yaml

the tolerations value is array therefore we need to pass
[] and not {}
Signed-off-by: Moshe Levi <moshele@nvidia.com>

[helm] fix nfd worker tolerations value

---

.github/ISSUE_TEMPLATE/new-release.md
.github/workflows/gh-pages.yml
deployment/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

- github: update gh-pages on published releases – will streamline release process in case we need v0.8.x point releases
- docs: describe Helm repo as the primary option for Helm
- docs: Add Table header to master/worker chart parameters
- helm: fix nfd worker tolerations value

release 0.8: cherry-picks from master

---

deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/templates/nfd-worker-conf.yaml

Currently when the `worker.config` key is being filled with a YAML string literal, it does not render properly and causes Helm errors. This is due to the way the indenting and whitespace trimming is handled.
This PR aims to fix that, by stripping the leading whitespace from the `worker.config` value, and forcing a newline.
Expected to work (snippet):
```yaml
worker:
config: |-
core:
sources:
- custom
- pci
- usb
sources:
usb:
```
Currently required to work (snippet), notice the indenting of `core:` vs the rest of the config file:
```yaml
worker:
config: |-
core:
sources:
- custom
- pci
- usb
sources:
usb:
```

Helm chart: Fix configMap indenting

---

.github/ISSUE_TEMPLATE/new-release.md

Aimed at fixing a problem with misleading version numbers of staging
master builds.
Also, clarify the instructions on upcating the README of the master
branch.
Fixes #448

github: update release process to create a 'devel' tag

---

docs/get-started/deployment-and-usage.md

Use correct spelling of Helm in heading (start with a capital letter).
Use https url for the chart repo.

docs: fixes in Helm documentation

---

docs/get-started/deployment-and-usage.md

Use correct spelling of Helm in heading (start with a capital letter).
Use https url for the chart repo.
(cherry picked from commit 72a4162c98d07a16386a0e025e4b5d0ad4abab64)

release-0.8: docs: fixes in Helm documentation

---

cmd/nfd-master/main.go
deployment/node-feature-discovery/templates/master.yaml
docs/advanced/developer-guide.md
docs/advanced/master-commandline-reference.md
docs/get-started/deployment-and-usage.md
nfd-master.yaml.template
pkg/nfd-master/nfd-master.go

Fix for https://github.com/kubernetes-sigs/node-feature-discovery/issues/511
When VerifyNodeName is on, this change respects SubjectAltName (rather than just CN) in the client cert 
The VerifyHostname method used respects wildcards on the left hand side, so for example a cert with a SAN of *.mycluster.org would match node1.mycluster.org
I've left in the existing common name check to avoid breaking existing clients (Certificate.VerifyHostname does not respect CN).

Accept client certs based on SAN, not just CN

---

deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/templates/master.yaml
deployment/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

Add `extraLabelNs` master flag in the Helm chart.
I did a patch update on the chart version but maybe it should be a minor update?

helm: add extraLabelNs master flag

---

cmd/nfd-master/main.go
deployment/node-feature-discovery/templates/master.yaml
docs/advanced/developer-guide.md
docs/advanced/master-commandline-reference.md
docs/get-started/deployment-and-usage.md
nfd-master.yaml.template
pkg/nfd-master/nfd-master.go

* first attempt at SAN-based VerifyNodeName
* Update docs on verify-node-name
(cherry picked from commit 77bd4e4cf6035cc39b191203a341093fafeabe8b)

backport-0.8: Accept client certs based on SAN, not just CN (#514)

---

deployment/node-feature-discovery/templates/worker.yaml
nfd-daemonset-combined.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
source/config.go
source/internal/kernelutils/kernel_kconfig.go
test/e2e/node_feature_discovery.go

Mount /usr as /host-usr inside the pod to allow NFD to find the kernel
configuration file inside /usr.
This solves the problem of the kernel config file not being present in /boot
on s390x RHCOS.
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

Mount /usr inside the Pod

---

docs/advanced/worker-configuration-reference.md
docs/get-started/features.md
source/custom/rules/usb_id_rule.go
source/internal/usb_utils.go

In my homelab, I have different FTDI serial converters connected to several utility meters. They all have identical vendor/device, but different serials.
In order to detect a specific FTDI unit (eg.  the one connected to my electricity meter), I'd like feature labels triggered by a specific USB serial.
This PR takes care of this. What's covered:
- logic to implement custom rules based on USB device
- exposure of the USB serial into `feature.node.kubernetes.io/usb-<...>.present=true`
- documentation update
- not use the serial by default in labels (ie, previous default behaviour was unchanged)
I've tested using following config:
```yaml
sources:
custom:
- name: "ftdi.A"
matchOn:
- usbId:
vendor: ["0403"]
device: ["6001"]
serial: ["A600aAMH"]
- name: "ftdi.B"
matchOn:
- usbId:
vendor: …
```

Add support for using USB device serial number

---

docs/_config.yml
docs/_includes/class/sidebar-wrap.liquid

Change the sidebar customization so that the full version (e.g. v0.8.2)
is displayed, instead of the truncated "releae branch version" (e.g.
v0.8) in the top left corner of the page. The items in the version menu
are unchanged and will still show the shorter form.
My plan is to backport this to all release branches.

docs: show full version number in sidebar

---

docs/_config.yml
docs/_includes/class/sidebar-wrap.liquid

Change the sidebar customization so that the full version (e.g. v0.8.2)
is displayed, instead of the truncated "releae branch version" (e.g.
v0.8) in the top left corner of the page. The items in the version menu
are unchanged and will still show the shorter form.
(cherry picked from commit 4d19e1ab85b6cf4c6a2f6e556bf04654e4fb238e)

backport-0.8: docs: show full version number in sidebar

---

docs/_config.yml
docs/_includes/class/sidebar-wrap.liquid

Change the sidebar customization so that the full version (e.g. v0.8.2)
is displayed, instead of the truncated "releae branch version" (e.g.
v0.8) in the top left corner of the page. The items in the version menu
are unchanged and will still show the shorter form.
(cherry picked from commit 4d19e1ab85b6cf4c6a2f6e556bf04654e4fb238e)

backport-0.7: docs: show full version number in sidebar

---

docs/_config.yml
docs/_includes/class/sidebar-wrap.liquid
scripts/test-infra/mdlint.sh

- Change the sidebar customization so that the full version (e.g. v0.8.2)
is displayed, instead of the truncated "releae branch version" (e.g.
v0.8) in the top left corner of the page. The items in the version menu
are unchanged and will still show the shorter form.
(cherry picked from commit 4d19e1ab85b6cf4c6a2f6e556bf04654e4fb238e)
- docs: add 'release' parameter in config.yml

backport-0.6: docs: show full version number in sidebar

---

pkg/utils/dump.go

utils/dump: do not print empty header line

---

source/cpu/cpu.go
source/custom/custom.go
source/fake/fake.go
source/iommu/iommu.go
source/kernel/kernel.go
source/local/local.go
source/memory/memory.go
source/network/network.go
source/pci/pci.go
source/storage/storage.go
source/system/system.go
source/usb/usb.go

Paves the way for future work on more general representation of
feature data and looser coupling of the data and feature source
interface.

source: define source names as consts

---

deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/values.yaml
nfd-master.yaml.template
nfd-prune.yaml.template

This updates the tolerations and affinities to also respect the term „control-plane“ which will eventually replace „master“

chore: update tolerations and affinities to control-plane

---

go.mod
go.sum

The new version adds AVX512-FP16 (half precision floating-point)
support available on Sapphire Rapids.

go.mod: update to klauspost/cpuid/v2@v2.0.9

---

docs/advanced/master-commandline-reference.md
docs/get-started/features.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Allow <sub-ns>.feature.node.kubernetes.io label namespaces. Makes it
possible to have e.g. vendor specific label ns without the need to user
-extra-label-ns.
Fixes #477

nfd-master: allow sub-namespaces of the default label ns

---

source/cpu/cpu.go
source/cpu/cstate.go
source/cpu/pstate.go
source/kernel/selinux.go

- source/cpu: better error reporting
Drop confusing errors in the log when intel pstate or cstate driver is
not enabled in the system. However, we still log an error if sysfs is
not available at all, in which case we're not able to detect these
correctly.
- source/kernel: better error reporting
Get rid of distracting error in the log in case selinux is not enabled
in the kernel. Still print an error only if sysfs/fs directory is not
available, though, which indicates that we're not able to correctly
detect the presence of selinux.
Fixes #527

Better error reporting of kernel and cpu feature sources

---

Dockerfile
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
pkg/nfd-master/nfd-master.go

Fixes #522 
This patch seeks to:
- https://github.com/kubernetes-sigs/node-feature-discovery/commit/273cfffe62936300f575bca72205bff0cc8bae3d enable readinessprobe for nfd-master
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/563/commits/f4e8e20ea5c963c0cb4610f702abf0ed889b90a9 add livenessprobe for nfd-master

Add Readiness and liveliness probes to nfd-master

---

deployment/base/master-worker-combined/master-worker-daemonset.yaml

Got broken unnoticed with the addition of liveness and readiness probes.

kustomize: fix broken master-worker-combined base

---

cmd/nfd-worker/main.go
pkg/nfd-client/base.go
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go
pkg/nfd-client/worker/nfd-worker_test.go

Refactor the worker code and split out gRPC client connection handling
into a separate base type. The intent is to promote re-usability of code
for other NFD clients, too.

nfd-worker: split out gRPC connection handling

---

.gitignore

Want to ignore kustomization.yaml which is auto-generated by the make
yamls target.

gitignore: add kustomization.yaml

---

docs/get-started/deployment-and-usage.md

Fixed typo in https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/get-started/deployment-and-usage.md
Fixes #567

Fix the typo in deployment-and-usage.md

---

docs/advanced/worker-configuration-reference.md

needs to be backported to v0.9.0 

Fix broken link for worker-conf example

---

source/network/network.go

However, log an error if something unexpected happens, i.e. the file to
read maximum number of vfs exists (sriov_totalvfs) but read fails.

source/network: silence annoying/useless log message

---

Makefile
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go
source/cpu/cpu.go
source/custom/custom.go
source/fake/fake.go
source/iommu/iommu.go
source/kernel/kernel.go
source/local/local.go
source/memory/memory.go
source/mock_LabelSource.go
source/network/network.go
source/pci/pci.go
source/source.go
source/source_test.go
source/storage/storage.go
source/system/system.go
source/usb/usb.go

Implement new registration infrastructure under the "source" package.
This change loosens the coupling between label sources and the
nfd-worker, making it easier to refactor and move the code around.
Also, create a separate interface (ConfigurableSource) for configurable
feature sources in order to eliminate boilerplate code.
Add safety checks to the sources that they actually implement the
interfaces they should.
In sake of consistency and predictability (of behavior) change all
methods of the sources to use pointer receivers.
Add simple unit tests for the new functionality and include source/...
into make test target.
Second piece towards getting #464 merged.

source: make sources register themselves

---

pkg/api/feature/feature.go
pkg/api/feature/types.go
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go
source/cpu/cpu.go
source/custom/custom.go
source/fake/fake.go
source/iommu/iommu.go
source/kernel/kernel.go
source/local/local.go
source/memory/memory.go
source/mock_LabelSource.go
source/network/network.go
source/pci/pci.go
source/source.go
source/source_test.go
source/storage/storage.go
source/system/system.go
source/usb/usb.go

Specify a new interface for managing "raw" feature data. This is the
first step to separate raw feature data from node labels. None of the
feature sources implement this interface, yet.
This patch unifies the data format of "raw" features by dividing them
into three different basic types.
- `keys`, a set of names without any associated values, e.g. CPUID flags
or loaded kernel modules
- `values`, a map of key-value pairs, for features with a single value,
e.g. kernel config flags or os version
- `instances`, a list of instances each of which has multiple attributes
(key-value pairs of their own), e.g. PCI or USB devices
The new feature data types are defined in a new "pkg/api/feature"
package, catering decoupling and re-usability of code e.g. within future
extentions of the NFD gRPC API. …

source: introduce FeatureSource interface

---

source/system/system.go

Currently when parsing /etc/os-release, NFD assumes all all values are surrounded by double quotes `"`. 
In some OS's, such as RHCOS, the OSTREE_VERSION is surrounded by single quotes. 
```NAME="Red Hat Enterprise Linux CoreOS"
VERSION="48.84.202107271439-0"
ID="rhcos"
...
OPENSHIFT_VERSION="4.8"
RHEL_VERSION="8.4"
OSTREE_VERSION='48.84.202107271439-0'
```

Trim single quotes in parseOSRelease

---

docs/advanced/architecture.md
docs/advanced/customization-guide.md
docs/advanced/developer-guide.md
docs/advanced/e2e-configuration-reference.md
docs/advanced/master-commandline-reference.md
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/introduction.md
docs/mdl-style.rb

Make table of contents in the pages cleaner and more readable by
dropping the main heading (H1 level) from TOCs. This was the original
intention with the usage of "no_toc" kramdown magic, which was broken,
however. The kramdown class magic needs to be specified on the line
immediately following the headinds, otherwise it has no effect. We need
to disable MD022 rule of mdlint as it does not understand this magic.

docs: fix TOCs

---

deployment/overlays/topologyupdater/kustomization.yaml

Align "topologyupdater" overlay with "topologyupdater-job". Both should
deploy topologyupdater as a standalone application. Previously the
topologyupdater overlay did not deploy nfd-master at all (but deployed
nfd-worker instead) causing the pods to end up in crashloopbackoff as
there was no master to communicate with.

deployment: align topologyupdater overlays

---

pkg/resourcemonitor/noderesourcesaggregator.go
pkg/resourcemonitor/noderesourcesaggregator_test.go
pkg/resourcemonitor/podresourcesscanner.go
pkg/resourcemonitor/podresourcesscanner_test.go
pkg/resourcemonitor/types.go
pkg/utils/memory_resources.go
pkg/utils/memory_resources_test.go

With the moving of the memory manager to beta, we have an option to expose relevant memory and hugepages information under the `NodeResourceTopology` CR.

resourcemonitor: aggregate and provide the memory and hugepages information

---

pkg/api/feature/feature.go
pkg/api/feature/types.go

Slight improvements on the internal pkg/api/feature api.
- use pointers of structs:
Make it easier to mutate the feature sets.
- generator functions with initial values:
Flavor the generator helper functions with arguments for specifying the
set of features to put into the generated objects.

pkg/api/feature: small improvements

---

test/e2e/node_feature_discovery.go

Lift the restriction to run custom rule tests on non-master node. Try to
find one but do not fail if that fails. Makes the end-to-end tests
runnable on single-node clusters such a simple minikube deployments.

test/e2e: make e2e tests run on single-node cluster

---

test/e2e/node_feature_discovery.go

This is not currently needed by end-to-end tests. Dropping it enables
testing in restricted environments that don't have /boot directory.

test/e2e: drop /boot mount

---

deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

fixes https://github.com/kubernetes-sigs/node-feature-discovery/pull/627#issuecomment-948316754
1. `"node-feature-discovery.fullname"` is used to prefix the worker ConfigMap name
2. `worker.configmapName` Helm parameter is dropped
3. This change is documented.
**Comments**:
Since the template filename is still `nfd-worker-conf.yaml`, it makes sense to have the name suffix `-worker-conf`.
Generally, we should consider renaming the template file, to e.g. `configmap.yaml`, and drop that resource name suffix. This would make that ConfigMap resource the single source of information for any (future) nfd pod configuration (worker, master, etc.). Should I proceed with this here?

deployment: Implicitly generate the worker ConfigMap name

---

deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
source/custom/custom.go
source/custom/custom_test.go
source/custom/directory_features.go
source/custom/expression/expression.go
source/custom/static_features.go

The main goal of this PR is to greatly expand the capabilities of the custom source, and, to make easier to extend in the future. After this change basically all features from the `cpu`, `kernel`, `system` `pci`, `usb` and `local` source are available for custom rule processing. This is achieved in three steps
1. Decouple "raw" feature discovery and label generation in the feature sources
1. Introduce a generalized and more expressive rule processing infrastructure, inspired by the MatchExpressions pattern in K8s nodeSelector (also, convert all existing rules to utilize this)
1. Implement a generic per domain/feature custom rule for matching all features from sources that support "raw" feature discovery (i.e. `cpu`, `kernel`, `system` `pci`, `usb` and `local` in this PR)
This PR …

More extensive and expressive custom rules

---

pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go
source/custom/custom.go

Move the rule processing of matchFeatures and matchAny from
source/custom package over to pkg/apis/nfd, aiming to better integrity
and re-usability of the code. Does not change the API as such, just adds
more supportive functions.
Depends/builds on #653

source/custom: move rule matching to pkg/apis/nfd

---

deployment/base/nfd-crds/nodefeaturerule-crd.yaml
deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
pkg/apis/nfd/v1alpha1/types.go

Drop stale leftover "LabelsTemplate" field from the rule spec.

pkg/apis/nfd: drop excess field from the CRD

---

deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/components/topology-updater/kustomization.yaml
deployment/components/topology-updater/sleep-interval-flag.yaml
deployment/components/topology-updater/topologyupdater-mounts.yaml

The base should really have the very bare minimum. Remove all redundant
(at default-value) args and move the others to the specific
topologyupdater kustomize component. This also makes these settings
re-usable in user-specific overlays (that are not based on
topologyupdater-daemonset).

deployment: clean up base/topologyupdater-daemonset

---

deployment/base/nfd-crds/cr-sample.yaml
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
source/storage/storage.go
source/storage/storage_test.go

Separate feature discovery and creation of feature labels. Generalize
the feature discovery so that block devices can be matched in custom
label rules in a similar fashion as pci and usb devices. This extends
the discovery to other block queue attributes than 'rotational': now we
also detect 'dax', 'nr_zones' and 'zoned'.
Labels created by the storage feature source are unchanged. The new
features being detected are available in custom rules only.
Example custom rules:
```
- name: "my block rule 1"
labels:
my-block-feature-1: "true"
matchFeatures:
- feature: storage.block
"rotational": {op: In, value: ["0"]}
- name: "my block rule 2"
labels:
my-block-feature-2: "true"
matchFeatures:
- feature: storage.block
"zoned": {op: In, value: [“host-aware”, “host-managed”]}
```
Also, add minimalist …

source/storage: implement FeatureSource

---

test/e2e/node_feature_discovery.go

This reverts commit 261ab113bffa44c2f3eea60c5533a70b156d3873.
This broke our e2e tests. We need to make this configurable.

Revert "test/e2e: drop /boot mount"

---

pkg/nfd-master/nfd-master.go

Enable Custom Resource based label creation in nfd-master. This extends
the previously implemented controller stub for watching NodeFeatureRule
objects. NFD-master watches NodeFeatureRule objects in the cluster and
processes the rules on every incoming labeling request from workers.
The functionality relies on the "raw features" (identical to how
nfd-worker handles custom rules) submitted by nfd-worker, making it
independent of the label source configuration of the worker. This means
that the labeling functions as expected even if all sources in the
worker are disabled.
NOTE: nfd-master is stateless and re-labeling only happens on the
reception of SetLabelsRequest from the worker – i.e. on intervals
specified by the core.sleepInterval configuration option (or
-sleep-interval cmdline flag) …

CRD-based custom node labeling

---

deployment/base/nfd-crds/cr-sample.yaml
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
source/network/network.go
source/network/network_test.go

Separate feature discovery and creation of feature labels. Generalize
the feature discovery so that network devices can be matched in custom
label rules in a similar fashion as pci and usb devices. Available
attributes for matching are:
- operstate
- speed
- sriov_numvfs
- sriov_totalvfs
Labels created by the network feature source are unchanged. The new
features being detected are available in custom rules only.
Example custom rule:
```
- name: "my network rule"
labels:
my-network-feature: "true"
matchFeatures:
- feature: network.device
matchExpressions:
"operstate": { op: In, value: ["up"] }
"sriov_numvfs": { op: Gt, value: ["9"] }
```
Also, add minimalist unit test.

source/network: implement FeatureSource

---

deployment/base/nfd-crds/cr-sample.yaml
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
source/memory/memory.go
source/memory/memory_test.go

Separate feature discovery and creation of feature labels.
Generalize the discovery of nvdimm devices so that they can be matched
in custom label rules in a similar fashion as pci and usb devices.
Available attributes for matching nvdimm devices are limited to:
- devtype
- mode
For numa we now detect the number of numa nodes which can be matched
agains in custom label rules.
Labels created by the memory feature source are unchanged. The new
features being detected are available in custom rules only.
Example custom rule:
```
- name: "my memory rule"
labels:
my-memory-feature: "true"
matchFeatures:
- feature: memory.numa
matchExpressions:
"node_count": {op: Gt, value: ["3"]}
- feature: memory.nv
matchExpressions:
"devtype" {op: In, value: ["nd_dax"]}
```
Also, add minimalist unit test.

source/memory: implement FeatureSource

---

docs/get-started/features.md
source/cpu/cpu.go
source/cpu/sgx_amd64.go
source/cpu/sgx_stub.go

source/cpu: detect Intel SGX

---

source/kernel/kernel.go

Commit 094501916155c183775e4e941d55a4d9ca5f38a0 changed the behavior so
that NFD started to advertise also "false" status of selinux.enabled
label. This patch reverts this behavior (i.e. we only have
selinux.enabled=true). The rationale behind is avoiding any excess
labels - selinux.enabled=false label would be pointless noise in most
deployments.

source/kernel: don't advertise selinux.enabled=false

---

pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go

Require that the expanded LabelsTemplate has values. That is, the
(expanded) template must consist of key=value pairs separated by
newlines. No default value will be assigned and we now return an error
if a (non-empty) line not conforming with the key=value format is
encountered.
Commit c8d73666d described that the value defaults to "true" if not
specified. That was not the case and we defaulted to an empty string,
instead.
An example:
```
- name: "my rule"
labelsTemplate: |
my.label.1=foo
my.label.2=
```
Would create these labels:
```
"my.label.1": "foo"
"my.label.2": ""
```
Further, the following:
```
- name: "my failing rule"
labelsTemplate: |
my.label.3
```
will cause an error in the rule processing.

pkg/apis/nfd: stricter format checking for template labels

---

deployment/base/nfd-crds/cr-sample.yaml
deployment/base/nfd-crds/nodefeaturerule-crd.yaml
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
deployment/helm/node-feature-discovery/values.yaml
pkg/api/feature/feature.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go
pkg/apis/nfd/v1alpha1/types.go
pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
pkg/nfd-master/nfd-master.go
source/custom/custom.go

Support backreferencing of output values from previous rules. Enables
complex rule setups where custom features are further combined together
to form even more sophisticated higher level labels. The labels created
by preceding rules are available as a special 'rule.matched' feature
(for matchFeatures to use).
If referencing rules accross multiple configs/CRDs care must be taken
with the ordering. Processing order of rules in nfd-worker:
1. Static rules
2. Files from /etc/kubernetes/node-feature-discovery/custom.d/
in alphabetical order. Subdirectories are processed by reading their
files in alphabetical order.
3. Custom rules from main nfd-worker.conf
In nfd-master, NodeFeatureRule objects are processed in alphabetical
order (based on their metadata.name).
This patch also adds new 'vars' …

Add variables to feature rule spec and support backrefs 

---

source/cpu/cpuid_s390x.go
source/cpu/power_stub.go

Add the newly supported s390x CPU Flags for the 5.15 Kernel
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
I also fixed one compiler Issue for non amd64 architectures.

source/cpu: add additional IBM Z CPU Flags

---

Makefile

After https://github.com/kubernetes-sigs/node-feature-discovery/pull/667
adding a rule for also deploying NFD is encouraged.

Makefile: Add make deploy rule

---

docs/advanced/developer-guide.md

These just keep getting out of sync and do not provide much value. Also,
we do have dedicated cmdline reference for all the executables.

docs: drop cmdline help from developer guide

---

cmd/nfd-topology-updater/main_test.go
cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
docs/advanced/worker-configuration-reference.md
docs/get-started/features.md
docs/get-started/introduction.md
pkg/nfd-client/base.go
pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
pkg/nfd-client/worker/nfd-worker.go
pkg/nfd-client/worker/nfd-worker_test.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/nfd-master_test.go

Use the single-dash (i.e. '-option' instead of '--option') format
consistently accross log messages and documentation. This is the format
that was mostly used, already, and shown by command line help of the
binaries, for example.

Use single-dash format of cmdline flags

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
docs/get-started/features.md
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go
pkg/nfd-client/worker/nfd-worker_test.go

Rename `core.sources` config file option to `core.labelSources` and `-sources` command line flag to `-label-sources`. Also provide backwards compatibility via deprecated options. Multiple smaller pieces as separate commits:
- rename config option `sources` to `labelSources`
The goal is to make the name more descriptive. Also keeping in mind a
possible future addition a 'featureSources' option (or similar) for
controlling the feature discovery.
- provide deprecated core.sources config option 
Provide backwards compatibility via a deprecated 'core.sources' config
file option. This will override 'core.labelSources'. A warning is
printed in the log if this option is detected.
- introduce -label-sources cmdline flag 
Useful for development, testing and debugging.
- update docs on label-sources …

nfd-worker: rename 'sources' config option

---

source/kernel/kconfig.go

Do not do length checking here. We do not need/want to limit the values
here because they could still be used in custom rules. Moreover, we do
more proper validation of label all label values in nfd-worker, anyway.

source/kernel: drop length check of kconfig values

---

source/custom/rules/kconfig_rule.go
source/kernel/kconfig.go
source/kernel/kernel.go

Stop converting `=y` and `=m` to `"true"` for the raw feature values used
in "kernel.config" custom rule processing.
In practice, this means that to check if a kernel config flag has been
set to "y" or "m", one needs to explicitly check for both of the values:
```
matchFeatures:
- feature: kernel.config
matchExpressions:
FOO: {op: In, value: ["y", "m"]}
```
instead of (how it used to be):
```
matchFeatures:
- feature: kernel.config
matchExpressions:
FOO: {op: IsTrue}
```
The legacy kconfig custom rule is unchanged as are the
kernel-config.<flag> feature labels.
Builds on top of #683

source/kernel: unmangled kconfig values for custom rules 

---

scripts/test-infra/test-e2e.sh

Rare timeouts (narrowly missing) with 10 minutes observed, try
increasing by 2 minutes.
Also fix printing of error message in case of a timeout.

scripts: increase e2e-test image poll timeout to 12mins

---

cmd/nfd-worker/main.go
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
pkg/nfd-client/worker/nfd-worker.go

Make it easier to disable single sources by prefixing the source name
with a dash ('-') in the core.sources config option (or -sources cmdline
flag).

nfd-worker: disable sources more easily

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go

- Add a configuration option for controlling the enabled "raw" feature
sources. This is useful e.g. in testing and development, plus it also
allows fully shutting down discovery of features that are not needed in
a deployment. Supplements core.labelSources which controls the
enablement of label sources.
-  add `-feature-sources` command line flag
Allows controlling (enable/disable) the "raw" feature detection.
Especially useful for development and testing.

nfd-worker: add core.featureSources config option

---

source/cpu/cpu_test.go
source/kernel/kernel_test.go
source/local/local_test.go
source/memory/memory_test.go
source/network/network_test.go
source/pci/pci_test.go
source/storage/storage_test.go
source/system/system_test.go
source/usb/usb_test.go

Now the tests check that GetLabels() works even without calling
Discover() at all.

source: make per-source unit tests stricter

---

pkg/nfd-client/worker/nfd-worker-internal_test.go
source/fake/fake.go

Makes it possible to create fake features for custom rules, enabling
testing.
Depends on #605

source/fake: implement FeatureSource

---

docs/get-started/features.md

Accidentally introduced in a57a25f63cb37c6e3aad45be52343c4b175a58f0.

docs: fix mistake in md format

---

test/e2e/node_feature_discovery.go

Use the "single-dash" notation of flags and replace deprecated -sources
with -label-sources.

test/e2e: revise usage of nfd command line flags

---

docs/get-started/features.md
source/local/local.go

Implicitly injecting the filename of the hook/featurefile into the name
of the label is usually confusing, counter-intuitive and unnecessarily
complex to understand. It's much clearer to advertise features and
labels as presented in the feature file / output of the hook.
NOTE: this breaks backwards compatibility with usage scenarios that rely
on prefixing the label with the filename.

source/local: don't prefix label names with the filename

---

pkg/nfd-client/worker/nfd-worker.go
source/custom/custom.go

Do not prefix label names from the new matchFeatures/matchAny custom
rules with "custom-". We want to have the same result (set of labels)
from a rule independent of whether it has been specified in worker
config or in a NodeFeatureRule CRs. Legacy matchOn rules (not available
in NodeFeatureRule CRs) are intact, i.e. still prefixed, in order to
retain backwards compatibility.

nfd-worker: drop 'custom-' prefix from matchFeatures custom rules

---

Dockerfile

Current grpc-health-probe functionality is pulling a binary, hard coded
to amd64, both unsecure and only works for 1 arch, preparing to build
NFD for multiple Arch's require we build the health probe from source,
that way we get rid of the unsecure binary pull, and guarantee a proper
arch build for the grpc-health-probe

Dockerfile: build grpc_health-probe from source

---

Dockerfile

Rename grpc-health-probe -> grpc_health_probe as
deployment yamls refer to it by this name.
This should fix broken NFD deployments.

Fix readiness and liveness checks

---

deployment/overlays/samples/cert-manager/issuer.yaml
deployment/overlays/samples/cert-manager/kustomization.yaml
deployment/overlays/samples/cert-manager/master-cert.yaml
deployment/overlays/samples/cert-manager/probes.yaml
docs/get-started/deployment-and-usage.md

A few changes in this PR:
1/ Make use of cert-manager's selfSigned{} to bootstrap the actual CA creation (removes the need for a manual openssl step)
2/ Update grpc_health_check to use TLS (without this, the master pod won't start)
3/ Update the certs to include "localhost" in the SAN list, so grpc_health_check can work
4/ Update docs (and bump cert-manager referenced to 1.6.1)
Note - this is partly in response to #563

Fix kustomization template to work with cert-manager

---

deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

See also #710 -- this is a similar change to the helm chart:
1/ Enable TLS for worker/master communications
2/ Optionally use cert-manager to bootstrap CA, and then create secrets
3/ Update grpc_health_check call to use the TLS certs if enabled

Enable TLS and cert-manager created certs for helm chart

---

deployment/helm/node-feature-discovery/templates/_helpers.tpl
deployment/helm/node-feature-discovery/templates/clusterrole.yaml
deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

Move top-level serviceAccount and rbac fields under master, making the
Helm chart more coherent.
Also, drop unused rbac.serviceAccountName and
rbac.serviceAccountAnnotations from values.yaml.
Add `-master` suffix to the nfd-master ClusterRole and
ClusterRoleBinding, and, to default name of the ServiceAccount. This
makes the naming consistent with the topology-updater and pave way for
the possibility of adding a separate worker-specific RBAC configuration.
Fixes #630

deployment/helm: refactor nfd-master rbac parameters

---

docs/get-started/features.md
docs/get-started/introduction.md
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go
source/fake/fake.go
source/iommu/iommu.go
source/source.go

Deprecate the iommu source and disable it by default.
First step of #676

source/iommu: deprecate and disable by default 

---

docs/_config.yml
docs/advanced/customization-guide.md
docs/get-started/features.md
examples/nodefeaturerule.yaml

Add a separate customization guide. Move documentation of the custom and
local sources there. Also, cover the new NodeFeatureRules custom
resource and the new expression-based label rule format.
This patch also simplifies the "Feature labels" page, describing
built-in labels. Reformat the tables describing feature labels.

docs: add customization guide

---

docs/get-started/deployment-and-usage.md

Add cross-referencing links to the helm deployment and configuration
sections. Use correct names for the tls related helm options
(tls.enabled and tls.certManager).

docs: small tinkering on the TLS documentation

---

docs/advanced/customization-guide.md
source/pci/utils.go

Add `iommu_group/type` to the list of PCI device attributes that are
discovered. The value is the raw value from sysfs (i.e DMA, DMA-FQ or
identity).
No built-in (automatic) labels are generated based on this, but, the
attribute is available for custom label rules to use. Examples of custom
rules:
```
- name: "iommu enabled rule"
labels:
iommu.enabled: "true"
matchFeatures:
- feature: pci.device
matchExpressions:
"iommu_group/type": {op: NotIn, value: ["unknown"]}
```
```
- name: "iommu passthrough rule"
labels:
iommu.passthrough: "true"
matchFeatures:
- feature: pci.device
matchExpressions:
"iommu_group/type": {op: In, value: ["identity"]}
```

source/pci: add iommu_group/type attribute

---

docs/advanced/customization-guide.md

In the list of available features, list 'name' separately as it's not
from a sysfs file like the other attributes.

docs: small fix in block and net features in customization guide

---

scripts/github/update-gh-pages.sh

Fix the sorting magic of release directories. Correctly sort according
to the version number.

scripts/update-gh-pages: fix symlink to stable version

---

cloudbuild.yaml

As per
https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md
we need that for buildx.

cloudbuild.yaml: set HOME to /root

---

cloudbuild.yaml

We hit the timeout with default 600s with multiarch builds enabled.

cloudbuild.yaml: double the timeout

---

cloudbuild.yaml

20 minutes was not clearly enough for multiarch buildx build.

cloudbuild.yaml: increase timeout to 2400s

---

cloudbuild.yaml
scripts/test-infra/test-e2e.sh

Even 40 minutes failed us for multi-arch builds.
Also, increase the e2e-test image polling timeout correspondingly.

cloudbuild.yaml: increase timeout to 1 hour

---

pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
pkg/nfd-client/worker/nfd-worker_test.go

This patch increases the timeout when setting up the NFD master
to 5 seconds instead of 1 second to allow for running tests in
slow environments.
Closes: #737

Increase timeout in test setups

---

scripts/test-infra/push-image.sh

Re-introduce docker authentication that was dropped in
bac690813ae5416387c9a4ace2ab4b65b040f4ee. Should fix issues with
building multi-arch buildx buildx.

scripts: configure docker auth in push-image.sh

---

Makefile
cloudbuild.yaml
docs/advanced/developer-guide.md
docs/get-started/deployment-and-usage.md
hack/init-buildx.sh
pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
pkg/nfd-client/worker/nfd-worker_test.go
pkg/nfd-master/nfd-master.go
scripts/test-infra/build-image-cross.sh
scripts/test-infra/build-image.sh
scripts/test-infra/push-image.sh
scripts/test-infra/test-e2e.sh

Enables multi arch (amd64 and arm64) builds on the `release-0.10` branch. Done by cherry-picking required commits from `master`.

release-0.10: enable multi arch builds

---

docs/advanced/developer-guide.md

Similar to what we did for nfd-master and nfd-worker in
0d21b3d7200272157438b76a62f7aad1361fe31e.

docs: drop topology-updater cmdline help from developer guide

---

scripts/prepare-release.sh

Fix the sed script to update the version of kustomize overlay.
Also, add a sed script to update the documentation link to point to the
correct version in gh-pages.

scripts/prepare-release: fix upating of readme

---

docs/get-started/deployment-and-usage.md

Back to how it was - the 'stable' channel went away in the latest NFD
update on community-opetors (operatorhub.io).

docs: re-fix operator deployment instructions

---

docs/advanced/worker-configuration-reference.md

Also, update the reference linking to the documentation of the custom
source to point to the customization guide.

docs: use new custom rule format in worker config reference

---

scripts/test-infra/verify.sh

This reverts commit 24425ed16f2162eb6d4ff9149de5b7e7f76577f0.
Tests if https://github.com/kubernetes/test-infra/pull/25023 works as expected

[release-0.9] Revert "scripts: disable gofmt check in ci"

---

docs/advanced/developer-guide.md

Change the default K8S_NAMESPACE to nfd-feature-discovery from
kube-system. The default was changed in the Makefile in commit
5d4484a1d983927c8e40bc932190d6e8f012aa19, but the docs were not updated
to correspond with that.

docs: Update default K8S_NAMESPACE

---

pkg/nfd-client/base.go
pkg/utils/tls.go

Deny deprecated TLS versions (1.0 and 1.1). We don't really excpect
other clients than NFD itself so we can just request the latest version.
Fixes #780

tls: require min TLS version 1.3

---

deployment/helm/node-feature-discovery/templates/_helpers.tpl
deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml

This PR creates a separate ServiceAccount for the nfd-worker like the other components.
Even though the nfd-worker doesn't need any special RBAC permissions, this feature is useful for nvidia/gpu-operator which supports PodSecurityPolicies. But since nfd-worker doesn't have its own ServiceAccount, they've bolted on this feature into their fork, which is giving them issues: https://github.com/NVIDIA/gpu-operator/issues/314 https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/414#note_854845708
PodSecurityPolicies are used to grant special permission to nfd-worker to create hostPath volumes.

Add ServiceAccount for nfd-worker

---

pkg/apihelper/k8shelpers.go
pkg/apis/nfd/v1alpha1/rule_test.go
pkg/nfd-client/base.go
pkg/nfd-client/topology-updater/nfd-topology-updater.go
pkg/nfd-master/nfd-master.go
pkg/resourcemonitor/podresourcesscanner.go
pkg/resourcemonitor/types.go
source/cpu/cpu.go
source/cpu/cstate_amd64.go
source/cpu/power_amd64.go
source/custom/rules/kconfig_rule.go
source/custom/rules/nodename_rule.go
source/fake/fake.go
source/local/local.go
source/memory/memory.go
source/pci/pci.go

This is continuation of Issue #566 
More lint fixes have been done and some spelling mistakes have been fixed.

Additional Lint Fixes in Codebase

---

docs/advanced/customization-guide.md

The PR fixes some references that present in the [customization guide](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html) in Advanced Section

Fixed the incorrect references 

---

pkg/resourcemonitor/noderesourcesaggregator.go

It's possible for device plugins to advertise non-existent
numa node ids that cause topology updater to crash.
Signed-off-by: Tuomas Katila <tuomas.katila@intel.com>

topologyupdater: Prevent crash with incorrect node id

---

docs/advanced/customization-guide.md
pkg/apis/nfd/v1alpha1/expression.go
pkg/apis/nfd/v1alpha1/expression_test.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go

This patch changes a rare corner case of custom label rules with an
empty set of matchexpressions. The patch removes a special case where an
empty match expression set matched everything and returned all feature
elements for templates to consume. With this patch the match expression
set logically evaluates all expressions in the set and returns all
matches - if there are no expressions there are no matches and no
matched features are returned. However, the overall match result
(determining if "non-template" labels will be created) in this special
case will be "true" as before as none of the zero match expressions
failed.
The former behavior was somewhat illogical and counterintuitive: having
1 to N expressions matched and returned 1 to N features (at most), but,
having 0 expressions …

apis/nfd: empty match expression set returns no features for templates

---

docs/advanced/customization-guide.md
docs/get-started/features.md
source/cpu/cpu.go

First pass on enhancing the discovered model of the CPU
example:
```bash
feature.node.kubernetes.io/cpu-model.ID=113
feature.node.kubernetes.io/cpu-model.family=23
feature.node.kubernetes.io/cpu-model.vendorID=AMD
```

Add cpu-model feature detection

---

docs/advanced/customization-guide.md
docs/get-started/features.md
source/cpu/cpu.go
source/cpu/se_s390x.go
source/cpu/se_stub.go

Set `cpu.se-enabled` to `true` when IBM Secure Execution for Linux (IBM Z & LinuxONE) is available and has been enabled.
Uses `/sys/firmware/uv/prot_virt_host`, which is available in kernels >=5.12 + backports. For simplicity, skip more complicated facility & kernel cmdline lookups.

cpu: Discover IBM Secure Execution

---

docs/advanced/developer-guide.md

Let the documentation follow the latest release name. Even if it's just
referential here it would look odd in the future if we refer to some
ancient version.

docs: remove fixed release tag in developer guide

---

scripts/github/update-gh-pages.sh

Align the version number inserted in the commit message with what we use
in the Makefile.

scripts/update-gh-pages: adjust commit message body

---

cmd/nfd-worker/main.go
scripts/test-infra/verify.sh

Adds support for golang v1.18.

scripts/test-infra: bump golangci-lint to v1.45.2

---

Dockerfile
go.mod
go.sum

Bump Go to 1.18

---

source/network/network.go

Ignore the operational state of network interface when creating the
network SR-IOV labels. Previously NFD only considered interfaces which
were "up".
Pre v0.9 we used to check the "administrative state" of interfaces
(managed by the sysadmin with e.g. with ip link set dev <dev> down/up).
In v0.10 we changed to checking the "operational state" of interfaces,
reflecting whether the it is actually able to transfer data. Both these
checks have caused confusion among users and it is more understandable
and more aligned with other HW discovery functions in NFD to just drop
the state check. Also, the documentation is aligned with this behavior.
Fixes #812

source/network: ignore interface operational state

---

docs/get-started/features.md

Update the partial list of x86 cpuid features that are presented in the
NFD documentation. In particular, the following instructions were left
out of the list: AVXSLOW, CETIBT, CETSS, CLDEMOTE, HLE, MPX, RTM,
RTM_ALWAYS_ABORT, SERIALIZE, SHA, TSXLDTRK.

docs: update x86 cpuid feature list

---

scripts/test-infra/test-e2e.sh

We need the latest version to support client.authentication.k8s.io/v1.
The previous version we used only supported v1alpha1 which was dropped
in K8s v1.24.

scripts/test-e2e: update aws-iam-authenticator to v0.5.7

---

test/e2e/e2e-test-config.example.yaml
test/e2e/node_feature_discovery.go

Change the part of the e2e-test configuration that contains
node-specific expected labels and annotations to a list, instead of a
map. This makes the parsing order deterministic and makes it possible to
e.g. have a default at the end of the list that captures "all the rest".

test/e2e: change node-specific config to a list

---

deployment/helm/node-feature-discovery/templates/_helpers.tpl
deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
deployment/helm/node-feature-discovery/templates/service.yaml
deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml

when use this helm chart as other charts' dependency([Helm Dependency](https://helm.sh/docs/helm/helm_dependency/)), helm will install manifests of this chart to parent chart's  namespace, because .Release.Namespace is parent chart's namespace. so, if we want this chart installed to a separated namespace, community of helm project recommend add namespaceOverride (https://github.com/helm/charts/pull/15202), and namespaceOverride is in helm template chart by default now.
many helm charts support namespaceOverride, such as [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/ae0085979db2de39611b60b1c9ddbcf35c3baa91/charts/kube-prometheus-stack/values.yaml#L11)

helm: add namespace override for multi-namespace deployments

---

Dockerfile
Makefile

Switch over to the "non-point-release" version of the image. Now we
always use the latest patch version of golang with latest security
fixes, for example, without the need to manually bump the version after
every point release.
This patch also makes the builder image configurable through a Makefile
variable.
For reproducible builds we should used fixed point-release versions in
release-brances.

dockerfile: update builder image to golang v1.18

---

docs/get-started/features.md
go.mod
go.sum

go.mod: update github.com/klauspost/cpuid to v2.1.0

---

test/e2e/node_feature_discovery.go
test/e2e/utils/config.go
test/e2e/utils/pod.go
test/e2e/utils/rbac.go
test/e2e/utils/service.go

This cleanup/refactoring will facilitate the addition of the nfd-topology-updater tests (https://github.com/kubernetes-sigs/node-feature-discovery/pull/528)

Move e2e-test helpers to a separate package

---

scripts/prepare-release.sh

Improve the release preparation script. The main motivation is to make the golang version fixed for release builds.
- option `-b` to not generate assets
Implement a new command line option `-b` to prevent the script from
creating release assets (Helm chart).
- option `-k` to specify the signing key
Make the GPG signing an optional argument. It doesn't make much sense to
require that when no assets are being generated (i.e. when `-b` is
used).
- patch golang version in Makefile
Make it mandatory to specify a golang version with `-g` when running the
script (and patching repo content). The given version will be patched
into the Makefile to fix the version used in the release build - it is
meant to use a exact point release (like 1.18.3) to get reproducible
builds.
Depends on #836

Improvements to scripts/prepare-release.sh

---

Makefile
docs/advanced/developer-guide.md
go.mod
test/e2e/e2e-test-config.example.yaml
test/e2e/topology_updater.go
test/e2e/utils/config.go
test/e2e/utils/kubeletconfig.go
test/e2e/utils/node.go
test/e2e/utils/noderesourcetopology.go
test/e2e/utils/pod.go
test/e2e/utils/rbac.go

Builds on top of https://github.com/kubernetes-sigs/node-feature-discovery/pull/525 and add e2e tests for the new component.
Some refactoring was performed along the way to make room for the new tests; no intended changes in the behaviour of the existing tests.
Design Document: [here](https://docs.google.com/document/d/1Q-4wSu1tzmbOXyGk_2r5_mK6JdXXJA-bOd3cAtBFnwo/edit?ts=5f24171f#)
Issue: https://github.com/kubernetes-sigs/node-feature-discovery/issues/333
Documentation: https://github.com/kubernetes-sigs/node-feature-discovery/pull/526

topology updater: add e2e tests

---

pkg/nfd-master/nfd-master.go

Use correct name for the CR (NodeFeatureRule) object. Also, the resource
is cluster-scoped so don't print the namespace.

nfd-master: more fixes to log messages

---

pkg/nfd-master/nfd-master.go
pkg/resourcemonitor/noderesourcesaggregator.go

It is not recognized (and does not work like with fmt.Errorf) so use %v
instead.

logging: do not use %w with klog.Errorf

---

pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go

When `MatchAny` is matched, template existence is checked with `r.labelsTemplate == nil`, and if it's nil - templating is skipped.
This is wrong because:
- there are `vars` templates too, not only `labels` templates
- `labelsTemplate` is initialized from `LabelsTemplate` when `executeLabelsTemplate` is called first time, so it would always be nil unless Rule has `MatchFeatures` in addition to `MatchAny`, and was executed already.
`LabelsTemplate` should be checked instead of `labelsTemplate` (same for vars) to see if there's template – but `executeLabelsTemplate` already does that.
So the check should be removed completely.
I've also added a test case which catches this issue.
Fixes #864.

Fix templates for NodeFeatureRule with MatchAny

---

scripts/test-infra/test-e2e.sh

Kubectl is required bu the topologu-updater end-to-end tests.

scripts/test-e2e: install kubectl

---

README.md

-  change prow badge to display status of image-build
Change the prow badge on top of the readme file to show the status of
image building (push-image job). We're not interested in the status of
the PR builds, merely on how the tip of the master branch (or occasional
releases) are doing.
- add a prow badge for e2e-test status

README: reconfigure prow badges

---

Makefile
scripts/test-infra/mdlint.sh

When working on a patch that touches docs/, there is no way to test changes against markdown checks before submitting a PR. In fact, we have a makefile target `mdlint` but it has a prerequisite of having mdl installed on the developer machine. What do you think of swapping the tasks of mdlint Makefile target with scripts/test-infra/mdlint.sh script with minor modifications so that developer can just run `make mdlint` which calls scripts/test-infra/mdlint.sh and the tests get executed within a container. Once execution is completed the temporary container gets removed so that we don't have garbage collected. I've chosen [ruby:slim](https://hub.docker.com/layers/library/ruby/slim/images/sha256-2e3b4a4628fead83109e77fa6732e430cf9881e2d8cb3fa6148935e87ea4ea70?context=explore) image (70.39 …

Run local markdown tests inside an isolated container

---

Tiltfile
docs/advanced/developer-guide.md

Currently the way we develop and test the code is
1. Code
2. Build the container image
3. Push the image to registry
4. Re-deploy manifests
This patch automates those steps via Tilt. It is an initial and simplified configuration and I expect to extend it in the future.
Fixes: https://github.com/kubernetes-sigs/node-feature-discovery/issues/879

Add Tilt option for developing NFD

---

.github/ISSUE_TEMPLATE/new-release.md
Makefile
Tiltfile
docs/advanced/developer-guide.md
docs/get-started/quick-start.md
scripts/prepare-release.sh
test/e2e/utils/pod.go

Kubernetes has moved to a new container image registry:
https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/FpHqeVR2BAAJ
See also:
https://github.com/kubernetes/kubernetes/pull/109938

Update registry to registry.k8s.io

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Remove the cleanup code that removes ancient NFD labels with the node.alpha.kubernetes-incubator.io/ prefix. This label namespace was deprecated/dropped already in v0.4.0 so it should be safe to drop this code.

nfd-master: drop cleanup of ancient incubator labels

---

deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/advanced/customization-guide.md
docs/advanced/worker-configuration-reference.md
source/local/local.go

Fixes: https://github.com/kubernetes-sigs/node-feature-discovery/issues/859

Config option to disable hooks

---

deployment/base/nfd-crds/nodefeaturerule-crd.yaml
deployment/helm/node-feature-discovery/crds/nodefeaturerule-crd.yaml
pkg/apis/nfd/v1alpha1/types.go

This patch adds a kubebuilder marker to add a short name `nfr` for
NodeFeatureRule CRD.

Set shortName for NodeFeatureRule CRD

---

docs/advanced/customization-guide.md
docs/get-started/features.md
source/cpu/security_amd64.go

Set `cpu.tdx-enable` to `true` when TDX is avialable and has been
enabled.
`/sys/module/kvm_intel/parameters/tdx` presence and content is used to
detect whether a CPU is Intel TDX capable.
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

cpu: Discover Intel TDX

---

pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go

Some renames in preparation for adding support for NFD CRD API client. I.e. a second client in addition to the existing gRPC client.
Split out from #903

nfd-worker: rename some symbols

---

pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master.go

Prepare for adding support for other nfd api objects. Just rename file and some symbols, no functional changes.
Split out from #903

nfd-master: rename crd controller

---

pkg/api/feature/feature.go
pkg/api/feature/generated.pb.go
pkg/api/feature/generated.proto
pkg/api/feature/types.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go
pkg/nfd-master/nfd-master.go
source/cpu/cpu.go
source/custom/custom.go
source/custom/rules/cpuid_rule.go
source/custom/rules/loaded_kmod_rule.go
source/custom/rules/nodename_rule.go
source/fake/fake.go
source/kernel/kernel.go
source/local/local.go
source/memory/memory.go
source/source_test.go
source/system/system.go

Sync type names with NFD documentation. Aims at making the codebase
easier to follow. No functional changes, just a rename.
Split out from #903

pkg/api/feature: rename types

---

pkg/nfd-client/worker/nfd-worker.go

Make the NoPublish config flag a more direct control point for whether to publishing features. This patch is pre-work for adding support for other clients (upcoming new CRD API) in nfd-worker.
Split out from #903

nfd-worker: refactor gRPC connection logic

---

pkg/nfd-master/nfd-master.go

Refactor the code so that the initialization and running of the gRPC server is done in a separate function. The goal is to make the code more maintainable in terms of disabling (and eventually removing) the gRPC functionality in the future.
Split out of #903

nfd-master: refactor gRPC into a separate method

---

Tiltfile

Tiltfile: update builder image to golang:1.19-bullseye

---

Makefile
Tiltfile

Update the base used for our "full" image to debian:bullseye-slim. Will ensure we get the latest and greatest updates and fixes.

Update base image to Debian bullseye

---

pkg/apis/nfd/v1alpha1/expression.go
pkg/apis/nfd/v1alpha1/rule_test.go
test/e2e/utils/pod.go

Error strings should not be capitalized [(ST1005)](https://staticcheck.io/docs/checks#ST1005) and remove
the redundancy from array, slice or map composite literals.

Error strings should not be capitalized

---

source/cpu/cpuid_arm.go
source/cpu/cpuid_arm64.go
source/cpu/cpuid_ppc64le.go
source/cpu/cpuid_s390x.go

Avoid trying to create empty "cpu-cpuid." labels for cpuid flags that we don't have a description for.

cpu: ignore unknown cpuid flags on non-x86

---

pkg/nfd-client/topology-updater/nfd-topology-updater.go

Scanning podresources can temporarily fail; the previous code was mistakenly not rearming the loop condition when this occurred, effectively stopping the monitoring.
Rather, we should always pool and bail out on unrecoverable error or when asked to stop.
Fixes: #922 
Signed-off-by: Francesco Romani <fromani@redhat.com>

topology-updater: continue looping on scan error

---

source/usb/utils.go

Scan the mounted host sysfs instead of hard coded /sys mount point. Currently, sysfs devices subdir is not namespaced in Linux (containers have the same view as the host) so this wasn't an issue in practice. However, this change should make the code more future proof and align usb with other sysfs detection in nfd.

source/usb: scan host sysfs

---

pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go

Fix handling of templates that got broken in
b907d07d7e0e7bd47f988b22c8b9a380f8abf75d when "flattening" the internal data structure of features. That happened because the golang text/template format uses dots to reference fields of a struct / elements of a map (i.e. 'foo.bar' means that 'bar' must be a sub-element of foo). Thus, using dots in our feature names (e.g. 'cpu.cpuid') means that that hierarchy must be reflected in the data structure that is fed to the templating engine. Thus, for templates we're now stuck stuck with two level hierarchy. It doesn't really matter for now as all our features follow that naming patter. We might be able to overcome this limitation e.g.  by using reflect but that's left as a future exercise.
Fixes #934

apis/nfd: fix NodeFeatureRule templating

---

cloudbuild.yaml

Image build is failing otherwise as per discussion on https://github.com/kubernetes-sigs/node-feature-discovery/pull/935#issuecomment-1292504879.
/cc @marquiz

Increase allowed image build timeout for 500s

---

scripts/test-infra/test-e2e.sh

We recently increased timeout in https://github.com/kubernetes-sigs/node-feature-discovery/pull/936  for image building and pushing
to GCR due to some failures with timeout. This commit extends timeout
for waiting that image to be published during E2E tests.
/cc @marquiz

Increase image waiting timeout

---

Makefile

Update the base used for our "full" image to debian:bullseye-slim. Will ensure we get the latest and greatest updates and fixes.
(cherry picked from commit a798b4517d4bb570a26f702698e0731cbbf083fd)

[release-0.11] Update base image to Debian bullseye

---

source/cpu/cpuid_arm.go
source/cpu/cpuid_arm64.go
source/cpu/cpuid_ppc64le.go
source/cpu/cpuid_s390x.go

Avoid trying to create empty "cpu-cpuid." labels for cpuid flags that we don't have a description for.
(cherry picked from commit 98fd07b1171e6cf68a629a507422c3a235fb6261)

[release-0.11] cpu: ignore unknown cpuid flags on non-x86

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

This commit adds an argument to updateNodeFeatures method for receiving
client argument, which currently gets initialized within the method itself. This
is a minor improvement originally for https://github.com/kubernetes-sigs/node-feature-discovery/pull/910.
Ref:https://github.com/kubernetes-sigs/node-feature-discovery/pull/910#discussion_r1012703631

Add argument to updateNodeFeatures method to pass client from caller

---

test/e2e/utils/pod.go

The -kubelet-config-file flag got renamed to -kubelet-config-uri and the expected format changed from plain filepath to URI.

test/e2e: fix topologu-updater cmdline args

---

test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go
test/e2e/utils/noderesourcetopology.go
test/e2e/utils/pod.go

A couple of commits which are addressing several issues in the tests.
We explained the rationale for every change in the commits themselves 
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

e2e: topologyupdater: fix and stabilize tests

---

test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go
test/e2e/utils/pod.go

Change the pod spec generator functions to accept parameterization in
the form of more generic "mutator functions". This makes the addition of
new test specific pod spec customizations a lot cleaner. Plus, hopefully
makes the code a bit more readable as well.
Also, slightly simplify the SpecWithConfigMap() but dropping one
redundant argument.
Inspired by latest contributions by Talor Itzhak (titzhak@redhat.com).

test/e2e: more flexible pod spec generation

---

test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go
test/e2e/utils/configmap.go

Implement a simple helper for creating a configmap with one key. One key (one config file) is enough for our current tests.

test/e2e: add helper for creating new configmaps

---

test/e2e/utils/pod.go

The master pod need these `SecurityContext` configurations In order to run inside a namespace with restricted policy
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

e2e: add SecurityContext to master

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
docs/reference/worker-commandline-reference.md
docs/reference/worker-configuration-reference.md
docs/usage/customization-guide.md
docs/usage/features.md
docs/usage/nfd-worker.md
pkg/nfd-client/worker/nfd-worker-internal_test.go
pkg/nfd-client/worker/nfd-worker.go

Drop the following flags that were deprecated already in v0.8.0:
`-sleep-interval`  (replaced by `core.sleepInterval` config file option)
`-label-whitelist` (replaced by `core.labelWhiteList` config file option)
`-sources`         (replaced by `-label-sources flag`)

nfd-worker: drop deprecated command line flags

---

test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go
test/e2e/utils/daemonset/daemonset.go
test/e2e/utils/pod/pod.go

By moving those utils into a separate package,
we can make the function names shorter and more apparent.
For example, instead of:
```
testutils.NFDWorkerPod(opts...)
testutils.NFDMasterPod(opts...)
testutils.SpecWithContainerImage(...)
```
we'll have the following:
```
testpod.NFDWorker(opts...)
testpod.NFDMaster(opts...)
testpod.SpecWithContainerImage(...)
```
It will also make the package more isolated and portable.
This work was initiated by the discussion here: https://github.com/kubernetes-sigs/node-feature-discovery/pull/964#issuecomment-1324093399

e2e: move pod utils to a seperate package

---

docs/get-started/introduction.md
docs/get-started/quick-start.md
docs/usage/custom-resources.md
docs/usage/customization-guide.md
docs/usage/examples-and-demos.md

Add a separate page for describing the custom resources used by NFD. Simplify the Introduction page by moving the details of NodeResourceTopology from there. Similarly, drop long NodeResourceTopology example from the quick-start page, making the page shorter and simpler.

docs: better document custom resources

---

docs/get-started/quick-start.md
docs/usage/nfd-topology-updater.md

Move topology-updater deployment notes to the topology-updater usage page. Also, rework the plaintext and headings a bit.

docs: simplify quick-start page

---

docs/usage/customization-guide.md

Add a reference to the label rule format in the NodeFeatureRule section. Also make it explicit in the beginning of Hooks section that hooks are deprecated.

docs: small update to customization guide

---

test/e2e/node_feature_discovery.go
test/e2e/utils/pod/pod.go

Fixes stricter API check on daemonset pod spec that started to cause e2e test failures. RestartPolicyNever that we previously set (by defaylt) isn't compatible with DaemonSets.

test/e2e: no pod restart policy of nfd-worker by default

---

deployment/helm/node-feature-discovery/templates/service.yaml

The nfd-workers don't have any exposed ports. It would be cleaner to have the service selector only point to the pods that actually expose a container port and host the grpc service

nfd-master svc should select only nfd-master pods

---

cmd/nfd-master/main.go

Extra dash caused a panic when trying to run the binary.

nfd-master: fix creation of the -enable-nodefeature-api flag

---

Makefile

In most of the cases we fall back to `${HOME}/.kube/config` anyways.

E2E: default kubeconfig location to ${HOME}/.kube/config

---

pkg/apis/nfd/v1alpha1/feature.go
pkg/nfd-master/nfd-master.go

Implement handling of multiple NodeFeature objects by merging all objects (targeting a certain node) into one before processing the data. This patch implements MergeInto() methods for all required data types.
With support for multiple NodeFeature objects per node, The "nfd api workflow" can be easily demonstrated and tested from the command line. Creating the folloiwing object (assuming node-n exists in the cluster):
```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeature
metadata:
labels:
nfd.node.kubernetes.io/node-name: node-n
name: my-features-for-node-n
spec:
features:
flags:
vendor.domain-a:
elements:
feature-x: {}
attributes:
vendor.domain-b:
elements:
feature-y: "foo"
feature-z: "123"
instances:
vendor.domain-c:
elements:
- attributes:
name: "elem-1"
vendor: "acme"
- …
```

nfd-master: handle multiple NodeFeature objects

---

test/e2e/node_feature_discovery.go

Leftover from development that got accidentally merged in 43910e6925e2bf1c050bbacf806f3ef3469f427d

test/e2e: fix mistake in ginkgo focus

---

test/e2e/utils/pod/pod.go

Use RuntimeDefault seccomp profile in nfd worker and topology updater pod spec similar to nfd master.
Otherwise, we get PodSecurity violation when running locally:
```
Dec 14 16:45:41.440: Unexpected error:
<*errors.StatusError | 0xc000d58a00>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "pods \"nfd-worker-6ee0652e-2dca-49a0-ac88-9896453b3655\" is forbidden: violates PodSecurity \"restricted:latest\": restricted volume types (volumes \"host-boot\", \"host-os-release\", \"host-sys\", \"host-usr-lib\", \"host-usr-src\" use restricted volume type \"hostPath\"), seccompProfile (pod or container \"node-feature-discovery\" must set securityContext.seccompProfile.type to …
```

E2E: default seccompProfile to runtimeDefault for nfd worker

---

docs/deployment/helm.md
docs/get-started/introduction.md
docs/reference/master-commandline-reference.md
docs/reference/worker-commandline-reference.md
docs/reference/worker-configuration-reference.md
docs/usage/custom-resources.md
docs/usage/customization-guide.md
docs/usage/nfd-master.md

Document the usage of the NodeFeature CRD API. Also re-organize the
documentation a bit, moving the description of NodeFeatureRule
controller from customization guide to nfd-master usage page.

docs: document NodeFeature API

---

test/e2e/node_feature_discovery.go

Drop the pod-security.kubernetes.io/enforce label from the test namespace, i.e. remove pod security admission enforcement. NFD-worker uses restricted host mounts (/sys) etc so pod creation fails even in privileged mode if pod security admission enforcement is enabled.

test/e2e: drop pod security enforcement label from the test namespace

---

pkg/nfd-master/nfd-master.go

We want to always update all nodes at startup. Without this patch we don't get any update event from the controller if no NodeFeature or NodeFeatureRule objects exist in the cluster. Thus all nodes would stay untouched whereas we really want to remove all labels from all nodes in this case.

nfd-master: update all nodes at startup when NodeFeature API enabled

---

pkg/nfd-master/nfd-master.go

Correctly handle the case where no NodeFeature objects exist for certain
node (and NodeFeature API has been enabled with
`-enable-nodefeature-api`). In this case all the labels should be removed.

nfd-master: update node if no NodeFeature objects are present

---

test/e2e/utils/pod/pod.go

Allows running e2e-tests in some more restricted environments.

test/e2e: drop host-usr-src mount

---

test/e2e/data/nodefeaturerule-3-updated.yaml
test/e2e/data/nodefeaturerule-3.yaml
test/e2e/node_feature_discovery.go
test/e2e/utils/crd.go
test/e2e/utils/pod/pod.go

This PR extends E2E to test NodeFeatureRule tainting functionality implemented in https://github.com/kubernetes-sigs/node-feature-discovery/pull/910.
/hold 
until https://github.com/kubernetes-sigs/node-feature-discovery/pull/910 is not merged.

Add E2E test for NFD tainting feature

---

test/e2e/node_feature_discovery.go
test/e2e/utils/pod/pod.go
test/e2e/utils/rbac.go

Add an initial test set for the NodeFeature API. This is done simply by
running a second pass of the tests but with -enable-nodefeature-api
(i.e. NodeFeature API enabled and gRPC disabled). This should give basic
confidence that the API actually works and form a basis for further
imporovements on testing the new CRD API.

test/e2e: add basic e2e-tests for NodeFeature API

---

docs/deployment/helm.md
docs/deployment/index.md
docs/deployment/kustomize.md
docs/deployment/operator.md

docs: better document differences between deployment methods

---

docs/usage/custom-resources.md

In the CRD intro, mention that NodeFeature can be used as an integration point for 3rd party extensions.

docs: mention NodeFeature as an extension point

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/overlays/prune/master-job.yaml
test/e2e/utils/pod/pod.go

Use the "single-dash" version of nfd command line flags in deployment files and e2e-tests. No impact in functionality, just aligns with documentation and other parts of the codebase.

Use single-dash format for nfd cmdline flags

---

cmd/nfd-topology-updater/main.go
pkg/nfd-topology-updater/nfd-topology-updater.go

Move and rename the Go package. It has nothing to do with NFD gRPC
client anymore so move it out of the nfd-client package.

topology-updater: move code

---

deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
pkg/apis/nfd/v1alpha1/generated.proto
pkg/apis/nfd/v1alpha1/types.go

Don't require features to be specified. The creator possibly only wants
to create labels or only some types of features. No need to specify
empty structs for the unused fields.

apis/nfd: make all fields in NodeFeatureSpec optional

---

docs/usage/features.md
go.mod
go.sum

This commit bumps cpuid version to [v2.2.3 ](https://github.com/klauspost/cpuid/releases/tag/v2.2.3 ) which adds support for detecting Intel Sierra Forest instructions.
Partially fixes: https://github.com/kubernetes-sigs/node-feature-discovery/issues/947

Bump cpuid to v2.2.3

---

test/e2e/data/nodefeature-1.yaml
test/e2e/data/nodefeature-2.yaml
test/e2e/node_feature_discovery.go
test/e2e/utils/crd.go

Test creation of multiple NodeFeature objects per node, mocking 3rd party extensions.

test/e2e: more comprehensive test for NodeFeature objects

---

go.mod
go.sum
pkg/topologypolicy/topology-policy.go
pkg/topologypolicy/topology-policy_test.go

Version `0.0.13` of NodeResourceTopology API added missing `TopologyManagerPolicy` for other policies than `single-numa-node`. This PR adds support for those new values.

Add missing TopologyManagerPolicy

---

test/e2e/e2e_test.go
test/e2e/node_feature_discovery_test.go
test/e2e/topology_updater_test.go

The docker image that used during e2e test
composed of repo and tag flags that are
passed to the test itself.
The problem is that the docker image initialized
before the flags are parsed. Hence, it will always contains the default flags value.
Initialize the flag in later stage, fixing the issue.
Also, moving the global variables to `e2e_test.go` since it commonly used by all tests.
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

e2e: init docker image

---

pkg/nfd-master/nfd-master.go

nfd-master: always start gRPC server

---

Makefile

Update to the latest patch release of golang.

[release-0.12] Update docker builder image to golang v19.5

---

docs/deployment/helm.md
docs/deployment/kustomize.md
docs/deployment/operator.md
docs/deployment/tls.md
docs/deployment/uninstallation.md
docs/get-started/introduction.md
docs/reference/master-commandline-reference.md
docs/reference/worker-commandline-reference.md
docs/reference/worker-configuration-reference.md
docs/usage/custom-resources.md
docs/usage/customization-guide.md
docs/usage/features.md
docs/usage/nfd-master.md
docs/usage/nfd-topology-gc.md
docs/usage/nfd-topology-updater.md
docs/usage/nfd-worker.md

Fixing external references by injecting .md so that links works correctly while reading the documentation.

docs: fix internal cross-page references by injecting .md

---

test/e2e/e2e_test.go
test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go

The docker image that used during e2e test
composed of repo and tag flags that are
passed to the test itself.
The problem is that the docker image initialized
before the flags are parsed. Hence, it will always contains the default flags value.
Moving the variable into a separate function, fixing the issue.
Also, moving the global variables to `e2e_test.go` since it commonly used by all tests.
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

[release-0.12] e2e: init docker image

---

deployment/helm/node-feature-discovery/README.md

(cherry picked from commit 1c095f5e8e278015da887ef28d66c6f3e5de4130)

[release-0.12] docs: Fix link for Helm docs

---

docs/usage/customization-guide.md
docs/usage/features.md
source/cpu/coprocessor_ppc64le.go
source/cpu/coprocessor_stub.go
source/cpu/cpu.go

Signed-off-by: Chandan Abhyankar <Chandan.Abhyankar@ibm.com>
Adding nx-gzip label support

cpu: support for detecting nx-gzip coprocessor feature

---

Dockerfile
scripts/test-infra/verify.sh

Move out running unit tests as part of container image building and 
instead add it into verify.sh script which runs linter, formatter and
other checks. As a future improvement, we could have separate
Prow jobs for fmt, golangci-lint, helm-linter and unit tests separately.

test: move out unit testing from Dockerfile

---

deployment/base/noderesourcetopologies-crd/noderesourcetopologies.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater-crds.yaml
go.mod
go.sum
pkg/nfd-topology-gc/nfd-nrt-gc.go
pkg/nfd-topology-gc/nfd-nrt-gc_test.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/resourcemonitor/noderesourcesaggregator.go
pkg/resourcemonitor/noderesourcesaggregator_test.go
pkg/resourcemonitor/types.go
pkg/topologypolicy/topology-policy.go
pkg/topologypolicy/topology-policy_test.go
test/e2e/topology_updater_test.go
test/e2e/utils/noderesourcetopology.go

As part of #1048 we need to update NRT API to `v1alpha2` 
where new top-level attributes have been added to NRT objects.
We will use this top-level attributes to report new pod fingerprint values. see: #1049 
address: #1048 
see: [this issue](https://github.com/k8stopologyawareschedwg/noderesourcetopology-api/issues/30) for more info about new NRT api version

topology-updater: nrt-api Update to v1alpha2

---

pkg/nfd-worker/nfd-worker.go

This pull request changes the nfd-worker to use `time.Ticker` instead of `time.After` to implement  `core.sleepInterval`. An infinite interval is represented by stopping the Ticker.
Issue: https://github.com/kubernetes-sigs/node-feature-discovery/issues/899

Change nfd-worker to use Ticker instead of After.

---

Makefile
docs/deployment/image-variants.md
docs/reference/worker-configuration-reference.md
docs/usage/customization-guide.md

Make distroless/base as the base image for the default image, effectively making the minimal image as the default. Add a new "full" image variant that corresponds the previous default image. The "*-minimal" container image tag is provided for backwards compatibility.
The practical user impact of this change is that hook support is limited to statically linked ELF binaries. Bash or Perl scripts are not supported by the default image, anymore, but the new "full" image variant can be used for backwards compatibility.
Refs #855 
Fixes #963

images: base the default image on distroless/base

---

pkg/nfd-worker/nfd-worker.go

This pull request adds logging of discovery durations. There are some optional things mentioned in https://github.com/kubernetes-sigs/node-feature-discovery/issues/899 by @eero-t. I had a quick discussion with @marquiz and if I understood correctly something like what is implemented here could also be useful. Depending on what exactly is wanted, this could close https://github.com/kubernetes-sigs/node-feature-discovery/issues/899. This is related to work done in https://github.com/kubernetes-sigs/node-feature-discovery/pull/1050.
The logging output can look like this:
```console
<output from other sources>
I0213 12:42:32.317317 2204667 nfd-worker.go:199] discovery duration for "system" source: 472.156µs
I0213 12:42:32.318310 2204667 usb.go:150] discovered usb features:
I0213 …
```

Add discovery duration logging

---

cmd/nfd-topology-updater/main.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/utils/kubeconf/kubelet_config_file.go
test/e2e/utils/noderesourcetopology.go

We want to advertise TopologyManager policy and scope as top level attributes in noderesourcetopology-api `v1alpha2`.
Based on this PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/488.

Advertise TopologyManger policy and scope as Attributes in NRT api v1alpha2

---

cmd/nfd-master/main.go
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-commandline-reference.md
docs/usage/customization-guide.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/utils/flags.go

Resolves #1022.
Signed-off-by: AhmedGrati <ahmedgrati1999@gmail.com>

feat: add deny-label-ns flag which supports wildcard

---

scripts/test-infra/verify.sh
test/e2e/e2e_test.go

scripts/test-infra: bump golangci-lint to v1.51.1

---

Makefile
go.mod

This patch
- Bumps GO to 1.20
- Updates deps by running "go mod tidy"

GO Update version to 1.20

---

docs/usage/features.md
go.mod
go.sum

Bump cpuid version to v2.2.4 in the go.mod so that WRMSRNS (Non-Serializing Write to Model Specific Register) and MSRLIST (Read/Write List of Model Specific Registers) instructions are detectable.
CPUID latest release reference: https://github.com/klauspost/cpuid/releases/tag/v2.2.4

go.mod: bump cpuid to v2.2.4

---

docs/get-started/introduction.md

fix omit describe for nfd-topology-gc.

docs: describe nfd-topology-gc in introduction.md

---

test/e2e/node_feature_discovery_test.go
test/e2e/topology_updater_test.go

Make it easier to only run tests for nfd master/worker and skip topology-updater tests.

test/e2e: rename ginkgo focus for tests

---

cmd/nfd-topology-updater/main.go
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/reference/topology-updater-commandline-reference.md
go.mod
go.sum
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-topology-updater/nfd-topology-updater_test.go
pkg/resourcemonitor/podresourcesscanner.go
pkg/resourcemonitor/podresourcesscanner_test.go
pkg/resourcemonitor/types.go
test/e2e/topology_updater_test.go

Add an option to compute the fingerprint of the current pod set on each node.
Report this new fingerprint using an attribute in new released `v1alpha2` NRT object.
needs: #1053 
address: #1048 
see: [this issue](https://github.com/k8stopologyawareschedwg/noderesourcetopology-api/issues/30) for more info about new NRT api version

topology-updater:compute pod set fingerprint

---

Makefile

Add code coverage reporting so that the report is then available to the PR author and reviewers via codecov GitHub app.
@marquiz for uploading/reporting the coverage results, we need to run `make test`. We already run the `make test` with one of the Prow job and I didn't want to add another one in the form of GitHub action. But GA is the most straightforward way of adding codecov and uploading it. There is an uploader available which can be executed from shell as well, so that can be added into Prow job run section, but for that codecov requires the token. We could store the token as a secret on GitHub but I don't know if there is a way actually for the Prow to ready/fetch that token. At least I have not seen anything like that. 
With GitHub actions it is not a problem, because we just …

test: add code coverage reporting

---

deployment/helm/node-feature-discovery/templates/clusterrole.yaml
deployment/helm/node-feature-discovery/values.yaml

- fix topology-updater rbac clusterrole 
Access to nodes/proxy resource was accidentally given to nfd-master
(which really doesn't need it), not topology-updater.
- create topology-updater RBAC rules by default 
Create RBAC rules if topology-updater is enabled. Previously installing
with topologyUpdater.enable=true (without
topologyUpdater.rbac.create=true) resulted in a crashloogbackoff as RBAC
was missing.

helm: fix topology-updater rbac

---

deployment/components/topology-updater/topologyupdater-mounts.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml

- kustomize: drop mount for kubelet config in topology-updater
We use the configz endpoint nowadays.
- helm: fix handling of topologyUpdater.kubeletConfigPath
By default we use the configz API endpoint so no mounts are needed.

deployment: fixes for mounting kubelet config

---

pkg/utils/flags.go

Make it possible to specify values in yaml as an array like
```yaml
conf:
- foo
- bar
````
Instead of unwieldy map like
```yaml
conf:
foo:
bar:
```

pkg/utils: add UnmarshalJSON method to StringSetVal

---

.gitignore

We don't necessarily need to keep the codecov coverage report on the git. As such, adding it to the gitignore to avoid it from accidental commiting.

gitignore: ignore codecov coverage report

---

pkg/nfd-worker/nfd-worker.go

As discussed in #1084, we need to add the dump of the nfd worker configuration, which can be really useful when debugging.

chore: add debug dump of nfd worker configuration

---

docs/usage/customization-guide.md
docs/usage/features.md
source/cpu/cpu.go
source/cpu/security_amd64.go

Enable the feature discovery of AMD SEV, SEV_ES and SEV_SNP as part of the `cpu-security` attribute

cpu: expose AMD SEV support

---

docs/usage/customization-guide.md
docs/usage/features.md
source/cpu/security_amd64.go

The total amount of keys that can be used on a specific TDX system is exposed via the cgroups misc.capacity. See:
```
$ cat /sys/fs/cgroup/misc.capacity
tdx 31
```
The first step to properly manage the amount of keys present in a node is exposing it via the NFD, and that's exactly what this commit does.
An example of how it ends up being exposed via the NFD:
```
$ kubectl get node 984fee00befb.jf.intel.com -o jsonpath='{.metadata.labels}'  | jq | grep tdx.total_keys
"feature.node.kubernetes.io/cpu-security.tdx.total_keys": "31",
```

cpu: Expose the total number of keys for TDX

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Also updates the Golang builder image to the latest v1.19 patch release (i.e. v1.19.7).
hack/prepare-release.sh -g 1.19.7 v0.12.2

Update references to release v0.12.2

---

Makefile
cmd/nfd-master/main.go
deployment/base/master/master-deployment.yaml
deployment/components/common/kustomization.yaml
deployment/components/common/master-mounts.yaml
deployment/components/master-config/kustomization.yaml
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-master-conf.yaml
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/default-combined/kustomization.yaml
deployment/overlays/default-job/kustomization.yaml
deployment/overlays/default/kustomization.yaml
deployment/overlays/master-worker-topologyupdater/kustomization.yaml
docs/deployment/helm.md
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
docs/reference/topology-gc-commandline-reference.md
docs/reference/topology-updater-commandline-reference.md
docs/reference/topology-updater-configuration-reference.md
docs/reference/worker-configuration-reference.md
docs/usage/nfd-master.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/nfd-master_test.go
pkg/nfd-worker/nfd-worker_test.go
test/e2e/node_feature_discovery_test.go
test/e2e/utils/configmap.go

feat: add master config file

---

test/e2e/utils/crd.go

Wait for the deletion of NFD CRDs to complete before trying to re-create them. Prevents errors in case CRDs already exist on the cluster when e2e-tests are launched.

test/e2e: wait for CRD deletion to complete

---

test/e2e/node_feature_discovery_test.go

Make the default master pod run with no special options. Move the
customizations of the master pod to the setup functions of the tests
that actually need it.
Also, cleanup the configuration of nfd-worker of some tests.

test/e2e: refactor nfd pod configuration

---

docs/usage/customization-guide.md
pkg/apis/nfd/v1alpha1/annotations_labels.go
pkg/nfd-master/nfd-master.go
test/e2e/data/nodefeaturerule-3-updated.yaml
test/e2e/data/nodefeaturerule-3.yaml
test/e2e/node_feature_discovery_test.go

Disallow taints having a key with "kubernetes.io/" or "*.kubernetes.io/"
prefix. This is a precaution to protect the user from messing up with
the "official" well-known taints from Kubernetes itself. The only
exception is that the "nfd.node.kubernetes.io/" prefix is allowed.
However, there is one allowed NFD-specific namespace (and its
sub-namespaces) i.e. "feature.node.kubernetes.io" under the
kubernetes.io domain that can be used for NFD-managed taints.
Also disallow unprefixed taint keys. We don't add a default prefix to
unprefixed taints (like we do for labels) from NodeFeatureRules. This is
to prevent unpleasant surprises to users that need to manage matching
tolerations for their workloads.

nfd-master: disallow unprefixed and kubernetes taints

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Update node status before node metadata. This fixes a problem where we lose track of NFD-managed extended resources in case patching node status fails. Previously we removed all labels and annotations (including the one listing our ERs) and only after that updated node status. If node status update failed we had lost the annotation but extended resources were still there, leaving them orphaned.
This was exposed by the e2e tests in #1099

nfd-master: fix node update

---

docs/usage/customization-guide.md
source/cpu/cpu.go
source/cpu/rdt_amd64.go
source/cpu/rdt_stub.go

Enable the feature discovery of `RDTL3CA_NUM_CLOSID` as part of the cpu-rdt source.
This feature is intended to be used as `extended` resource when this PR is merged https://github.com/kubernetes-sigs/node-feature-discovery/pull/1099

Advertise RDT L3 num_closid

---

deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/base/rbac/master-clusterrole.yaml
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/templates/clusterrole.yaml
docs/usage/customization-guide.md
examples/nodefeaturerule.yaml
pkg/apis/nfd/v1alpha1/annotations_labels.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/types.go
pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/data/nodefeaturerule-4.yaml
test/e2e/node_feature_discovery_test.go
test/e2e/utils/rbac.go

Fixes #1081 
Add support for management of extended resources with the
`NodeFeatureRule` CRD API.
There are usage scenarios where users want to advertise features
as extended resources instead of labels (or annotations).
This patch enables the discovery of extended resources, via annotation
and patch of `node.status.capacity` and `node.status.allocatable` By using
the `NodeFeatureRule` API.
Co-authored-by: Carlos Eduardo Arango Gutierrez <eduardoa@nvidia.com>
Co-authored-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

Create extended resources with NodeFeatureRule

---

Dockerfile

Dockerfile: bump grpc-health-probe to v0.4.17

---

docs/deployment/uninstallation.md
docs/get-started/introduction.md

A small update to fix some missing mentions of extended resources and taints as assets managed by NFD.

docs: add missing mentions of extended resources and taints

---

pkg/nfd-master/nfd-api-controller.go

Increase the NFD API controller resync period from 5 minutes to 1 hour.
The resync causes nfd-master to replay all NodeFeature and
NodeFeatureRule objects, being effectively a "big hammer reset all"
button. This should only be needed as an "insurance" to fix labels et al
in case they have been manually tampered (outside NFD) and against
certain bugs in nfd itself. NFD is not supposed to manage anything
fast-changing so 1 hour should be enough.
This change only affects behavior when the NodeFeature API has been
enabled (with -enable-nodefeature-api).

nfd-master: increase controller resync period to 1 hour

---

pkg/nfd-master/nfd-master.go

Change the NFD API handler to re-try on node update failures. Will work around transient failures, making sure that failed nodes (i.e. nodes that we failed to update) don't need to wait for the 1 hour resync period before being tried again.
This is another problem revealed by the recent addition of e2e-tests for extended resources.

nfd-master: re-try on node update failures

---

Makefile

Previously we were using the default, which even if equal to 0, still means 10 minute timout in practice (with the way we run the tests with invoking go test directly). With the addition of latest e2e tests we hit the limit and got bitten by it. Set the timeout to 1 hour which should be enough for anyone...

Makefile: set e2e test timeout to 1 hour

---

cmd/nfd-master/main.go
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md

Mark the -resource-labels flag (and the corresponding resourceLabels config option) as deprecated. We now support managing extended resources via NodeFeatureRule objects. This kludge deserves to go, eventually.
Refs #1125

nfd-master: deprecate the -resource-labels flag

---

docs/usage/features.md
source/cpu/cpu.go

Just have that as a feature for NodeFeatureRules to consume.

source/cpu: don't create cpu-security.tdx.total_keys label

---

codecov.yml
scripts/test-infra/verify.sh

e2e: add codecov uploader configuration
Depends on https://github.com/kubernetes/test-infra/pull/29082.

e2e: add codecov uploader configuration

---

Dockerfile

A new version that was just released.

Dockerfile: bump grpc-health-probe to v0.4.18

---

docs/_includes/class/content-wrap.liquid

Copied what #1132 did. Outcome will be similar (https://kubernetes-sigs.github.io/node-feature-discovery/v0.6)

[release-0.9] docs: mark release v0.9 as unsupported

---

docs/_includes/class/content-wrap.liquid

Copied what #1132 did. Outcome will be similar (https://kubernetes-sigs.github.io/node-feature-discovery/v0.6)

[release-0.7] docs: mark release v0.7 as unsupported

---

docs/_includes/class/content-wrap.liquid

Copied what #1132 did. Outcome will be similar (https://kubernetes-sigs.github.io/node-feature-discovery/v0.6)

[release-0.8] docs: mark release v0.8 as unsupported

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Bump Golang builder image to v1.19.8 as well.
hack/prepare-release.sh -g 1.19.8 v0.12.3

[release-0.12] Update references to release v0.12.3

---

docs/usage/features.md
source/cpu/cpu.go
source/cpu/security_amd64.go

This patch add SEV ASIDs and the related (but distinct) SEV Encrypted State (SEV-ES) IDs as two quantities to be exposed via extended resources. In a kernel built with CONFIG_CGROUP_MISC on a suitably equipped AMD CPU, the root control group will have a misc.capacity file that shows the number of available IDs in each category:
```bash
$ cat misc.capacity
sev 50
sev_es 10
```
The added extended resources are:
- sev.asids
- sev.encrypted_state_ids
An example on how to expose them on a suitable system is:
```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
name: sev-capacity
spec:
rules:
- name: "SEV system capacity"
extendedResources:
sev_asids: "@cpu.security.sev.asids"
sev_es: "@cpu.security.sev.encrypted_state_ids"
matchFeatures:
- feature: cpu.security …
```

 cpu: expose the total number of AMD SEV ASID and ES

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topology-gc/topology-gc.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Bump Golang builder image to v1.20.3.
hack/prepare-release.sh -g 1.20.3 v0.13.0

[release-0.13] Update references to release v0.13.0

---

test/e2e/node_feature_discovery_test.go
test/e2e/topology_updater_test.go
test/e2e/utils/configmap.go
test/e2e/utils/crd.go
test/e2e/utils/node.go
test/e2e/utils/noderesourcetopology.go
test/e2e/utils/pod/pod.go
test/e2e/utils/rbac.go
test/e2e/utils/service.go

Eliminate all context.TODO() from the e2e tests and use ginkgo context instead. This ensures that calls involving context are properly cancelled and return fast in case the tests get aborted.

test/e2e: use proper context

---

deployment/overlays/prune/kustomization.yaml
pkg/nfd-master/nfd-master.go

- configure before prune
Otherwise prune will crash because of uninitialized configuration.
- deployment/kustomize: add master config to prune overlay
Otherwise pods error out with failed mount of nfd-master-conf ConfigMap.

nfd-master: fix -prune

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Make the nfd.node.kubernetes.io/feature-labels and nfd.node.kubernetes.io/extended-resources annotations behave similary to the taints annotation: only create the annotations if some labels or extended resources are created.

nfd-master: don't create emtpy annotations

---

pkg/apis/nfd/v1alpha1/feature.go
pkg/nfd-master/nfd-master.go

Fix a a bug where nfd-master with NodeFeature API enabled would crash when NodeFeatureRule objects were processed in the case where no NodeFeature objects existed. This was caused by trying to insert values into a non-initialized NodeFeatureSpec in the code.
This patch adds two safety measures to prevent that from happening in the future. First, add a constructor function for the NodeFeatureSpec type, and second, check for uninitialized object in the function inserting new functions.
TODO: add unit tests for the API helper functions.
Fixes #1170

nfd-master: fix a crash when processing NodeFeatureRules

---

pkg/nfd-master/nfd-master.go

Fix typo: `foundon` -> `found on`

pkg/nfd-master/nfd-master.go: Fix typo

---

pkg/nfd-master/nfd-master.go

on _filterExtendedResources_ check if capacity is in the form `@domain.feature.element`
Fixes #1168

nfd-master: reject malformed extended resource dynamic capacity assignment

---

cmd/nfd-master/main.go
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/flags.go

feat: add master resync period configurability

---

pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go

This PR fixes 2 problems with kubeletnotifier:
- `kubelet_internal_checkpoint` file is in `/var/lib/kubelet/device-plugins` (as defined [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/constants.go#L30) and fsWatcher doesn't watch dirs recursively
- `e.Name` returned from fsWatcher events is a full path not a basename 
We really need tests for this feature 😄

nfd-topology-updater: fix wrong kubelet_internal_checkpoint path and compare basename to full path

---

docs/deployment/index.md
docs/deployment/kustomize.md
docs/get-started/index.md
docs/usage/features.md

Commit bfbc47f55e460ec80bfb8f57125ee3a0d2967486 added a lot of those and this patch tries to cover all that we missed there. Having .md suffixes in references to internal files makes it convenient to browse the document locally, just as text files as the references work correctly.

docs: add missing .md suffix to internal references

---

hack/prepare-release.sh

```bash
Usage: $this [-h] [-b] [-k GPG_KEY] {-a|-g GOLANG_VERSION} RELEASE_VERSION
Example:
-  $this v0.1.2 -k "Jane Doe <jane.doe@example.com>"
+ $this -k "Jane Doe <jane.doe@example.com>" v0.13.1
```
Release is the last arg, not the first

Match usage and example for prepare-release.sh

---

codecov.yml

not to block currently open PRs from getting merged and deal with target setting separately.

codecov: drop required minimum coverage ratio of a commit to 0%

---

codecov.yml

previously in https://github.com/kubernetes-sigs/node-feature-discovery/pull/1200 we added similar to project and this is doing the same but for the patch level.

codecov: drop required minimum coverage ratio at patch level

---

pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-api-controller_test.go

Split out resolving of node name (of the node to be updated) into a separate function. Makes it possible to add unit tests. Also. do unconditional type casting in the handler functions – that shouldn't fail unless there is a really serious internal inconsistency in the codebase so it should be ok to panic.

nfd-master: refactor api-controller object handling

---

pkg/nfd-master/nfd-master.go

Simplify code a bit and get more consistent error messages (in addition to
fixing some of those).
Also preparation for dynamic labels values (that `@` notation currently supported for extended resources).

nfd-master: refactor filtering of labels, taints and ERs

---

deployment/helm/node-feature-discovery/templates/master.yaml

Volume/mount setup for the ConfigMap was erroneously inside conditionals so it was not mounted unless TLS was enabled.

helm: fix mount for nfd-master config

---

deployment/helm/node-feature-discovery/templates/master.yaml

Volume/mount setup for the ConfigMap was erroneously inside conditionals so it was not mounted unless TLS was enabled.
(cherry picked from commit b016def8a3cbf7494fd623605045a39159a2f7d7)

[release-0.13] helm: fix mount for nfd-master config

---

cmd/nfd-master/main.go
pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master.go
test/e2e/node_feature_discovery_test.go

Resolves #1181.
**How to test:**
Make sure that CRDs have been deployed and then run locally
```bash
make build
NODE_NAME=<node-name> ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -resync-period=1s
```

nfd-master: fix resync period config option

---

deployment/helm/node-feature-discovery/values.yaml

This parameter is a path in the host system, not a mount path inside the container.

deployment/helm: fix default for kubeletStateDir parameter

---

deployment/components/topology-updater/topologyupdater-mounts.yaml

This mount is redundant as it's already included in the kubelet state files (/var/lib/kubelet) mount.

deployment/kustomize: drop pod-resources mount for topology-updater

---

test/e2e/gomega.go
test/e2e/node_feature_discovery_test.go

- Implement a new generic type nodeListPropertyMatcher, a generic Gomega
matcher for matching basically any property of a set of node objects. We
will be using it for verifying labels, annotations, extended resources
and taints for now. This moves the tests in a more Gomega'ish direction,
leveraging code re-use and providing way more informative error messages
in case of test failures.
The patch adds a new eventuallyNonControlPlaneNodes helper assertion for
asserting all (non-control-plane) nodes in the cluster, intended to
replace the ugly simplePoll() helper function.
This patch implements a matcher for node labels and converts tests to
use it instead of the old checkForNodeLabels helper function.
- Add new MatchAnnotations Gomega matcher and drop the old
waitForNfdNodeAnnotations …

test/e2e: refactor matching of node properties

---

deployment/helm/node-feature-discovery/templates/topologyupdater.yaml

Mount kubelet podresources socket on an independent path, not under with the kubelet state directory. Otherwise container creation may fail on mount creation if topologyUpdater.kubeletPodResourcesSockPath and/or topologyUpdater.kubeletConfigPath Helm parameters are specified in a certain way.

deployment/helm: avoid overlapping mount paths on topology-updater

---

deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
docs/deployment/helm.md

Make it possible to disable kubelet state tracking with --set topologyUpdater.kubeletStateFiles="" as the documentation suggests.
Also, fix the documentation regarding the default value of topologyUpdater.kubeletStateFiles parameter.

deployment/helm: improve handling of topologyUpdater.kubeletStateFiles

---

cmd/nfd-topology-updater/main.go
deployment/components/topology-updater/env.yaml
deployment/components/topology-updater/kustomization.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
docs/reference/topology-updater-commandline-reference.md

Use a separate NODE_ADDRESS environment variable in the default value of -kubelet-config-uri (instead of NODE_NAME that was previously used). Also change the kustomize and Helm deployments to set this variable to node IP address. This should make the default deployment more robust, making it work in scenarios where node name does not resolve to the node ip, e.g. nodename != hostname.

topology-updater: use node IP in the default configz URI

---

test/e2e/node_feature_discovery_test.go

Delete `NodeFeatureRule` and `NodeFeature` CRs only if found.

e2e: delete CRs only if found

---

cmd/nfd-master/main.go
deployment/base/rbac/master-clusterrole.yaml
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/templates/clusterrole.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
docs/usage/nfd-master.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

This should fix https://github.com/kubernetes-sigs/node-feature-discovery/issues/1188
Right now it is still in progress.
Missing:

Add leader election for nfd-master

---

pkg/nfd-master/nfd-master.go

Simpler and more reliable (in case of multiple consumers) to just close the channel.

nfd-master: use close for stop channel

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Validate labels before trying to update the node. Makes us fail early nad prevent useless retries in case invalid labels are tried.

nfd-master: add validation of label names and values

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Validate labels before trying to update the node. Makes us fail early nad prevent useless retries in case invalid labels are tried.
(backported from commit 2a3c7e4c9357b5426c1203ba7684e6f966a0d65f)

[release-0.13] nfd-master: add validation of label names and values

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Validate labels before trying to update the node. Makes us fail early nad prevent useless retries in case invalid labels are tried.
(backported from commit 2a3c7e4c9357b5426c1203ba7684e6f966a0d65f)

[release-0.12] nfd-master: add validation of label names and values

---

scripts/test-infra/logcheck.conf
scripts/test-infra/verify.sh

Now that we've migrated to structured logging add a verification step to verify that future additions/changes to logging comply.

scripts/test-infra: add logcheck to verify script

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topology-gc/topology-gc.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Update references and bump golang to v1.20.4.
hack/prepare-release.sh -g 1.20.4 v0.13.2

[release-0.13] Prepare for release 0.13.2

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Bump golang to v1.19.9.
hack/prepare-release.sh -g 1.19.9 v0.12.4

[release-0.12] Update references to release v0.12.4

---

deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/worker-configuration-reference.md
docs/usage/customization-guide.md
docs/usage/features.md
go.mod
go.sum
source/cpu/cpu.go
source/cpu/security_amd64.go

NFD already has the capability to discover whether baremetal / host
machines support Intel TDX.  Now, the next step is to add support for
discovering whether a node is TDX protected (as in, a virtual machine
started using Intel TDX).
In order to do so, we've decided to go for a new `cpu-security.tdx`
property, called `protected` (`cpu-security.tdx.protected`).
NOTE: We have to update the cpuid to its v2.2.5 release, released on
June 2nd, 2023, as it brings in information about TDX guests.

cpu: Discover TDX guests based on cpuid information

---

deployment/base/master/master-deployment.yaml
deployment/base/master/master-service.yaml

deployment/kustomize: use a named port for nfd gRPC service

---

README.md
docs/get-started/index.md
docs/get-started/quick-start.md

There seems to be missing apostrophes in the `jq` calls in the documentation.
jq version:
``` console
> jq --version
jq-1.6
```
current behaviour:
```console
> kubectl get no -o json | jq .items[].metadata.labels
zsh: no matches found: .items[].metadata.labels
```
changed behaviour:
```console
> kubectl get no -o json | jq '.items[].metadata.labels'
{
...
```

Fix missing apostrophe for jq

---

deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/worker-configuration-reference.md
docs/usage/customization-guide.md
source/local/local.go

We have deprecated hooks in v0.12.0 but kept it enabled by default. Starting from v0.13.x we are starting to disable it by default and plan to fully remove it in v0.14.x if there are no objections from the community.

hooks: disable hooks by default from v0.14

---

pkg/nfd-topology-gc/nfd-nrt-gc.go
pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go

Clean `ticker` in time.
Because it will cause memory leak if we do not stop `ticker` when the function has completed.

Stop ticker in time to avoid memory leak

---

pkg/nfd-master/nfd-master.go

Don't try to update all nodes on config change when the NodeFeature API is disabled. In this case we rely on gRPC and only act on gRPC requests from the worker.

[release-0.13] nfd-master: fix node updates on config change

---

pkg/nfd-master/nfd-master.go

nfd-master: check for nil references in nfdAPIUpdateAllNodes

---

source/cpu/security_amd64.go

We've been only considering cgroupsv2 when trying to read misc.capacity. However, there are still a bunch of systems out there relying on cgroupsv1.

cpu: Take cgroupsv1 into account when reading misc.capacity

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Update links for new release and update golang to v1.19.11.
hack/prepare-release.sh -g 1.19.11 v0.12.5

[release-0.12] Update references to release v0.12.5

---

docs/reference/versions.md

docs: document version and deprecation policy

---

docs/reference/topology-gc-commandline-reference.md
docs/reference/topology-updater-commandline-reference.md

Exclude the main title from to (with the empty line the "no_toc" directive took no effect).

docs: fix toc of topology-updater and topology-gc reference

---

docs/deployment/image-variants.md
docs/deployment/uninstallation.md
docs/usage/nfd-worker.md

Drop table of contents from short pages where it is only cluttering the page.

docs: remove useless TOCs

---

deployment/helm/node-feature-discovery/templates/prometheus.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/deployment/metrics.md

Prometheus is able to select monitors based on their labels.  This lets you easily set a label for the newly created monitor.

Add optional labels to the podmonitor

---

docs/deployment/index.md
docs/get-started/introduction.md
docs/usage/nfd-topology-updater.md

docs: describe supported Kubernetes versions

---

cmd/nfd-topology-updater/main.go
pkg/nfd-topology-updater/nfd-topology-updater.go

fixes https://github.com/kubernetes-sigs/node-feature-discovery/issues/1254

Fix Topology Manager policy and scope not being updated after NRT creation

---

docs/deployment/metrics.md

Also change table formatting and fix one incorrect description.

docs: align metrics documentation with latest changes on naming

---

source/local/local.go

Trim leading and trailing whitespace from the input (from feature files and hooks). Makes it a bit more relaxed on the expected input format.

source/local: trim whitespace from input

---

pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

Rename symbols and reword log messages to correlate with the
functionality (we may do other updates than just modify labels
nowadays).
This PR also containers a oneliner patch for removing one stale empty line from the codebase.

nfd-master: use term node update instead of labeling

---

docs/reference/master-commandline-reference.md
docs/reference/worker-commandline-reference.md

Document the -metrics command line flag in the command line reference of nfd-master and nfd-worker.

docs: document -metrics flag in command line reference

---

scripts/test-infra/verify.sh

Update logcheck to the latest version. Fixes the flakiness we've been experiencing.
Refs: https://github.com/kubernetes-sigs/logtools/pull/24

scripts/test-infra: update logcheck tool to v0.6.0

---

scripts/test-infra/verify.sh

Brings e.g. support for Go v1.21.

scripts/test-infra: bump golangci-lint to v1.54.0

---

pkg/nfd-topology-gc/nfd-nrt-gc.go

The stop channel has multiple readers to we need to close it so that all of the readers get notified.

topology-gc: fix Stop

---

pkg/nfd-topology-gc/nfd-nrt-gc.go
pkg/nfd-topology-gc/nfd-nrt-gc_test.go

topology-gc: rename run()

---

pkg/nfd-topology-gc/nfd-nrt-gc.go

topology-gc: rename runGC to garbageCollect()

---

pkg/nfd-topology-gc/nfd-nrt-gc.go

Small refactor. Contextually this feels more like under periodicGC().

topology-gc: move initial GC out of startNodeInformer()

---

docs/deployment/metrics.md
pkg/nfd-master/metrics.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

Add new metrics for nfd-master for better observability:
- add nfd_node_update_failures_total counter
Add a new counter for tracking node update failures from nfd-master.
This tracks both normal feature updates and the --prune sub-command.
This is a simple counter without any additional labels - nfd-master logs
can be used for further diagnostics.
- add nfd_nodefeaturerule_processing_errors_total counter
Add a counter for errors encountered when processing NodeFeatureRules.
Another simple counter without any additional prometheus labels -
nfd-master logs can provide further details.
- counters for rejected labels, extended resources and taints
Add counters for labels, extended resources and taints rejected/filtered
out by nfd-master.
- add nfd_node_update_requests_total counter
Add a …

metrics: additional metrics for nfd-master

---

cmd/nfd-topology-updater/main.go

Make it possible to run -version in an environment whithout the NODE_ADDRESS environment variable set.

topology-updater: make -version always runnable

---

Makefile
docs/Gemfile
docs/Gemfile.lock

Get away with the jekyll:3.8 image which is already four years old.  Use
the ruby instead. The jekyll image did not bring any value (more
problems, if anything) as we install/update jekyll and all other gems
with byndler nevertheless (image was jekyll:3.8 but we use jekyll
v3.9.3).
Also updates docs build dependencies.
Replaces #1316 and #1317

docs: use ruby docker image for building docs

---

docs/usage/nfd-topology-updater.md

Clarify that we account, and we can account, only
resources exclusively allocated to Guaranteed QoS pods.
Fixes: #1312

docs: nfd-updater: clarify accounting

---

pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
pkg/nfd-topology-updater/nfd-topology-updater.go
test/e2e/topology_updater_test.go
test/e2e/utils/noderesourcetopology.go

The nfd-topology-updater has state-directories notification enabled by default. In theory, we can have only timer-based updates, but if the option is given to disable the state-directories event source, then all the update mechanism is mistakenly disabled, including the timer-based updates.
The two updaters mechanism should be decoupled.
So this PR changes this to make sure we can enable just and only the timer-based updates.
WIP: missing tests (probably e2e tests is the "only" tests we need, but still, missing)

nfd-updater: events: enable timer-only flow

---

docs/usage/customization-guide.md
source/local/local.go
source/local/local_test.go
source/local/testdata/features.d/expired_feature
source/local/testdata/features.d/feature_with_comments
source/local/testdata/features.d/multiple_expiration_dates
source/local/testdata/features.d/unparsable_expiry_comment
source/local/testdata/features.d/valid_feature

Resolves #857.
This PR adds the expiration feature of feature files. The implemented solution suggests that the expiration date should follow this format:
```plaintext
```

Feat: add expiry date for feature files

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/get-started/introduction.md
docs/reference/master-commandline-reference.md
docs/reference/worker-commandline-reference.md
docs/usage/custom-resources.md
docs/usage/customization-guide.md
docs/usage/nfd-master.md
test/e2e/node_feature_discovery_test.go

Enable NodeFeature API by default

---

source/custom/custom.go
source/custom/static_features.go

Also add a log message warning about legacy rule format.

sources/custom: convert static rules to new format

---

cmd/nfd-master/main.go
cmd/nfd-master/main_test.go
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-configuration-reference.md
pkg/nfd-master/nfd-master.go

nfd-master: add config file options for logging

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

With the current implementation, our deployment and daemonset resources are set with an empty set of annotations; versus skipping them like in [other](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/node.yaml#L24) [helm](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L26) [charts](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/templates/deployment.yaml#L31).
This PR proposes a similar method to the other charts, for consistency with the rest of `kubernetes-sigs`

Helm: conditionally add annotations if defined

---

go.mod
go.sum

go.mod: bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/klog/klog.go
pkg/utils/klog/klog_test.go

chore: introduce a commong klog handling for cmd/nfd-*

---

docs/usage/customization-guide.md
docs/usage/features.md
source/cpu/cpu.go

Drop the deprecated cpu-sgx.enabled and cpu-se.enabled labels and the corresponding "raw" features. These have been replaced by cpu-security.sgx.enabled and cpu-security.se.enabled.
Fixes: #832

cpu: drop the deprecated sgx and se labels

---

scripts/github/update-gh-pages.sh

The gh-pages branch is normally automatically managed by the GitHub workflow. However, on really rare occasions there may beed to contribute something manually via a PR. Thus, this patch updates the update-gh-pages script to sync the OWNERS from master the gh-pages branch branch, to enable the usual prow-based workflow for PRs in gh-pages branch.

scripts/update-gh-pages: sync OWNERS from master to gh-pages

---

.github/workflows/gh-pages.yml

Ensure sequential updates to the gh-pages branch. Otherwise, if parallel jobs are triggered, onnly one (the first to complete) will succeed and the others will fail with git push error (because the tip of the gh-pages has moved and their commit doesn't apply anymore).

github: prevent parallel runs of gh-pages update

---

deployment/helm/node-feature-discovery/templates/role.yaml
deployment/helm/node-feature-discovery/templates/rolebinding.yaml

Put nfd-worker role and rolebinding in the correct namespace if namespaceOverride parameter is used.
Fixes: #1363

deployment/helm: fix namespace of nfd-worker role and rolebinding

---

.github/ISSUE_TEMPLATE/new-patch-release.md

Also simplify the wording on the major release issue template, eliminating "for a major release" from the text.

github: add a separate issue template for patch releases

---

Dockerfile
Makefile
docs/deployment/image-variants.md

Switch to fully statically linked binaries and use scratch as a base image.
Switching to the virtually empty scratch base image means that the default/minimal NFD image only supports running hooks that are truly statically linked (e.g.  normal go binaries that are "almost" statically linked stop working).  The documentation has been already stating this (i.e. that only statically-linked binaries are supported) - i.e. we have had no promise of supporting other than that. Also, hooks are now deprecated and even disabled by default so the possibility of real user impact should be small.

Build statically linked binaries

---

Dockerfile
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/overlays/samples/cert-manager/master-cert.yaml

Kubernetes [1.23](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) has introduced native health probes for gRPC which can replace
`grpc_health_probe` utility. This commit removes baking in `grpc_health_probe`
binary into the image and updates related health checks to use k8s native gRPC.

Replace gRPC health probe utility with k8s built-in health probe

---

pkg/nfd-master/nfd-master.go
test/e2e/data/nodefeaturerule-4.yaml
test/e2e/node_feature_discovery_test.go

Fix a bug in checking the allowed ".feature.node.kubernetes.io" ns suffix for extended resources. Also update e2e-tests to cover this case.

nfd-master: fix filtering of extended resources

---

pkg/apis/nfd/v1alpha1/types.go

Drop a leftover "docstring" comment that wasn't removed with the type it refers to.

apis/nfd: drop one stale comment line

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml

This patch continues to clean up after gRPC deprecation, by moving remaining flags in Helm charts under conditional of enableNodeFeatureAPI being set to false

Helm - Move remaining gPRC related flags to conditional

---

docs/usage/customization-guide.md
source/local/local.go
source/local/local_test.go
source/local/testdata/features.d/features_with_labels

Resolves #1376.
**Note: I used `no-label` and `no-feature` directives instead of `noLabel` and `noFeature`, to make it consistent with `expiry-time` directive.**

feat: support raw features

---

pkg/nfd-master/nfd-master.go

Delete correct annotations if -instance is specified.

nfd-master: correctly clean up annotations

---

docs/get-started/introduction.md
pkg/apis/nfd/v1alpha1/annotations_labels.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/e2e-test-config.example.yaml
test/e2e/node_feature_discovery_test.go

We now have metrics for getting detailed information about the NFD instances running. There should be no need to pollute the node object with NFD version annotations.
One problem with the annotations also that they were incomplete in the sense that they only covered nfd-master and nfd-worker but not nfd-topology-updater or nfd-gc.
Also, there was a problem with stale annotations, giving misleading information. E.g. there was no way to remove old/stale master.version annotations if nfd-master was scheduled on another node where it was previously running.
Fixes #1352

nfd-master: stop creating NFD version annotations

---

cmd/nfd-gc/main.go
deployment/base/gc/gc.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/deployment/metrics.md
pkg/nfd-gc/metrics.go
pkg/nfd-gc/nfd-gc.go

Implements three metrics for nfd-gc:
- `nfd_gc_build_info`: version information of nfd-gc.
- `nfd_gc_objects_deleted_total`: total number of NodeFeature and NodeResourceTopology objects deleted by nfd-gc.
- `nfd_gc_object_delete_failures_total`: number of errors encountered when deleting NodeFeature and NodeResourceTopology objects.

nfd-gc: add metrics

---

docs/deployment/metrics.md
examples/grafana-dashboard.json

Example visualization for all metrics except
nfd_node_update_requests_total which counts the deprecated (and disabled-by-default) gRPC requests.
Fixes #1381

examples: add example grafana dashboard

---

pkg/nfd-master/node-updater-pool.go
test/e2e/gomega.go
test/e2e/node_feature_discovery_test.go

This patch addresses issues with slow node status (extended resources) updates. Previously we did just a few retries in quick succession which could result in the node update failing, just because node status was updated slower than our retry window. The patch mitigates the issue by increasing the number of tries to 15. In addition, it creates a ratelimiter with a longer per-item (per-node) base delay.
The patch also fixes the e2e-tests to expose the issue.

nfd-master: fix retry of node updates

---

test/e2e/gomega.go
test/e2e/node_feature_discovery_test.go

Now that the hard-to-predict version annotations are gone we can do
strict validation of nfd-generated node annotations.
The PR also contains another patch that drops the now unused ignoreUnexpected arg from custom gomega matcher.

test/e2e: stricter validation of node annotations

---

deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
docs/get-started/introduction.md
docs/usage/customization-guide.md
pkg/apis/nfd/v1alpha1/annotations_labels.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/types.go
pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/data/nodefeaturerule-5.yaml
test/e2e/node_feature_discovery_test.go

Discover node features as annotations

---

test/e2e/node_feature_discovery_test.go

Delete NFD-managed feature annotations at test setup and teardown

test/e2e: cleanup feature annotations

---

docs/usage/customization-guide.md
docs/usage/features.md

First, fix a typo s/sex/sev/. Second, these features are not advertised as node labels but only as "raw" features available for consumption in NodeFeatureRules.

docs: fix documentation on SEV security features

---

docs/usage/customization-guide.md
docs/usage/features.md

First, fix a typo s/sex/sev/. Second, these features are not advertised as node labels but only as "raw" features available for consumption in NodeFeatureRules.
(cherry picked from commit 14d26f2c476b487f7606abb045cc9ee04e87b0bb)
Backports #1447

[release-0.14] docs: fix documentation on SEV security features

---

docs/usage/customization-guide.md

(cherry picked from commit d9b4d9bbd60f76b96345072bdc13f02e4304bf83)
Backports #1449

[release-0.14] docs: use correct storage.block name for block device feature

---

source/network/network.go

Make the function more generic and re-usable.

source/network: refactor readIfaceInfo

---

go.mod
go.sum

Let's update the cpuid to v2.2.6 release, released on November 6th 2023, as it brings information about TDX Guests virtualised atop of Hyper-V.
cpuid's changelog:
```
v2.2.6 (Latest)
What's Changed
* Add Intel apx, avx10, keylocker by @klauspost in #134
* Update README.md by @klauspost in #136
* Detect TDX Guest when it's virtualised using Hyper-V by @fidencio in #138
```

go.mod: Update cpuid to its v2.2.6 release

---

pkg/apis/nfd/v1alpha1/expression.go

This patch updates the comments to correspond to the actual behavior which was changed back in 36341bf4c70971cd7c76ebb63e7a494bb5c4f3fd.

apis/nfd: fix incorrect comments of matching functions

---

test/e2e/gomega.go
test/e2e/node_feature_discovery_test.go

In some occasions the node status (capacity) takes a lot of time to update. Increase the timeout on extended resource tests. Revert the default timeout back to 10s.

test/e2e: increase timeout for waiting node status

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Remove some stale variables that were leftover from the recent removal of nfd version annotations.

nfd-master: drop stale variables

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
test/e2e/data/nodefeature-1.yaml

Make the handling of unprefixed names (of labels, annotations and
extended resources) well-defined and predictable. Previously the
resulting output was not predictable in case the same name was coming in
both the unprefixed and prefixed form, say unprefixed `foo=bar` coming from
one source (be it nfd-worker or NodeFeature(Rule)) and
`feature.node.kubernetes.io/foo=baz` from a NodeFeature(Rule).
Previously the output value was randomly either `bar` or `baz`.
This patch adds prefixes to all names early in the processing
"pipeline", preventing random name clashes later on.

nfd-master: predictable handling of unprefixed names

---

deployment/components/master-config/nfd-master.conf.example
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-configuration-reference.md
docs/usage/customization-guide.md
examples/nodefeaturerule.yaml
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go

Add new `autoDefaultNs` (default is `true`) config option to nfd-master.
Setting the config option to false stops NFD from automatically adding
the `feature.node.kubernetes.io` prefix to labels, annotations and
extended resources. Taints are not affected as for them no prefix is
automatically added. The user-visible part of enabling the option change
is that NodeFeatureRules, local feature files, hooks and configuration
of the "custom" may need to be altereda (if the auto-prefixing is
relied on).
For now, the config option defaults to `true`, meaning no change in
default behavior. However, the intent is to change the default to
`false` in a future release, deprecating the option and eventually
removing it (forcing it to `false`).
The goal of stopping doing "auto-prefixing" is to simplify …

Option to stop implicitly adding default prefix to names

---

pkg/apis/nfd/v1alpha1/expression_test.go

The "better way" of running test cases, get e.g. better output in case of errors.
Also drop some unneeded type definitions from the tests.

Use T.Run in expression unit tests

---

docs/deployment/tls.md

Point to latest version of cert-manager. Let's keep this up-to-date even if TLS support is deprecated and going away.

docs/tls: update cert-manager deployment instructions

---

docs/deployment/helm.md
docs/deployment/kustomize.md
docs/deployment/operator.md

The "minimal" image variant has been the default since v0.13.

docs: remove outdated instructions for minimal image

---

docs/usage/customization-guide.md
source/network/network.go

feat: discover virtual network interface

---

deployment/components/common/env.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
pkg/nfd-worker/nfd-worker.go

This patch creates a owner-dependent relationship between the nfd-worker pod and the NodeFeature object that it creates. With this change the orphaned NodeFeature object(s) gets automatically garbage-collected when the nfd-worker pod goes away, without the need for manual clean-up actions.

nfd-worker: set owner reference in NodeFeature objects

---

Makefile

Makefile: more verbose output for e2e-tests

---

Makefile

Fix syntax error in the shell code. Also enable verbosity to print out the shell script being run.

Makefile: fix e2e-testing of the full image

---

pkg/nfd-master/nfd-master.go

These are now handled by the validate package. If we have them here in nfd-master, the default namespace (feature.node.kubernetes.io) gets denied.

nfd-master: remove default denied ns from config

---

go.mod
test/e2e/gomega.go

The maps package became available as a standard non-experimental package in Go 1.21.

Use non-exp maps package

---

deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
pkg/apis/nfd/v1alpha1/expression.go
pkg/apis/nfd/v1alpha1/expression_test.go
pkg/apis/nfd/v1alpha1/rule_test.go
pkg/apis/nfd/v1alpha1/types.go
source/custom/static_features.go

Drop the creation helper functions as one step in an effort to tidy up the api package. These functions were not much used outside unit tests anyway, the static rules of the nfd-worker custom feature source being the only exception (and if those happened to be invalid we'd catch that e.g. in the e2e-tests).

apis/nfd: drop creation helper functions

---

deployment/base/nfd-crds/cr-sample.yaml
deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/usage/customization-guide.md
pkg/apis/nfd/v1alpha1/expression.go
pkg/apis/nfd/v1alpha1/rule.go
pkg/apis/nfd/v1alpha1/rule_test.go
pkg/apis/nfd/v1alpha1/types.go
pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
samples/nodefeaturerule-cpu.yaml
samples/nodefeaturerule-custom.yaml
samples/nodefeaturerule-kernel.yaml
samples/nodefeaturerule-local.yaml
samples/nodefeaturerule-memory.yaml
samples/nodefeaturerule-network.yaml
samples/nodefeaturerule-pci.yaml
samples/nodefeaturerule-storage.yaml
samples/nodefeaturerule-system.yaml
samples/nodefeaturerule-usb.yaml
source/custom/static_features.go
test/e2e/data/nodefeaturerule-1.yaml
test/e2e/data/nodefeaturerule-2.yaml
test/e2e/node_feature_discovery_test.go

Extend the format of feature matcher terms (the elements of the
arrayspecified under under matchFeatures field) with new matchName
field. The value of this field is an expression that is evaluated
against the names of feature elements instead of their values (values
are matched with the matchExpressions field, instead).
The matchName field is useful e.g. in template rules for creating
per-feature-element labels based on feature names (instead of values)
and in non-template rules for checking if (at least) one of certain
feature element names are present.
If both matchExpressions and matchName for certain feature matcher term
is specified, they both must match in order to get an overall match.
Also, in this case the list of matched features (used in templating) is
the union of the results …

apis/nfd: add matchName field in feature matcher terms

---

docs/usage/customization-guide.md
source/cpu/cpu.go

feat: add cpu socket count in `cpu.topology`

---

pkg/nfd-worker/nfd-worker.go

Address the following warning error message:
> I1218 10:06:33.826912       1 nfd-worker.go:626] "ignoring label with invalide value" labelKey="nvidia.com/gpu.machine" labelValue="..." errors=["a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"]

chore(nfd-worker): fix minor typo in wrong label value format error

---

docs/usage/features.md

Document the Intel APX and AVX10 features that were added with cpuid v2.2.6.

docs: document new x86 cpuid features

---

Makefile
cmd/kubectl-nfd/main.go
cmd/kubectl-nfd/subcmd/dryrun.go
cmd/kubectl-nfd/subcmd/root.go
cmd/kubectl-nfd/subcmd/test.go
cmd/kubectl-nfd/subcmd/validate.go
docs/reference/plugin-commandline-reference.md
docs/reference/versions.md
docs/usage/kubectl-plugin.md
examples/nodefeature.yaml
examples/nodefeaturerule.yaml
go.mod
pkg/apis/nfd/validate/validate.go
pkg/kubectl-nfd/dryrun.go
pkg/kubectl-nfd/test.go
pkg/kubectl-nfd/validate.go

Fixes #1384 
This initial implementation of `kubectl-nfd` adds 3 verification cases:
- Validate a NodeFeatureRule file 
- Run a NodeFeatureRule against a local NodeFeature file
- Run a NodeFeatureRule against a cluster

Add Kubectl NFD plugin 

---

Makefile

Fixes recently experienced timeouts in e2e-tests. For some reason -test.timeout was not enough (anymore).

Makefile: add -timeout argument to e2e-tests

---

deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
docs/deployment/helm.md
docs/deployment/uninstallation.md

This patch adds a post-delete hook to the Helm chart that runs "nfd-master --prune" in the cluster. This cleans up the node of labels, annotations, taints and extended resources that were created by NFD.

helm: add post-delete hook that cleans up the node

---

cmd/nfd-master/main.go
deployment/base/master/master-deployment.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
pkg/nfd-master/nfd-master.go

This patch separates the gRPC health server from the deprecated gRPC server (disabled by default, replaced by the NodeFeature CRD API) used for node labeling requests. The new health server runs on hardcoded TCP port number 8082.
The main motivation for this change is to make the Kubernetes' built-in gRPC liveness probes to function if TLS is enabled (as they don't support TLS).
The health server itself is a naive implementation (as it was before), basically only checking that nfd-master has started and hasn't crashed. The patch adds a TODO note to improve the functionality.
Fixes: #1533

nfd-master: run a separate gRPC health server

---

hack/generate.sh

Temporary (hopefully) fix for deepcopy functions that code-generator doesn't get quite right.

hack/generate: patch auto-generated deepcopy functions

---

pkg/nfd-topology-updater/nfd-topology-updater.go

We need to parse kubeconfig (and initialize the apihelper) even with -no-publish as the PodResourcesScanner accesses the k8s API even if we're not publishing/updating NRTs.

topology-updater: initialize properly with -no-publish

---

pkg/apihelper/k8shelpers.go
pkg/nfd-gc/nfd-gc.go
pkg/nfd-master/nfd-master.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/kubernetes.go

This change is part of an effort to remove the pkg/apihelper package. GetKubeconfig is useful helper functionality shared accross the codebase so move it into a "safe" location.
Split out from #1561

pkg/utils: move GetKubeconfig from pkg/apihelper here

---

deployment/helm/node-feature-discovery/templates/nfd-topologyupdater-conf.yaml

Only deploy the topology-updater config if topology-updater itself (the daemon) is deployed.

deployment/helm: don't deploy topology-updater conf unnecessarily

---

pkg/apihelper/apihelpers.go
pkg/apihelper/k8shelpers.go
pkg/apihelper/mock_APIHelpers.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool_test.go
pkg/utils/jsonpatch.go
test/e2e/node_feature_discovery_test.go

Part of the effort of dropping apihelper package (#1561)

pkg/utils: move JsonPatch from pkg/apihelper

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool_test.go

Implement some of frequently used helper functions inpackage.
This patch also contains big changes to the nfd-master unit tests. Much of this is about migrating from the mocked apihelper interface to fake kubernetes client that provides a bit more apiserver'ish functionality. At the same time there is quite a bit of renaming in the tests, shortening and unifying naming and getting rid of the extensive usage of "mock" everywhere.
This is the last self-contained piece to split out from #1561

nfd-master: ditch apihelper

---

pkg/nfd-master/nfd-master.go

Correctly patch the "status" subresource. This got broken when refactoring the code in 7a050e7cf9c2e8f21c2f3ddda0a9745a45de472c and wasn't even catched by the unit tests as the fake kubernetes client doesn't handle subresources as the real apiserver does.

nfd-master: fix node status patching

---

go.mod
go.sum

[release-0.15] go.mod: bump github.com/opencontainers/runc to v1.1.12

---

go.mod
go.sum

[release-0.14] go.mod: bump github.com/opencontainers/runc to v1.1.12

---

docs/usage/customization-guide.md
examples/nodefeature.yaml
source/system/system.go

Add reading vendor information from /sys/devices/virtual/dmi/id/sys_vendor
Closes #1057

source/system: Add reading vendor information

---

pkg/apis/nfd/validate/validate.go
pkg/apis/nfd/validate/validate_test.go

This also fixes test cases that were not working properly.

apis/nfd/validate: use testify/assert for checking test results

---

cmd/nfd-master/main.go
docs/reference/master-commandline-reference.md

Plan the removal of the -crd-controller flag along with the gRPC API. This flag does not make much sense after that as all communication with nfd-worker is based on CRDs - with the CRD controller disabled nfd-master is virtually a functionless stub.

nfd-master: mark the -crd-controller flag as deprecated

---

pkg/nfd-master/nfd-api-controller.go

Fixes a memory leak that happened when stopping (and then re-starting) the nfd api controller. The stop channel was not used properly which caused the underlying informer to keep on running.

nfd-master: fix memory leak in nfd api-controller

---

go.mod
go.sum

Bump google.golang.org/protobuf to 1.33.0 and
github.com/golang/protobuf to v1.5.4
Backports #1613

[release-0.14] go.mod: bump protobuf deps

---

go.mod
go.sum

Bump google.golang.org/protobuf to 1.33.0 and
github.com/golang/protobuf to v1.5.4
Backports #1613

[release-0.15] go.mod: bump protobuf deps

---

deployment/components/common/worker-mounts.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
docs/usage/customization-guide.md
docs/usage/features.md
pkg/utils/hostpath/hostpath.go
source/memory/memory.go
source/memory/memory_test.go
source/memory/testdata/noswap
source/memory/testdata/swap

add swap support in nfd

---

deployment/base/rbac-topologyupdater/topologyupdater-clusterrole.yaml
deployment/helm/node-feature-discovery/templates/clusterrole.yaml
pkg/nfd-topology-updater/nfd-topology-updater.go
test/e2e/topology_updater_test.go
test/e2e/utils/rbac.go

Add owner reference to NRT object

---

pkg/nfd-topology-updater/nfd-topology-updater.go

APIVersion and Kind are empty in the returned namespace object and need to be set explicitly.

topology-updater: Set APIVersion, Kind in the OwnerReference explicitly

---

pkg/nfd-master/nfd-api-controller.go

Prevents (rare) races on nfd-master reconfigurartion. Previously the scheme was registered at nfd API controller creation/startup time. This caused a race with some lister/informer goroutines of the previous (stoppped) controller still running and accessing (reading) the sceme while we were updating (writing) it.

nfd-master: do nfd API scheme registration in an init function

---

cmd/nfd-topology-updater/main.go
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/values.yaml
pkg/nfd-topology-updater/nfd-topology-updater.go

nfd-topology-updater: Add liveness probe

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

Prevent excess queries of node objects from the Kubernetes apiserver. This significantly speeds up node updates (and reduces the load on the apiserver) as the client-side throttling (which is good) does not bite us that hard.

nfd-master: get node object only once when updating node

---

deployment/helm/node-feature-discovery/templates/prometheus.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

chore/deploy: make interval property in PodMonitor configurable

---

pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

Prevents races when (re-)starting the queue. There are no reports on issues related to this (and I haven't come up with any actual failure path in the current code) but better to be safe and follow the best practices.

nfd-master: protect node updater pool queueing with a lock

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/utils/flags.go

Change the handling of LabelWhiteList config option to use a pointer to detect when the option is unset. This doesn't fix any detected crash but is merely general improvement and stabilization, serving easier testing.
Also, use the regexp type from the core libs for the config struct - dropping the unmasrhalling code for our custom regexp type - as the core regexp now implements unmarshaller itself.

nfd-master: prevent crash on empty config struct

---

pkg/nfd-gc/nfd-gc_test.go
pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-worker/nfd-worker.go

This started as a small effort to simplify the usage of "ready" channel in nfd-master. It extended into a wider simplification/unification of the channel usage.

Tidy up usage of channels for signaling

---

cmd/nfd-master/main.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/nfd-master_test.go
pkg/nfd-master/node-updater-pool_test.go
pkg/nfd-worker/nfd-worker_test.go

This provides a more controlled way for setting up the NfdMaster instance for testing.

nfd-master: implement opts for modifying NfdMaster instance

---

api/nfd/v1alpha1/annotations_labels.go
pkg/apis/nfd/validate/validate.go
pkg/apis/nfd/validate/validate_test.go

Don't require that the annotation value must conform to the (strict)
requirements of label values. In the Kubernetes API annotation values do
not have other restrictions than that the total size (keys and values)
of _all_ annotations combined of an object must not exceed 256kB.
This patch sets a maximum size limit of 1kB for the value of a single
feature annotation created by NFD. This limit is rather arbitrary but
should be enough for the NFD usage scenarios (until proven wrong).
Also add license header to the test.go file and fix one bug in
MatchFeature validation.

apis/nfd/validate: loosen validation of feature annotations

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

Sharing the same client between updater threads virtually serializes access, in practice making the effective parallelism close to 1.
With this patch, in my bench cluster of 300 nodes, the time taken by updating all nodes drops from ~2 minutes to ~12 seconds (with the default parallelism of 10 node updater threads). This demonstrates the 10-fold increased parallelism from ~1 to 10.
There might be other solutions that could be explored, e.g. caching nodes with an indexer/lister but otoh nfd doesn't necessarily need/want to watch every little change in each node. We only need to get the node when something in our own CRDs change (we don't react to any changes in the node object itself). Using multiple clients was the most obvious choice to solve the problem for now.

nfd-master: use separate k8s api clients for each updater

---

pkg/apis/nfd/nodefeaturerule/expression-api_test.go
pkg/apis/nfd/nodefeaturerule/expression.go
pkg/apis/nfd/nodefeaturerule/expression_test.go

Return false (i.e. "did not match") but no error when evaluating a match expression against a "flag" type feature (which don't have any associated value, just the name) if a MatchOp that never matches is used.
This is preparation for supporting multi-type features, i.e. one feature, like "cpu.cpuid", having e.g. "flag" and "attribute" type features.

apis/nfd: no error on ops that never match

---

Makefile
scripts/test-infra/build-image-cross.sh

this allows the nfd to run on arm devices like the Raspberry Pi >= 2 
with ARMv7 core or ARMv8 in 32Bit mode
see #426

add ARMv7 support

---

cloudbuild.yaml

Mitigate the big increase of build time after enabling armv7 builds.

cloudbuild.yaml: change machine type to e1-highcpu-32

---

cloudbuild.yaml

The higher tier builder didn't give any advantage, especially after armv7 builds were disabled. Let's revert back to highcpu-8.

cloudbuild.yaml: downgrade machine type to e2-highcpu-8

---

pkg/apis/nfd/nodefeaturerule/expression-api_test.go

Cover error cases of the "match name" functions.

apis/nfd: increase unit test coverage

---

Makefile
hack/init-buildx.sh

Fixes scenarios where there are other builders, too.

build: specify buildx builder name everywhere

---

source/kernel/selinux.go

Silence a irrelevant error that was printed in case /sys/fs/selinux/ directory exists but selinuxfs is not mounted (i.e. the dir is empty).

source/kernel: silence misleading error on selinux detection

---

docs/reference/feature-gates.md
docs/reference/master-configuration-reference.md
pkg/features/features.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Now that we have support for feature gates deprecate the autoDefaultNs
config option of nfd-master and replace it with a new alpha feature gate
DisableAutoPrefix (defaults to false). Using a feature gate to handle
and communicate these kind of changes, where the default behavior is
intended to be changed in a future release, feels much more natural than
using random flags/options.
The combined logic of the feature gate and the config option is a
logical OR over disabling auto-prefixing. That is, auto-prefixing is
disabled if either the feature gate or the config options is used set to
disable it:
```
| DisableAutoPrefix (feature gate)
| false | true
-------------------- | --------------------------------
autoDefaultNs   true |  ON   | OFF
(config opt)   false |  OFF  | OFF
```

nfd-master: add DisableAutoPrefix feature gate

---

pkg/nfd-worker/nfd-worker.go

Don't log an empty NodeFeature object.

nfd-worker: improved log when creating NodeFeature object

---

deployment/nodefeaturerule/samples/nodefeaturerule-cpu.yaml
docs/usage/customization-guide.md
docs/usage/features.md
source/cpu/cpu.go
source/cpu/cpuid_amd64.go
source/cpu/cpuid_linux_arm.go
source/cpu/cpuid_linux_arm64.go
source/cpu/cpuid_linux_ppc64le.go
source/cpu/cpuid_linux_s390x.go
source/cpu/cpuid_stub.go

Add new cpuid label "feature.node.kubernetes.io/cpu-cpuid.AVX10_VERSION" that advertises the supported version of AVX10 vector ISA. Correspondingly, the patch adds AVX10_VERSION to the "cpu.cpuid" feature for NodeFeatureRules to consume.
This makes cpu.cpuid on amd64 architecture a "multi-type" feature in that it contains "flags" and potentially also "attributes" (the only cpuid attribute so far is the AVX10_VERSION).

cpu: advertise AVX10 version

---

.github/workflows/gh-pages.yml

Checkout v4 does some strange mangling of tags, basically overwrites our signed/annotated tag with something like:
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune \
--no-recurse-submodules origin \
+2e93c3fd478b6631dd7bda9c6ec66a9f99cafaa8:refs/tags/v0.16.0
Which breaks our gh-pages build on release branches/tags.
This reverts commit 130ef1070d4f90e2a44959a68a576ef11ad93c4f.

Revert "build(deps): bump actions/checkout from 1 to 4"

---

cmd/nfd-topology-updater/main.go

Fix the usage of IPv6 addresses for default kubelet configz endpoint.
The default host:port we use for kubelet configz endpoint is ${NODE_ADDRESS}:10250. Previously we errored out if NODE_ADDRESS was an IPv6 address because we used an incorrect notation (without brackets). The (IPv6) needs to be enclosed in brackets if specifying the port.
Fixes #1727

topology-updater: properly handle IPv6 from NODE_ADDRESS

---

pkg/nfd-master/nfd-api-controller.go

We faced the problem when master deleted some of labels on start. Sometimes he doesn't gets NodeFeatures when they are present in cluster because of empty cache in informer

Fix the problem with starting the master with empty cache

---

deployment/helm/node-feature-discovery/templates/post-delete-job.yaml

The Service account name must match the referenced service account in the job spec
With helm chart as-is, the gpu-operator e2e tests fail as the `helm uninstall` operation fails and times out. On further analysis, we found that the delete hook job can't find the service account it looks for, so the job remains unprovisioned until the helm uninstall times out
This change fixes the above issue. I've tested this locally and our gpu-operator e2e tests now pass

ensure post-delete-job's service account matches ref in job spec

---

docs/usage/features.md

Update to klauspost/cpuid to v2.2.7

Document AVXVNNIINT16 cpuid feature

---

scripts/test-infra/test-e2e-presubmit.sh

scripts: refresh e2e-presubmit test script

---

docs/deployment/index.md
docs/deployment/kustomize.md
docs/developer-guide/index.md
docs/get-started/introduction.md
docs/reference/versions.md

Bump the required Kubernetes version to v1.24. In practice this is the
minimum Kubernetes version as our deployment (both kustomize and Helm)
depend on the gRPC container probes feature of Kubernetes.

docs: describe Kubernetes version compatibility in versions page

---

cloudbuild.yaml
scripts/test-infra/test-e2e.sh

Attempt to fix occasional (rare) build failures.

cloudbuild: increase the image build timeout

---

pkg/nfd-worker/nfd-worker.go
pkg/nfd-worker/nfd-worker_test.go

Run nfd-worker with NodeFeature API enabled (against a fake apiserver) instead of using the deprecated gRPC (against a nfd-master instance).
Expand the test to verify the features and labels that are advertised as a NodeFeature object.
Refs #1546

nfd-worker: change TestRun to use NodeFeature API

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Fixes: #1759 
Tested locally. Output:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name:  release-name-node-feature-discovery-master
namespace: default
labels:
helm.sh/chart: node-feature-discovery-0.2.1
app.kubernetes.io/name: node-feature-discovery
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "master"
app.kubernetes.io/managed-by: Helm
role: master
spec:
replicas: 1
revisionHistoryLimit: 3
selector:
matchLabels:
app.kubernetes.io/name: node-feature-discovery
app.kubernetes.io/instance: release-name
role: master
template:
metadata:
labels:
app.kubernetes.io/name: node-feature-discovery
app.kubernetes.io/instance: release-name
role: master
spec:
serviceAccountName: release-name-node-feature-discovery
enableServiceLinks: false
securityContext:
{} …
```

Helm: Add revision history limit for master replica

---

test/e2e/topology_updater_test.go

Attempt to eliminate flakiness in CI.

test/e2e: set topology-updater sleep-interval in podfingerprint test

---

test/e2e/topology_updater_test.go

Make the test finish considerably faster.

test/e2e: specify -sleep-interval in topology-updater exclude-memory test

---

docs/reference/feature-gates.md
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
docs/reference/worker-commandline-reference.md
docs/usage/customization-guide.md
docs/usage/nfd-gc.md
docs/usage/nfd-master.md
pkg/features/features.go
pkg/nfd-worker/nfd-worker_test.go
test/e2e/node_feature_discovery_test.go

The feature gate is locked to true. That is, it is not possible to revert back to the gPRC-based communication which makes the gRPC API ready for removal.

feature-gates: mark NodeFeatureAPI as GA

---

deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

#1782 added support for setting revision history limit for master and gc replicas. This PR adds the same for worker replicas.
Fix #1759

Helm: Add revision history limit for worker daemonset

---

deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

* Helm: Add revision history limit for worker daemonset
Signed-off-by: Rouke Broersma <mobrockers@gmail.com>
* Helm: Add revision history limit for topology updater daemonset
Signed-off-by: Rouke Broersma <mobrockers@gmail.com>
* chore: tidy table columns
---------
Signed-off-by: Rouke Broersma <mobrockers@gmail.com>
(cherry picked from commit 1230d607aca6f708b0f09b59ae180fdf066fc45f)

[release-0.16] Helm: Add revision history limit for worker daemonset (#1797)

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Fixes: #1730
The following values.yaml:
```yaml
master:
enable: true
args: []
config: ### <NFD-MASTER-CONF-START-DO-NOT-REMOVE>
port: 8080
metricsPort: 8081
instance:
featureApi:
resyncPeriod:
denyLabelNs: []
extraLabelNs: []
resourceLabels: []
enableTaints: false
crdController: null
featureRulesController: null
nfdApiParallelism: null
deploymentAnnotations: {}
replicaCount: 1
podSecurityContext: {}
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop: [ "ALL" ]
readOnlyRootFilesystem: true
runAsNonRoot: true
serviceAccount:
create: true
annotations: {}
name:
revisionHistoryLimit:
rbac:
create: true
service:
type: ClusterIP
port: 8080
resources:
limits:
memory: 4Gi
requests:
cpu: 100m
memory: 128Mi
nodeSelector: {}
tolerations:
- key: "node-role.kubernetes.io/master" …
```

helm: add configurable liveness&readiness probes for master topology-updater and worker

---

pkg/nfd-master/nfd-api-controller.go

Bail out if there were errors in syncing the cache of any resource.

nfd-master: check nfd api informer cache sync result

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Add configurable liveness&readiness probes for master topology-updater and worker.
Signed-off-by: Omer Aplatony <omerap12@gmail.com>
(cherry picked from commit b2222e2c8c821d11aa7303b13e66535f0865a8b4)

[release-0.16] helm: add configurable liveness&readiness probes

---

pkg/nfd-master/nfd-api-controller.go

Fix cache syncing problems on big clusters with thousands of NodeFeature objects.
On the initial list (sync) the client-go cache reflector sets the ResourceVersion to "0" (instead of leaving it empty). This causes problems in the api server with (apiserver) logs like:
```
E writers.go:122] apiserver was unable to write a JSON response: http:
Handler timeout
E status.go:71] apiserver received an error that is not an
metav1.Status: &errors.errorString{s:"http: Handler timeout"}:
http: Handler timeout
```
On the nfd-master side we see corresponding log snippets like:
```
W reflector.go:547] failed to list *v1alpha1.NodeFeature: stream error
when reading response body, may be caused by closed
connection. Please retry. Original error: stream
error: stream ID 1521; INTERNAL_ERROR; received from …
```

nfd-master: tweak list options for NodeFeature informer

---

pkg/nfd-gc/nfd-gc.go

List NodeFeature and NodeResourceTopology objects in pages of 200 items. This reduces memory consumption and eliminates timeouts (on the apiserver side) in big clusters of thousands of nodes.

nfd-gc: use paging when listing CRs

---

Makefile
docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
netlify.toml

The upstream repo (and the release downloads)
github.com/rundocs/jekyll-rtd-theme has been deleted. This broke our docs generation as the remote theme configuration depended on downloading the release artefact.
This patch changes the docs building to use a Ruby gem instead of the remote theme setting. To complicate matters, the gem has an seemingly incorrect (too strict) version dependency. To mitigate this, we now install bundler-override plugin to ignore this particular dependency.

docs: use jekyll-rtd-theme from a ruby gem

---

Tiltfile

Sync up builder go version with project go.mod otherwise build will fail. 
Also, add `allow_k8s_contexts('kubernetes-admin@kubernetes')` to allow tilt to run on production like clusters.

tilt: sync up builder go version with project go.mod

---

pkg/nfd-master/nfd-api-controller.go

There's no reason why the "update all" chans should be buffered (while the other are not).

nfd-master: use only unbuffered chans in the nfd api-controller

---

pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master.go

Stop blocking on event channels when the api controller is stopped.
Ensures that the nfd API informer factory is properly shut down and all
resources released when stop() is called. This eliminates a memory leak
on re-configure events when leader election is enabled.
Fixes: #1841

nfd-master: proper shutdown of nfd api informers

---

pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master.go

Stop blocking on event channels when the api controller is stopped. Ensures that the nfd API informer factory is properly shut down and all resources released when stop() is called. This eliminates a memory leak on re-configure events when leader election is enabled.
(cherry picked from commit 2bb8a725321adce8b8b97203b54ee40a0ea9b96d)
Backports #1848

[release-0.16] nfd-master: proper shutdown of nfd api informers

---

deployment/components/master-config/kustomization.yaml
deployment/components/topology-updater-config/kustomization.yaml
deployment/components/worker-config/kustomization.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
docs/reference/worker-configuration-reference.md
docs/usage/nfd-master.md
docs/usage/nfd-topology-updater.md
docs/usage/nfd-worker.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go
test/e2e/node_feature_discovery_test.go

Simplify the code and reduce possible error scenarios by dropping fsnotify-based reconfiguration from nfd-master and nfd-worker. Also eliminates repeated re-configuration in scenarios where kubelet continuosly touches the (every minute) mounted file (configmap) on the filesystem.
Also modifies the Helm and kustomize deployments so that nfd-master, nfd-worker and nfd-topology-updater pods are restarted on configmap updates. In kustomize, the slght downside of this is the name of the config map(s) depends on the content, so every time a user customizes the config data, the old unused configmap will be left and must be garbage-collected manually.
Fixes #1846

Drop dynamic run-time reconfiguration

---

Makefile
Tiltfile
go.mod

NOTE: api/nfd/go.mod is not bumped. There should be no need to force the importers of the API to v1.23 (yet).

Bump Go to v1.23

---

source/network/network.go

On Talos OS NFD logs constantly show errors related to the network attributes of bonding_masters.
Closes #1842

source/network: Ignore bonding_masters interface during scanning

---

.github/workflows/gh-pages.yml
.github/workflows/release.yml

Update gh-pages has started failing with default permissions. It needs write permissions to be able to push to the gh-pages branch.

github: specify workflow permissions

---

charts/index.yaml

Manual update to work around insufficient permissions in the github workflow.

[gh-pages] Update Helm repo index for release v0.16.5

---

testdata/README.md
testdata/go.mod

This ensures that the testdata folder is not included in the top-level module and prevents issues such as unsupported characters in path names.
See also https://github.com/openshift/oc-mirror/pull/669

Convert testdata to an empty go module

---

docs/developer-guide/index.md

The issue is due to the k3d/kind cluster created by ctlptl will run inside containers(it will serve as the virtual hosts).
Host folders which will be scaned by the nfd feature discovery should be mounted into the container ( the virtual host). otherwise the nfd-worker container which run inside the virtual host will just see the default base image rootfs /boot, /lib folders, which are usually empty, leads to the discovey failure.

Doc: Fix tilt up issue in feature discovering in developer guide

---

go.mod
go.sum

go.mod: bump cpuid to [v2.2.9](https://github.com/klauspost/cpuid/releases/tag/v2.2.9)

go.mod: bump cpuid to v2.2.9

---

docs/deployment/metrics.md
examples/grafana-dashboard.json
pkg/nfd-gc/metrics.go
pkg/nfd-master/metrics.go
pkg/nfd-topology-updater/metrics.go
pkg/nfd-worker/metrics.go

For different components in the same project, metrics should be distinguished by different system prefixes.

chore: add metrics system prefix

---

docs/reference/master-commandline-reference.md
docs/reference/worker-commandline-reference.md

The link to feature gates documentation is pointing to the feature-gates.md in master-commandline-reference.html and worker-commandline-reference.html, it should be updated to linking html file.
Signed-off-by: joehuang <joehuang.sweden@gmail.com>
(cherry picked from commit a442749f89b9db2791b6c8eb5010f2b7753efed1)
Backports: #1821 
Fixes: #1971

Docs: Fix the link to feature gates documentation

---

enhancements/1845-nfd-image-compatibility/README.md

Proposal to describe image requirements by using NFD labels and OCI artifact.

NFD image compatibility proposal

---

scripts/github/update-gh-pages.sh

When determining the release branch only consider "main" release tags, refusing to pick api/nfd/v* tags.

scripts/update-gh-pages: fix release version parsing

---

pkg/nfd-master/namespace-lister.go
pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-api-controller_test.go

Mitigate the namespace cache sync reported in issue #1936

nfd-master: check that namespace informer cache sync succeeded

---

cmd/nfd-gc/main.go
cmd/nfd-master/main.go
cmd/nfd-topology-updater/main.go
cmd/nfd-worker/main.go
scripts/github/update-gh-pages.sh
scripts/test-infra/test-e2e-presubmit.sh

The fix in a416af51a48d5d49cc0f17b069b3fc6e8566bedd was not enough by itself and that needs to be applied comprehensively.

Fix version parsing

---

Makefile

One bit that was accidentally left out from
047d0314aa91c7e81a87914789e75b97b330ed5e

Makefile: fix version parsing

---

cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
deployment/components/worker-config/nfd-worker.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/worker-commandline-reference.md
docs/reference/worker-configuration-reference.md
pkg/nfd-worker/nfd-worker.go

In some cases it's desirable to control automatic garbage collection of NodeFeature object.
Add an option to disable setting the owner references to Pod for NodeFeature object.
Closes: #1817

nfd-worker: Add an option to disable setting the owner references

---

deployment/base/rbac/worker-role.yaml
deployment/helm/node-feature-discovery/templates/role.yaml
pkg/nfd-worker/nfd-worker.go
test/e2e/utils/rbac.go

when OwnerReferencesPermissionEnforcement validating webhook is
enabled additional permissions are required to set/update owner ref
field. NFD worker sets/updates NodeFeature owner ref field to
the worker pod and owning daemonset.
owner reference can only be updated if the worker has delete permissions
for NodeFeatures.
if owner reference has blockOwnerDeletion (as the case for the daemonset
owner reference) then it requires update permissions to the finalizers
of the owner, to avoid this, we set blockOwnerDeleteion to false for all
owners referenced from NFD worker pod when setting/updating NodeFeature
owner ref.
more info on [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement)

Add support running with OwnerReferencesPermissionEnforcement

---

deployment/base/rbac/worker-role.yaml
deployment/helm/node-feature-discovery/templates/role.yaml
pkg/nfd-worker/nfd-worker.go
test/e2e/utils/rbac.go

when OwnerReferencesPermissionEnforcement validating webhook is enabled additional permissions are required to set/update owner ref field. NFD worker sets/updates NodeFeature owner ref field to the worker pod and owning daemonset.
owner reference can only be updated if the worker has delete permissions for NodeFeatures.
if owner reference has blockOwnerDeletion (as the case for the daemonset owner reference) then it requires update permissions to the finalizers of the owner, to avoid this, we set blockOwnerDeleteion to false for all owners referenced from NFD worker pod when setting/updating NodeFeature owner ref.
Signed-off-by: adrianc <adrianc@nvidia.com>
(cherry picked from commit 3f012c2d5a140bd80abf128f9d7d45ee988c0794)
Backports: #2006

[release-0.16] Add support running with OwnerReferencesPermissionEnforcement

---

pkg/apis/nfd/nodefeaturerule/rule.go
pkg/client-nfd/compat/artifact-client/client.go
pkg/client-nfd/compat/node-validator/node-validator.go
pkg/client-nfd/compat/node-validator/node-validator_test.go

Bugfixes:
* Always pull the latest compatibility artifact
* Handle missing compatibility matches to avoid panic
* Continue procesing the rule if the feature is missing

Bugfixes for image compatibility feature

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Enable setting the dnsPolicy in pods deployed as part of the NFD helm chart.

Make DNS Policy configurable in helm chart

---

pkg/utils/jsonpatch.go
test/e2e/node_feature_discovery_test.go
test/e2e/utils/namespace/namespace.go

test: add utility for namespace labels patching and add the test cases for denyNodeFeatureLabels restriction

---

pkg/client-nfd/compat/node-validator/node-validator.go
pkg/client-nfd/compat/node-validator/node-validator_test.go

I refactored the node validator code to achieve better readability for easier maintenance / expansion.
In addition, test cases have been moved into separate functions, before in case of failure, it was hard to figure out what's wrong.

Refactoring of image compatibility node validator

---

docs/usage/customization-guide.md
go.mod
go.sum
pkg/apis/nfd/nodefeaturerule/rule.go
pkg/apis/nfd/template/template.go
pkg/apis/nfd/validate/validate.go

Use Sprig template functions and add asLabelValue function

---

deployment/components/common/master-affinity.yaml
deployment/helm/node-feature-discovery/values.yaml

Fix this warning during helm install
```bash
W0303 17:28:58.017492   44880 warnings.go:70] spec.template.spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].key: node-role.kubernetes.io/master is use "node-role.kubernetes.io/control-plane" instead
```
Cause of the Warning
•	node-role.kubernetes.io/master is deprecated.
•	Since Kubernetes v1.20, the preferred label is node-role.kubernetes.io/control-plane.
•	The warning is triggered because node-role.kubernetes.io/master is still used in your chart’s nodeAffinity rules.

Remove deprecated toleration/affinity value

---

deployment/base/master/master-deployment.yaml

Remove gRPC startup probe from master following gRPC [logging removal](https://github.com/kubernetes-sigs/node-feature-discovery/pull/2004).

Drop gRPC startup probe

---

go.mod
pkg/apis/nfd/nodefeaturerule/expression.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/flags.go
source/pci/pci.go
source/usb/usb.go

Replace [golang.org/x/exp/maps](https://pkg.go.dev/golang.org/x/exp/maps) with the standard library's [maps](https://pkg.go.dev/maps) package.

Replace golang.org/x/exp/maps with the standard library's maps package.

---

deployment/helm/node-feature-discovery/templates/post-delete-job.yaml

This is taking the work done here: https://github.com/kubernetes-sigs/node-feature-discovery/pull/1893.
Given the original author is non-responsive I am raising this in hope to get this merged faster.

Allow configuration of image pull secrets in post-delete job

---

api/image-compatibility/v1alpha1/spec.go
docs/usage/image-compatibility.md
pkg/client-nfd/compat/node-validator/node-validator.go
pkg/client-nfd/compat/node-validator/node-validator_test.go

Simplify and rationalize the compat api. Many of the fields in Rule, like Labels, Annotations or ExtendedResources are not applicable in this context.

compat/api: use GroupRule type

---

api/nfd/go.mod

One of the latest dep updates i.e. golang.org/x/net v0.36.0 requires go v1.23.0.

api: bump go to v1.23

---

Makefile
api/nfd/v1alpha1/feature_test.go

It was broken in 719c5186f6a555a9ca4389b33754781b6ab2cb56 but never caught as the unit tests were not run (after the api was moved to a separate module).
This patch also modifies the makefile to run the unit tests from api/ directory.

api/nfd: fix broken unit test

---

pkg/nfd-master/nfd-master.go

(cherry picked from commit acc94b9f7379eb9b80bc1d940de438c981dce8b8)

[release-0.16] nfd-master: skip NodeFeatureGroup informers if feature gate disabled

---

deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-configuration-reference.md
docs/usage/customization-guide.md
pkg/nfd-master/nfd-master.go

The autoDefaultNs was deprecated in NFD v0.16 and replaced by the DisableAutoPrefix feature gate.

nfd-master: drop the deprecated autoDefaultNs config option

---

pkg/nfd-master/nfd-master.go

The nfdController must never be nil now that the gRPC API has been removed.

nfd-master: cleanup nil checks

---

pkg/nfd-master/nfd-master.go

Fix a serious memory leak of non-leaders that was caused by bad chan usage. With leader election enabled, the nfdAPIUpdateHandler() was not started for non-leader instances, and thus, there was no reader for the chans that the nfdController uses to communicate what objects to update. This, in turn caused blocking in the kubernetes API informer context (trying to queue data into the chan), piling up requests on each NodeFeature update, consuming more and more memory (that would not be released unless we became the leader).
(cherry picked from commit a595439063c97fd01f7c57e9e49f2781904c8af8)

[release-0.16] nfd-master: fix memory leak when leader election is enabled

---

pkg/nfd-master/nfd-master.go

Fix a serious memory leak of non-leaders that was caused by bad chan usage. With leader election enabled, the nfdAPIUpdateHandler() was not started for non-leader instances, and thus, there was no reader for the chans that the nfdController uses to communicate what objects to update. This, in turn caused blocking in the kubernetes API informer context (trying to queue data into the chan), piling up requests on each NodeFeature update, consuming more and more memory (that would not be released unless we became the leader).
(cherry picked from commit a595439063c97fd01f7c57e9e49f2781904c8af8)

[release-0.17] nfd-master: fix memory leak when leader election is enabled

---

docs/reference/feature-gates.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

Currently, unprefixed labels are not allowed, despite the existence of the `DisableAutoPrefix` feature gate, which is intended for this purpose. This change ensures that when `DisableAutoPrefix` is set to True, the namespace addition is skipped, allowing unprefixed labels.
Fixes: https://github.com/kubernetes-sigs/node-feature-discovery/issues/2074

Enable unprefixed label setting via feature gate

---

deployment/helm/node-feature-discovery/templates/post-delete-job.yaml

This adds in some resource limits so the prune job can't run away with the system.

helm: Inherit resource limits for prune job

---

cmd/nfd-master/main.go
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/values.yaml
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
docs/usage/nfd-master.md
pkg/nfd-master/nfd-api-controller.go
pkg/nfd-master/nfd-master.go

addresses scalability and api-server load concerns for large clusters by adding configurable pagination to the informer cache of nfd-master
related to: https://github.com/kubernetes-sigs/node-feature-discovery/issues/1998

add configurable pagination to nfd-master

---

docs/reference/master-commandline-reference.md
docs/reference/topology-updater-commandline-reference.md
docs/reference/worker-commandline-reference.md

The command line reference of nfd-master, nfd-worker and nfd-topology-updater were outdated. They were documenting the already removed -metrics and missing -port completely.

docs: document -port flag

---

pkg/apis/nfd/nodefeaturerule/rule.go
pkg/client-nfd/compat/node-validator/node-validator_test.go

There is an error that mostly influenced processing of matchAny. The status of the rule was not transfered correctly.

Bugfix: NFR and NFG rules processing

---

Tiltfile

Use anonymous, ephemeral image registry [ttl.sh](https://ttl.sh/) for local development.

tilt: use anonymous, ephemeral image registry

---

docs/Gemfile.lock
docs/_config.yml

Pin to a specific commit for reproducibility.
(cherry picked from commit 4faf4df1e4f612b900d408a1c121595810429237)

[release-0.14] docs: switch to jekyll-theme-read-the-docs

---

docs/_config.yml

Pin to a specific commit for reproducibility.
(cherry picked from commit 4faf4df1e4f612b900d408a1c121595810429237)

[release-0.13] docs: switch to jekyll-theme-read-the-docs

---

docs/_config.yml
docs/_includes/templates/addons.liquid
docs/_includes/templates/content.liquid
docs/_includes/templates/sidebar.liquid

Pin to a specific commit for reproducibility.
(cherry picked from commit https://github.com/kubernetes-sigs/node-feature-discovery/commit/4faf4df1e4f612b900d408a1c121595810429237)
Also, sync (docs/_includes) from master branch to work with the updated theme.

[release-0.9] docs: switch to jekyll-theme-read-the-docs

---

pkg/resourcemonitor/podresourcesscanner.go

Since not all pods may have resource limits defined(or devices), adjust the frequency of less valuable events. These are often more useful during debugging than in regular operation. Example, when topology-updater is installed, the pod gets bombarded with the scanner info logs:
```YAML
I0630 11:15:37.319246       1 podresourcesscanner.go:148] "scanning pod" podName="calico-apiserver-5d7c589bc4-mxnwh"
I0630 11:15:37.319267       1 podresourcesscanner.go:231] "pod doesn't have devices" podName="calico-apiserver-5d7c589bc4-mxnwh"
I0630 11:15:37.326157       1 podresourcesscanner.go:148] "scanning pod" podName="my-node-feature-discovery-master-659f8d956d-hq2t2"
I0630 11:15:37.326212       1 podresourcesscanner.go:231] "pod doesn't have devices" …
```

logging: refine logging level in pod resources scanner

---

pkg/resourcemonitor/podresourcesscanner.go
pkg/resourcemonitor/podresourcesscanner_test.go
test/e2e/utils/pod/pod.go

fix topology-updater cpu report

---

cmd/nfd-gc/main.go
cmd/nfd-master/main.go
cmd/nfd-topology-updater/main.go
cmd/nfd-worker/main.go
pkg/apis/nfd/nodefeaturerule/expression.go
pkg/nfd-gc/nfd-gc.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go
pkg/nfd-worker/nfd-worker_test.go
pkg/utils/featuregate/featuregate.go
pkg/utils/featuregate/featuregate_test.go
pkg/utils/memory_resources_test.go
scripts/test-infra/verify.sh
source/cpu/security_amd64.go
source/custom/api/conversion_test.go
source/kernel/kconfig.go
test/e2e/gomega.go

Also fix or silence errors from golangci-lint v2.4.0:
- unchecked return values (errcheck)
- nolint for Close() for read-only files and http servers
- unnecessary naming of embedded fields of structs (staticcheck)
- multiple imports of the same package (staticcheck)
- use switch-case instead of if/else (staticcheck)
- remove type from var declaration (staticcheck)
- remove "Yoda" condition from if (staticcheck)
- don't use dot imports

scripts/test-infra: bump golangci-lint to v2.4.0

---

cmd/nfd/subcmd/export/export.go
cmd/nfd/subcmd/export/features.go
cmd/nfd/subcmd/export/labels.go
cmd/nfd/subcmd/export/utils.go
docs/usage/nfd-export.md
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go

Problem: We want to statically export NFD features for HPC.
Solution: Add an `nfd export features` mode that allows for generation and export of static feature labels.
For the HPC use case, we want to be able to export static features, either to the screen (for inspection) or a file (for saving and use with a scheduler, or other compatibility checking algorithm).  Adding support for this is fairly easy - we need to just add the subcommand. The usage is simple and intuitive:
```bash
nfd export features
nfd export features --path features.json
nfd export labels
nfd export labels --path labels.json
```
The flag is also useful for cases beyond HPC when a quick inspection is desired. There are ways this could be extended (requesting specific groups or filters) but I think it's better to start …

feat: add ability to export features for static node

---

scripts/test-infra/verify.sh

Logcheck does not build/install with golang v1.25.

scripts/test-infra: temporarily disable logcheck

---

Makefile
scripts/test-infra/push-image.sh

For non-release builds, publish Helm chart with version `0.0.0-<branch-name>` in the OCI repo.

helm: publish rolling staging version of OCI chart

---

scripts/test-infra/push-image.sh

The _GIT_TAG variable is always specified (set by the prow job). We can determine whether we're building a tag or branch from the _PULL_BASE_REF.

scripts/test-infra/push-image: fix env variable parsing

---

cloudbuild.yaml

Needed by the latest version of push-image.sh script.

cloudbuild: export _PULL_BASE_REF as an env variable

---

deployment/helm/node-feature-discovery/templates/master-pdb.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc-pdb.yaml
deployment/helm/node-feature-discovery/values.yaml

A bunch of fixes to the Helm chart:
1. Drop unused master.featureApi from values.yaml
2. Drop featureRulesController parameter
The nfd-master does not have such commandline flag as `-featurerules-controller` anymore.
3. Fix master.extraEnvs
4. Fix PodDisruptionBudget

helm: fixes

---

scripts/test-infra/push-image.sh

If the _PULL_BASE_REF matches a release tag use that as the VERSION. This fixes a problem in cases we push multiple tags at the same time like:
git push origin v0.X.Y api/nfd/v0.X.Y
and the _GIT_TAG might be derived from the api/nfd/... tag.

scripts/test-infra/push-image: more robust parsing of version

---

deployment/helm/node-feature-discovery/templates/prometheus.yaml
deployment/overlays/prometheus/monitor.yaml

In https://github.com/kubernetes-sigs/node-feature-discovery/commit/7fccf2325b479839c2f859d68b99d9f7c45bfb0e the metrics endpoint was merged/renamed to . Unfortunately not for the . This PR fixes this.

fix(deploy,helm,overlays): use correct port for PodMonitor

---

README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

./hack/prepare-release.sh -g 1.25.1 v0.18.1

[release-0.18] Release v0.18.1
