Makefile
README.md
glide.lock
node-feature-discovery-job.json.template

This PR hosts docker image in quay.io (https://github.com/kubernetes-incubator/node-feature-discovery/issues/6). It updates makefile, job template and readme appropriately. I've tested it manually.

Hosted docker image in quay.io.

---

RELEASE.md

Adds more specific instructions for releasing.

---

.dockerignore
Dockerfile

Fixes #10. Update resolves all fixable vulnerabilities. Tested Manually.
- Updated to debian testing (stretch).
- Updated to go v1.7.
- Added .dockerignore file.

Fixed vulnerabilities in Docker image.

---

.travis.yml
README.md

- Updated .travis.yml.
- Updated readme to show build status.
Partially fixes #7.

Integrated with travis-ci.

---

demo/README.md
demo/docker-images/Dockerfile-CloverLeaf
demo/docker-images/Dockerfile-PARSEC
demo/helper-scripts/demo-pod-with-discovery.json.parsec.template
demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
demo/helper-scripts/demo-pod-without-discovery.json.template

- Hosted demo images in quay.io.
- Added dockerfiles for the demo images.
- Updated readme appropriately.

Updated demo.

---

demo/docker-images/Dockerfile-PARSEC

- Updated the demo dockerfile for parsec appropriately.

Hosted demo input data for parsec in S3.

---

main.go

The --label-whitelist option takes a regex and matches against labels.
If set, labels will only be published if they match the whitelist regex.
```
% docker run quay.io/kubernetes_incubator/node-feature-discovery:91b50e441347 --no-publish
2016-10-17 17:30:21.853659 I | node.alpha.intel.com/node-feature-discovery.version = d4eec17-dirty
2016-10-17 17:30:21.853975 I | node.alpha.intel.com/d4eec17-dirty-cpuid-SSE3 = true
2016-10-17 17:30:21.853993 I | node.alpha.intel.com/d4eec17-dirty-cpuid-BMI1 = true
2016-10-17 17:30:21.854007 I | node.alpha.intel.com/d4eec17-dirty-cpuid-RDTSCP = true
2016-10-17 17:30:21.854020 I | node.alpha.intel.com/d4eec17-dirty-cpuid-SSSE3 = true
2016-10-17 17:30:21.854032 I | node.alpha.intel.com/d4eec17-dirty-cpuid-SSE4.1 = true
2016-10-17 17:30:21.854045 I | …
```

Adds label-whitelist option.

---

README.md
main.go

Removed version from published label keys.

---

node-feature-discovery-job.json.template

- Changed container tag to v0.1.0 for the release.

Updated the container tag in the job template

---

rdt-discovery/l2-allocation-discovery.c
rdt-discovery/l3-allocation-discovery.c
rdt-discovery/monitoring-discovery.c

Clean-up RDT helper programs.

---

main.go
main_test.go
sources.go

Relates to #62. Coverage is now at 64%.
- Refactored code for testing purposes.
- Misc. comment changes.

Improved unit test coverage.

---

Dockerfile
glide.yaml
node-feature-discovery-job.json.template

This Pull Requests bump kubernetes go-client to lastest version.

bump client version 5.0.2

---

README.md
main.go
node-feature-discovery-job.json.template
source/network/network.go

PR in reference to https://github.com/kubernetes-incubator/node-feature-discovery/issues/35

Adding SR-IOV capability discovery to node-feature-discovery

---

README.md

Signed-off-by: Bin Lu <bin.lu@arm.com>

Add Arm64 details into the README

---

README.md
node-feature-discovery-daemonset.json.template
node-feature-discovery-job.json.template
rbac.yaml

* Add rbac.yaml which contains needed rules for NFD to work on a RBAC
enabled cluster
* Add lines to templates to use the RBAC policy
* Update README

Add RBAC policy

---

README.md
node-feature-discovery-daemonset.json.template
node-feature-discovery-job.json.template

Update the container image tags in the templates to v0.2.0

---

source/pstate/pstate.go

Signed-off-by: Bin Lu <bin.lu@arm.com>

check frequency boost support on Arm

---

source/rdt/rdt.go

Signed-off-by: Rui Cao <ruicao@alauda.io>

Fix typo: suppported -> supported

---

README.md
main.go
main_test.go
node-feature-discovery-daemonset.yaml.template
node-feature-discovery-job.yaml.template
node-feature-discovery.conf.example
source/kernel/kernel.go

Implement kernel feature source and add support for config file

Discover kconfig flags

---

source/cpuid/cpuid_amd64.go
source/cpuid/cpuid_arm64.go

Signed-off-by: Bin Lu <bin.lu@arm.com>

Add ARM64 support to cpuid

---

README.md

Add a paragraph about hook config files.

README: improve documentation of local hooks

---

OWNERS

I have some time to help with reviews for @marquiz

Add kad as reviewer in OWNERS file

---

OWNERS

I have some spare time too, happy to help to review PRs

Add zvonkok to OWNERS file as a reviewer 

---

README.md
source/local/local.go

The aim here is to add another way to specify labels using the local source by reading files in a specific directory. That avoids us to execute a hook when we just need to get the content of a file.
Close https://github.com/kubernetes-sigs/node-feature-discovery/issues/226
Signed-off-by: Jordan Jacobelli <jjacobelli@nvidia.com>

Allow to get labels by reading files in local source

---

OWNERS

I would like to help to review PRs

Add Ethyling to OWNERS file

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker_test.go

Make the --label-whitelist effective. Previously, it was unused and had
no effect. Also, add simple unit test for that.

nfd-master: fix --label-whitelist

---

Dockerfile

Better see what is happening inside the build.

Dockerfile: verbose dep ensure

---

pkg/nfd-worker/nfd-worker.go

Prevent worker from trying to connect to the master when the
--no-publish flag is specified.

nfd-worker: don't connect to master when --no-publish is used

---

Makefile

Makes testing with different go versions easier.

Makefile: define go binary in a make variable

---

README.md

Mention supported runtimes that the hooks can use and describe how hooks
and feature files can be used for injecting labels from other pods.

README: better document the usage of hooks and feature files

---

.gitignore

/assign @zvonkok 
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>

Update gitignore to include yaml files generated from template

---

README.md
cmd/nfd-master/main.go
nfd-master.yaml.template
pkg/apihelper/apihelpers.go
pkg/apihelper/k8shelpers.go
pkg/apihelper/mock_APIHelpers.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go

@marquiz 
#229 
This adds support for making selected labels extended resources.
Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

master: add extended resource support

---

README.md
cmd/nfd-worker/main.go
cmd/nfd-worker/main_test.go
nfd-worker.conf.example
pkg/nfd-worker/nfd-worker.go
source/custom/custom.go
source/custom/rules/loaded_kmod_rule.go
source/custom/rules/pci_id_rule.go
source/custom/rules/rule.go
source/custom/static_features.go
source/internal/pci_utils.go
source/pci/pci.go

Support custom features

---

go.mod
pkg/nfd-worker/nfd-worker.go
test/e2e/node_feature_discovery.go

Replace github.com/ghodss/yaml.

Switch to sigs.k8s.io/yaml

---

README.md

Shortly describe node annotations created/managed bu NFD.
Aimed at implementing #296

README: document node annotations

---

.travis.yml
Makefile
cmd/nfd-master/main.go
cmd/nfd-worker/main.go
pkg/cpuid/cpuid_amd64.go
pkg/cpuid/cpuid_amd64.s
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-worker/nfd-worker-internal_test.go
pkg/nfd-worker/nfd-worker.go
source/custom/custom.go
source/custom/rules/pci_id_rule.go
source/custom/rules/usb_id_rule.go
source/custom/static_features.go
source/internal/pci_utils.go
source/internal/usb_utils.go
source/kernel/kernel.go
source/local/local.go
source/panic_fake/fake_panic.go
source/source.go
test/e2e/node_feature_discovery.go

Integrate golangci-lint with our build. Fix lint errors.

Verify golangci-lint

---

.travis.yml
scripts/test-infra/build-image.sh
scripts/test-infra/verify.sh

A step towards moving away from TravisCI.

scripts: add scripts for kubernetest test-infra jobs

---

cloudbuild.yaml

Hopefully fixes failing builds:
https://testgrid.k8s.io/sig-node-node-feature-discovery#post-node-feature-discovery-push-images

cloudbuild.yaml: use correct tags

---

cloudbuild.yaml

Another attempt at making image builds succeed.
Also add an image tag for e2e-testing.

cloudbuild.yaml: fix docker build arguments

---

scripts/test-infra/verify.sh

Modify PATH in order to make sure that golangci-lint is found.

scripts: fix verify.sh

---

scripts/test-infra/build.sh

A script for verifying (non-docker) build.

scripts/test-infra: add build.sh

---

README.md

Now that we are utilizing Prow, why not to show off in the README :) 

Add prow badge

---

README.md

The references listed have lost relevance in this context.

README: drop References and unused links

---

docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/_includes/class/addons-wrap.liquid
scripts/test-infra/build-gh-pages.sh

Fix two separate issues that coincidentally occurred at the very same time.

scripts: fix gh-pages build failure in prow

---

README.md

README: fix link to Github pages

---

OWNERS

Inactive for way over two years, now.

OWNERS: drop balajismaniam

---

docs/get-started/features.md

Better explain where the rules configuration is supposed to be
specified.

docs: improve documentation of the custom source

---

.github/ISSUE_TEMPLATE/new-release.md
scripts/prepare-release.sh

A helper script for preparing the release branch.

scripts: add prepare-release.xh

---

README.md
docs/_config.yml
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
test/e2e/node_feature_discovery.go

Generated semi-automagically by running
$ scripts/prepare-release.sh v0.7.0

Update references to v0.7.0

---

go.mod
go.sum
source/internal/cpuidutils/cpuid_amd64.go

go.mod: update to klauspost/cpuid/v2@v2.0.2

---

nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
scripts/prepare-release.sh

Update prepare-release.sh so that the policy will be set to IfNotPresent
for releases.
Inspired by the discussion in #423

Set imagePullPolicy in the deployment templates to Always

---

Makefile
docs/advanced/architecture.md
docs/advanced/customization-guide.md
docs/advanced/developer-guide.md
docs/advanced/e2e-configuration-reference.md
docs/advanced/master-commandline-reference.md
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/introduction.md
docs/mdl-style.rb
scripts/test-infra/mdlint.sh

Also, fix issues so that we pass muster

docs: enable markdown linting

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go

- drop last remnants of log package
- change (some) Fatal* log messages to Exit*

Logging fixes

---

.github/ISSUE_TEMPLATE/new-release.md

Sync the default assignees with the project OWNERS file.

github: update new-release issue template assignees

---

README.md
deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/values.yaml
docs/_config.yml
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
test/e2e/node_feature_discovery.go

```
scripts/prepare-release.sh v0.8.0
```

release-0.8: update references to point to v0.8.0

---

docs/get-started/deployment-and-usage.md

While on the project website it looks OK, it does
not render correctly in Markdown.
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>

Docs: Add Table header to master/worker chart parameters

---

deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/templates/nfd-worker-conf.yaml

* Fix configMap indenting
* Update Chart.yaml
* Update nfd-worker-conf.yaml
(cherry picked from commit 33a6425d05a7a1bf9d6396cbba088ccb774c82bb)

Helm chart: Fix configMap indenting (#496)

---

scripts/prepare-release.sh

Add '-a' command line option to only create release assets and not patch
any files in the repo. E.g.
$ scripts/prepare-release.sh -a v0.8.0+1 user@example.com

scripts/prepare-release: option to only create assets

---

README.md
deployment/node-feature-discovery/Chart.yaml
docs/_config.yml
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
test/e2e/node_feature_discovery.go

Generated with scripts/prepare-release.sh

Update references to point to v0.8.1

---

deployment/node-feature-discovery/Chart.yaml
deployment/node-feature-discovery/templates/master.yaml
deployment/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

Signed-off-by: Jordan Jacobelli <jordanjacobelli04@gmail.com>
(cherry picked from commit 630e97a52c57f2061e2a50c3ac3461b661b47f45)

backport-0.8: helm: add extraLabelNs master flag

---

README.md
deployment/node-feature-discovery/Chart.yaml
docs/_config.yml
nfd-daemonset-combined.yaml.template
nfd-master.yaml.template
nfd-prune.yaml.template
nfd-worker-daemonset.yaml.template
nfd-worker-job.yaml.template
test/e2e/node_feature_discovery.go

Generated with scripts/prepare-release.sh

Update references to v0.8.2

---

pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
source/custom/custom.go
source/custom/directory_features.go
source/custom/rules/loaded_kmod_rule.go
source/custom/rules/nodename_rule.go
source/custom/static_features.go
source/internal/cpuidutils/cpuid_amd64.go
source/internal/pci_utils.go
source/iommu/iommu.go
source/local/local.go
source/pci/pci.go
source/usb/usb.go

Go report badge is showing `Found 40 issues across 61 files` , this are low hanging fruits to fix
- gofmt -s
- fix go lint's regarding proper var and func comments

make go report happy

---

pkg/nfd-master/nfd-master.go
source/custom/custom.go
source/local/local.go
source/pci/pci.go
source/usb/usb.go

Fix small mistakes that slipped through with lint fixes (in
1230945564179eba3645d0b216cfdf998efb1481).

Straighten wrinkles in lint fixes

---

docs/get-started/deployment-and-usage.md

This patch should be back ported to fix release v0.8.2 documentation

Remove wrong comands on documentation

---

docs/get-started/deployment-and-usage.md

(cherry picked from commit 59172007b29df077d99910ce12e13926e4445524)

backport-0.8: remove wrong commands from docs

---

docs/get-started/deployment-and-usage.md

(cherry picked from commit 59172007b29df077d99910ce12e13926e4445524)

backport-0.7: remove wrong commands from docs

---

deployment/node-feature-discovery/README.md
scripts/prepare-release.sh

Add minimal readme to the helm chart and update
scripts/prepare-release.sh to handle references in the readme file.
Fixes #510

helm: add readme

---

deployment/base/master-worker-combined/master-worker-daemonset.yaml
scripts/prepare-release.sh

Pull in the latest fixes from master

release-0.9: sync with master

---

README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/node_feature_discovery.go

scripts/prepare-release.sh v0.9.0 markus.lehtonen@intel.com

release-0.9: update references to v0.9.0

---

README.md

We don't have templates, anymore, but use kustomize.

release-0.9: README: fix deployment instructions

---

source/custom/rules/kconfig_rule.go

Use a more well-defined form with separate key and value fields.

source/custom: refactor kconfig rule internal representation

---

docs/get-started/deployment-and-usage.md

Fix a link in deployment-and-usage.md

---

docs/advanced/worker-configuration-reference.md
docs/get-started/deployment-and-usage.md

Backport some documentation fixes from master.

backports/v0.9: documentation fixes

---

docs/advanced/worker-configuration-reference.md

All configuration options are documented.

docs: remote wip note from worker configuration reference

---

docs/advanced/architecture.md
docs/advanced/customization-guide.md
docs/advanced/developer-guide.md
docs/advanced/e2e-configuration-reference.md
docs/advanced/master-commandline-reference.md
docs/advanced/worker-commandline-reference.md
docs/advanced/worker-configuration-reference.md
docs/get-started/deployment-and-usage.md
docs/get-started/examples-and-demos.md
docs/get-started/features.md
docs/get-started/introduction.md
docs/mdl-style.rb

Backport a bunch of documentation fixes

backports/v0.9: fixes to docs

---

docs/get-started/introduction.md

Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

Topology-updater introduction typo fix

---

docs/advanced/topology-updater-commandline-reference.md
docs/get-started/introduction.md

Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

More topology updater documentation typo fixes

---

docs/contributing/index.md

Update the link of slack channel

---

cmd/nfd-topology-updater/main.go
pkg/nfd-client/topology-updater/nfd-topology-updater.go
pkg/resourcemonitor/noderesourcesaggregator.go

topologyupdater: logs relevant message when feature-gate is disabled.

---

Makefile

Add deploy-prune makefile rule to ease devel processes

---

source/kernel/kconfig.go

Regexp is just a resource hog here and does not simplify the code.

source/kernel: ditch regexp in kconfig parsing

---

source/local/local.go

With `-v 4` user can now see the features originating per each file.
Makes debugging easier.

source/local: log features per each hook and feature file

---

docs/get-started/deployment-and-usage.md
docs/get-started/index.md

Ref #712 where we mentioned creating separate TLS docs.

Initial bash at new TLS docs

---

deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/node_feature_discovery.go

scripts/prepare-release.sh v0.10.0 markus.lehtonen@intel.com

release-0.10: update references to release v0.10.0

---

Makefile

Adding missing target dep

---

cloudbuild.yaml
scripts/test-infra/test-e2e.sh

Fourth timeout increase's the charm.

cloudbuild.yaml: increase timeout to 1h 20min

---

cloudbuild.yaml

Hopefully speeds up our multi-arch builds.

cloudbuild.yaml: upgrade machine type to n1-highcpu-8

---

docs/get-started/deployment-and-usage.md

docs: update helm document to match values.yaml

---

docs/get-started/deployment-and-usage.md

(cherry picked from commit f302962519058644dbc52c30d662f1a948c4a06d)

[release-0.7] docs: fix operator deployment instructions

---

go.mod
go.sum

The new version adds Control-flow Enforcement Technology (CET)
bits detection.

go.mod: update to klauspost/cpuid/v2@v2.0.11

---

.github/ISSUE_TEMPLATE/new-release.md
docs/advanced/customization-guide.md
docs/advanced/developer-guide.md
docs/get-started/deployment-and-usage.md

Fix a couple typos

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

Signed-off-by: Cyril Corbon <cyril.corbon@dailymotion.com>
helm: add possibility to set annotations for deployment and daemonset

helm: add annotations to daemonset and deployment

---

README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
docs/advanced/developer-guide.md
test/e2e/node_feature_discovery.go

scripts/prepare-release.sh v0.11.0 markus.lehtonen@intel.com

[release-0.11] Update references to release v0.11.0

---

README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/node_feature_discovery.go

scripts/prepare-release.sh v0.11.1 markus.lehtonen@intel.com

Update references to release v0.11.1

---

go.mod
go.sum

Adds e.g. detection of Intel TME.

go.mod: update github.com/klauspost/cpuid to v2.0.14

---

test/e2e/node_feature_discovery.go

The test was broken twofold: Firstly, the annotation was not checked at
all because the name of the node where nfd-master is running was not
set. Secondly, the annotation prefix was used incorrectly.

test/e2e: fix checking of nfd-master annotation

---

deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/get-started/deployment-and-usage.md

Add `worker.priorityClassName`, which sets `.spec.priotiryClassName` in `worker` DaemonSet

helm: add priorityClassName to worker

---

README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/node_feature_discovery.go

scripts/prepare-release.sh v0.11.2 markus.lehtonen@intel.com

[release-0.11] Update references to release v0.11.2

---

netlify.toml

This patch adds netlify configuration file which includes steps needed to build
the documentation as part of presubmit review process. I was planning to add
these commands from the web UI, but it is better to keep it here transparency
and the version control purposes.
Prerequisite for https://github.com/kubernetes-sigs/node-feature-discovery/issues/886 and https://github.com/kubernetes/org/issues/3665

Add Netlify configuration file

---

pkg/nfd-master/nfd-master.go

Be a bit more verbose what is happning.

nfd-master: log if node was modified (or not)

---

pkg/apihelper/apihelpers.go
pkg/apihelper/k8shelpers.go
pkg/apihelper/mock_APIHelpers.go
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/resourcemonitor/noderesourcesaggregator.go
pkg/resourcemonitor/podresourcesscanner.go
pkg/utils/memory_resources.go
pkg/utils/memory_resources_test.go
test/e2e/node_feature_discovery.go
test/e2e/topology_updater.go
test/e2e/utils/node.go
test/e2e/utils/noderesourcetopology.go
test/e2e/utils/pod.go
test/e2e/utils/rbac.go
test/e2e/utils/service.go

Standardize `k8s.io/api/core/v1` package short naming across the repo.

Standardize "k8s.io/api/core/v1" package short name

---

README.md
docs/get-started/index.md
docs/get-started/quick-start.md

/kind cleanup
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

Stop using the beta.kubernetes.io/os and arch labels

---

test/e2e/node_feature_discovery.go

Replace with a ConfigMap-based configuration.

test/e2e: remove dropped -sleep-interval arg

---

test/e2e/node_feature_discovery.go
test/e2e/utils/crd.go

After introducing NodeFeatureRule we packed two CRD definitions in one yaml file. Our e2e-tests were not prepared to that and the file itself was also renamed so it couldn't even be read by the test suite.
With this change the e2e-tests start to create NodeFeatre CRD in the test cluster, preparing for the addition of e2e-tests for NodeFeature API.

test/e2e: fix creation of NFD CRDs

---

test/e2e/node_feature_discovery.go

Only generate CRDs once in the beginning of the test run. Use the "Ordered" option for the test container so that we can utilize ginkgo.BeforeAll to only do stuff once before the first test. Changing from unordered to ordered shouldn't make a big difference here.
Add a cleanup function to remove stale NodeFeatureRule objects that are cluster-scoped and not deleted with the test namespace.

test/e2e: create CRDs once in the beginning of the tests

---

test/e2e/node_feature_discovery.go

Without this e2e tests may fail in clusters with control-plane-only
nodes.

test/e2e: don't expect control-plane nodes to be labeled

---

.github/ISSUE_TEMPLATE/new-release.md

Add instructions about creating prow jobs for new release branches.

github: update new-release issue template

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/node_feature_discovery.go

hack/prepare-release.sh -g 1.19.4 v0.12.0

[release-0.12] Update references to release v0.12.0

---

README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml
test/e2e/e2e_test.go

Created with:
hack/prepare-release.sh -g 1.19.5 v0.12.1

[release-0.12] Update references to release v0.12.1

---

deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/helm/node-feature-discovery/templates/master.yaml

Resolves #883.
Signed-off-by: AhmedGrati <ahmedgrati1999@gmail.com>

deployment: disable service links in NFD master pod

---

.github/ISSUE_TEMPLATE/new-release.md
OWNERS

I recently changed my username from `Ethyling` to `jjacobelli` so I'm updating the `OWNERS` file to reflect this change

OWNERS: Update Ethyling username to jjacobelli

---

test/e2e/node_feature_discovery_test.go

Make sure that stale NodeFeature objects from previous test case are not interfering the next one.

test/e2e: cleanup NodeFeature objects before/after tests

---

docs/usage/customization-guide.md

Fix the usage customization guide typos.

docs: fix usage customization guide typos

---

docs/_includes/class/content-wrap.liquid

[release-0.6] docs: mark release as unsupported

---

OWNERS

OWNERS: add PiotrProkop as a reviewer

---

Dockerfile_generator
deployment/base/nfd-crds/nfd-api-crds.yaml
deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml

Update controller-gen tool from sigs.k8s.io/controller-tools to the latest release.
Also, bump goimports from golang.org/x/tools to the latest version.

generate: update controller-gen to v0.11.3

---

pkg/nfd-master/nfd-master.go

Better this way than to crash which is what currently happens with this combination.

nfd-master: support noPublish with -prune

---

OWNERS

Also adds marquiz as a reviewer so that all approvers are also reviewers.
Resolves #1175

OWNERS: add ArangoGutierrez as an approver

---

scripts/test-infra/verify.sh

In the hopes that codecov will be properly showing and calculating the diff.

scripts/test-infra: provide PR base SHA to codecov

---

Makefile
cmd/nfd-master/main.go
deployment/components/master-config/nfd-master.conf.example
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
pkg/nfd-master/nfd-master-internal_test.go
pkg/nfd-master/nfd-master.go
pkg/nfd-master/node-updater-pool.go

feat: parallelize nodes update

---

deployment/helm/node-feature-discovery/templates/master.yaml

else statement of crd-controller should
also refer to crd-controller flag.

fix typo in helm chart

---

.github/ISSUE_TEMPLATE/new-release.md

github: update assignees in new-release issue template

---

pkg/nfd-topology-gc/nfd-nrt-gc.go

Hopefully makes the code slightly more readable.

topology-gc: simplify listing of node objects

---

pkg/nfd-master/node-updater-pool_test.go

test: add node updater pool unit tests

---

docs/usage/customization-guide.md

Hooks are deprecated so describe feature files first.

docs: demote hooks in the customization guide

---

test/e2e/nfd_gc_test.go

Also remove some leftover debug print.

e2e/test: make the nfd-gc test pass on one-node cluster

---

README.md
deployment/base/gc/gc.yaml
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

hack/prepare-release.sh -g 1.20.8 v0.14.1

[release-0.14] Update references to release v0.14.1

---

Makefile
README.md
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topology-gc/topology-gc.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

hack/prepare-release.sh -g 1.20.8 v0.13.5

[release-0.13] Update references to release v0.13.5 and bump Go to v1.20.8

---

pkg/nfd-master/metrics.go
pkg/nfd-master/nfd-master.go
pkg/nfd-topology-updater/metrics.go
pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-worker/metrics.go
pkg/nfd-worker/nfd-worker.go
pkg/utils/metrics.go

Move common boilerplate code under pkg/utils.

Refactor metrics

---

deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
deployment/helm/node-feature-discovery/templates/clusterrole.yaml
deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-master-conf.yaml
deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
deployment/helm/node-feature-discovery/templates/role.yaml
deployment/helm/node-feature-discovery/templates/rolebinding.yaml
deployment/helm/node-feature-discovery/templates/service.yaml
deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

feat: add parameters in helm to disable/enable nfd-master and nfd-worker

---

test/e2e/node_feature_discovery_test.go

We dropped the legacy rule format so we need to convert the e2e test rules to the new format, accordingly.

test/e2e: fix source/custom nodename test

---

test/e2e/node_feature_discovery_test.go

Fix some typos and improve log messages a bit.

test/e2e: fix log messages

---

docs/get-started/introduction.md

List tracking annotations for taints and feature annotations.

docs: document all tracking annotations

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

hack/prepare-release.sh -g 1.21.5 v0.15.0

[release-0.15] Update references to release v0.15.0

---

Makefile

Create binaries under bin/ rather than a binary named bin.

makefile: fix build: target

---

source/cpu/cpu.go

See https://github.com/kubernetes-sigs/node-feature-discovery/pull/1497#discussion_r1426426249

chore: combine cpu count and thread_siblings functions into discover topology function

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Manually generated with:
./hack/prepare-release.sh -g 1.21.6 v0.15.1

[release-0.15] Update references to release v0.15.1

---

OWNERS

Also, sort the names alphabetically.
Fixes #1563

OWNERS: add AhmedGrati as a reviewer

---

pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/resourcemonitor/podresourcesscanner.go
pkg/resourcemonitor/podresourcesscanner_test.go

Stop using pkg/apihelper for accessing the Kubernetes API. Modify unit tests to use the fake kubernetes client instead of mocked apihelper interface.
Part of #1561

topology-updater: ditch apihelper

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Manually generated with:
./hack/prepare-release.sh -g 1.21.8 v0.15.2

[release-0.15] Update references to release v0.15.2

---

pkg/nfd-topology-updater/nfd-topology-updater.go
pkg/nfd-worker/nfd-worker.go

The stop channel was not being closed properly

Use close to signal stop channedl in worker and topology-updater

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master-worker-combined/master-worker-daemonset.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Manually generated with:
./hack/prepare-release.sh -g 1.20.14 v0.14.5

[release-0.14] Update references to release v0.14.5

---

README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Manually generated with:
./hack/prepare-release.sh -g 1.21.8 v0.15.3

[release-0.15] Update references to release v0.15.3

---

OWNERS

You can check that both have the same email.

replace AhmedGrati account with TessaIO as reviewer

---

pkg/nfd-master/node-updater-pool.go

Make the node-updater-pool worker fail fast (and not retry updates) if a node does not exist.

nfd-master: check if node exists before trying update

---

cmd/nfd-master/main.go
cmd/nfd-worker/main.go
docs/deployment/tls.md
docs/developer-guide/index.md
docs/reference/master-commandline-reference.md
docs/reference/master-configuration-reference.md
docs/reference/worker-commandline-reference.md
docs/usage/customization-guide.md
test/e2e/node_feature_discovery_test.go

Fix documentation, code and e2e-tests.

Remove references to -enable-nodefeature-api flag

---

pkg/nfd-master/node-updater-pool.go

Treat node updates like a reconciliation loop. Keep trying on node
update as long as it fails. Node update permafailing likely indicates a
bug in the nfd code (there should be no reason for it to fail forever)
and it's better to clearly see it in the logs/metrics rather than giving
up after a few retries.
Depends on #1595

nfd-master: retry node updates indefinitely

---

cmd/nfd-worker/main.go
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
pkg/nfd-worker/nfd-worker.go

nfd-worker: Add liveness probe

---

pkg/nfd-master/nfd-master.go

Prevents potential race between node-updater pool and the api-controller when re-configuring nfd-master. Reconfiguration causes a new api-controller instance to be created so nfd api lister might change in the midst of processing a node update (if the pool was running). No actual issues related to this have been identified but races (like this) should still be avoided.

nfd-master: stop node-updater pool before reconfiguring api-controller

---

pkg/nfd-master/nfd-master-internal_test.go

Some improvements to the unit-test file of nfd-master.

chore/nfd-master: remove warnings in nfd-master unit tests file

---

api/nfd/v1alpha1/feature.go
api/nfd/v1alpha1/feature_test.go
pkg/apis/nfd/nodefeaturerule/rule_test.go
source/fake/fake.go
source/pci/pci.go
source/usb/usb.go

Make usage of this helper function more flexible.

api/nfd: use varargs in the NewInstanceFeatures helper

---

README.md

made with `./hack/prepare-release.sh`

Update README to v0.16.1

---

api/nfd/v1alpha1/feature_test.go
pkg/apis/nfd/nodefeaturerule/expression-api_test.go
source/custom/static_features.go
source/fake/fake.go
source/pci/pci_test.go

Simplify code

---

README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Created with `./hack/prepare-release.sh -g 1.21.12 v0.15.6`

Release v0.15.6

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

Made with `hack/prepare-release.sh`

Release v0.16.2

---

deployment/helm/node-feature-discovery/templates/master.yaml
deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Signed-off-by: Omer Aplatony <omerap12@gmail.com>
(cherry picked from commit 920306cba8bb1b9cc06b26313ccdf6e02da95561)

[release-0.16] Add revision history limit for master replica and for garbage collector

---

docs/reference/master-commandline-reference.md

Docs: Fixed feature-gates reference

---

pkg/nfd-gc/nfd-gc.go
pkg/nfd-gc/nfd-gc_test.go

Significantly reduce the apiserver and network load by only listing/getting the object metadata.

nfd-gc: only fetch object metadata

---

test/e2e/node_feature_discovery_test.go

The Kubernetes e2e framework now supports setting the pod security level.

test/e2e: drop the pod security admission hack

---

pkg/nfd-master/updater-pool.go

We store the work queues in the updater pool struct so we don't need to pass those as function arguments.

nfd-master: cleanup updater-pool method args

---

deployment/helm/node-feature-discovery/values.yaml

Fixes an omission in 843fc9307dda0173c39e695817aa688819dbb04c.

helm: rename args to extraArgs in values.yaml

---

README.md
docs/deployment/kustomize.md
docs/deployment/uninstallation.md
docs/get-started/quick-start.md

Makes them work with zsh which tries to glob URLs containing query parameters (question marks).
Refs: #1877

docs: quote shell snippets containing urls with query parameters

---

cmd/nfd-master/main.go

nfd-master: drop stale unreachable deprecation notices

---

Makefile
cmd/nfd-gc/main.go
cmd/nfd-master/main.go
cmd/nfd-topology-updater/main.go
cmd/nfd-worker/main.go
scripts/github/update-gh-pages.sh
scripts/test-infra/test-e2e-presubmit.sh

Backports:
- #1974 
- #1977 
- #1981 
Fixes #1971

[release-0.16] Fix version parsing

---

Makefile
README.md
deployment/base/gc/gc.yaml
deployment/base/master/master-deployment.yaml
deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
deployment/base/worker-daemonset/worker-daemonset.yaml
deployment/base/worker-job/worker-job.yaml
deployment/helm/node-feature-discovery/Chart.yaml
deployment/helm/node-feature-discovery/README.md
deployment/helm/node-feature-discovery/values.yaml
deployment/overlays/prune/master-job.yaml
docs/_config.yml

./hack/prepare-release.sh -g 1.23.4 v0.17.0

[release-0.17] Prepare v0.17 release

---

deployment/helm/node-feature-discovery/templates/worker.yaml

helm: fix usage of worker.extraArgs

---

examples/grafana-dashboard.json

This PR allows the substitution to be used since the datasource was not being picked up correctly

Allow DS_PROMETHEUS substitution for grafana dashboard

---

go.mod
go.sum

Adds detection of AMXCOMPLEX and AMXTF32.

go.mod: bump cpuid to v2.2.10

---

source/cpu/pstate_amd64.go

source/cpu: suppress cpufreq related error if driver is not enabled

---

pkg/apis/nfd/nodefeaturerule/rule.go
pkg/client-nfd/compat/node-validator/node-validator_test.go

Bugfix: handle matchAny and matchFeatures when they appear in one spec

---

pkg/apis/nfd/nodefeaturerule/rule.go

Use a common function for handling both LabelsTemplate and VarsTemplate fields of NodeFeatureRule.

nodefeaturerule: refactor template handling

---

api/nfd/v1alpha1/types.go
docs/usage/customization-guide.md
pkg/apis/nfd/nodefeaturerule/expression.go
pkg/apis/nfd/nodefeaturerule/expression_test.go

This PR extends the operators list with the following:
* Le - lower than or equal
* Ge - greater than or equal
* LeGe - range that includes boundary values

Add new comparison operators

---

pkg/apis/nfd/nodefeaturerule/expression.go
pkg/apis/nfd/template/template.go
pkg/kubectl-nfd/dryrun.go
pkg/nfd-gc/nfd-gc_test.go
pkg/nfd-master/updater-pool.go
pkg/utils/featuregate/featuregate.go
pkg/utils/flags.go
pkg/utils/memory_resources.go
pkg/utils/memory_resources_test.go
source/custom/api/expression.go
source/kernel/kconfig.go
source/memory/memory.go
source/usb/utils.go
test/e2e/node_feature_discovery_test.go

Applied improvements to loops and maps based on recommendations from
```shell
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest ./...
```

Apply modernize analysis improvements

---

docs/usage/customization-guide.md
source/network/network.go

Read MTU attribute for physical and virtual devices.

Discover MTU of physical and virtual network devices

---

pkg/nfd-master/nfd-api-controller.go

Drop effectively unused parameter. The NodeFeatureAPI feature gate has been locked to true.

nfd-master: clean up api controller

---

pkg/nfd-master/nfd-master.go

Fix a serious memory leak of non-leaders that was caused by bad chan usage. With leader election enabled, the nfdAPIUpdateHandler() was not started for non-leader instances, and thus, there was no reader for the chans that the nfdController uses to communicate what objects to update. This, in turn caused blocking in the kubernetes API informer context (trying to queue data into the chan), piling up requests on each NodeFeature update, consuming more and more memory (that would not be released unless we became the leader).
Fixes: #2063

nfd-master: fix memory leak when leader election is enabled

---

Makefile

@marquiz
Should these eventually be triggered from 'hack/prepare-release.sh'?
Or is that script a better place for this?

Makefile: Add helm-push target

---

scripts/test-infra/push-image.sh

@marquiz
I am not quite sure if this is enough, would it be possible to smoke test on your side?

scripts: Add helm-push to push-image.sh script

---

deployment/helm/node-feature-discovery/templates/worker.yaml
deployment/helm/node-feature-discovery/values.yaml
docs/deployment/helm.md

Related to: #2127
I remain open to any suggestions or proposals for improvement.

add configurable  worker daemonset updateStrategy in Helm chart

---

.github/ISSUE_TEMPLATE/support.md
docs/contributing/index.md

See https://github.com/kubernetes/community/issues/8240

renamed google group for SIG Node

---

.github/workflows/gh-pages.yml
docs/_config.yml
docs/_includes/templates/addons.liquid
docs/_includes/templates/content.liquid
docs/_includes/templates/sidebar.liquid

Manual cherry-pick of #2221 (plus #466)

[release-0.7] docs: switch to jekyll-theme-read-the-docs

---

Makefile
Tiltfile
go.mod

At the same time change builder image base from Debian bookworm to trixie.

Bump golang to v1.25

---

README.md
netlify.toml

Also updates the netlify redirect.

README: release v0.18.0
